# -*- mode: mandoku-tls-view -*-
#+TITLE: ADMIT
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= ADMIT
:PROPERTIES:
:CUSTOM_ID: uuid-5a62b4b0-8b8c-43fd-87d2-bc767d5a2000
:SYNONYM+:  CONCEDE
:SYNONYM+:  CONFESS
:SYNONYM+:  ACKNOWLEDGE
:SYNONYM+:  OWN
:SYNONYM+:  CONCEDE
:SYNONYM+:  GRANT
:SYNONYM+:  ACCEPT
:SYNONYM+:  ALLOW
:SYNONYM+:  REVEAL
:SYNONYM+:  DISCLOSE
:SYNONYM+:  DIVULGE
:SYNONYM+:  PLEAD GUILTY
:TR_ZH: 承認
:END:
** DEFINITION

ASSENT to what the LISTENER has in the PAST DECLARED to be TRUE OR what the LISTENER is BELIEVED to BELIEVE is TRUE.

** NOTES

*** Old Chinese Criteria
I cannot think of a good way of expressing the speech act of admission or of conceding the truth of what someone else has said in classical Chinese.

*** Modern Chinese Criteria
承認 is the general term for admitting or acknowledging something.

認錯 refers to the admission of a mistake.

認罪 refers to the admission of guilt.

認帳 refers to an acknowledgement of a responsibility which imposes duties on one.

認輸 refers to an acknowledgement of defeat.

認命 refers to the acknowledgement that something is one's fate.

Compare also:

確認 refers specifically to the confirmation that something which may or may not be pleasant to the speake is the case.

認可 refers to approval of something as true or acceptable, the speaker being a person in authority.

肯定 refers to a positive appraisal or confirmation of something as being true.

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** POINTERS
*** TAXONOMY
 - [[tls:concept:APOLOGISE][APOLOGISE]]
 - [[tls:concept:SURRENDER][SURRENDER]]
 - [[tls:concept:CONFESS][CONFESS]]

*** ANTONYMY
 - [[tls:concept:DENY][DENY]]

*** WORDNET synsets
 - 00818972

*** KIND OF
 - [[tls:concept:ASSENT][ASSENT]]

** SOURCE REFERENCES
*** APRESJAN 2004
 - [[cite:APRESJAN-2004][Apresjan(2004), Novyj objasnitel'nyj Slovar' Sinonimov Russkogo Jazyka]], p.854

*** BUCK 1988
 - [[cite:BUCK-1988][BUCK(1988), A Dictionary of Selected Synonyms in the Principal Indo-European Languages]], p.18.33

*** DOEDERLEIN 1840
 - [[cite:DOEDERLEIN-1840][Doederlein(1840), Lateinische Synonyme und Etymologien]]

ADMIT

fateri refers to an act of disclosing something in a very general sense, as opposed to celare "to hide".

profiteri refers to a free and spontaneous act of avowal of a belief one holds, unprovoked by questions; and this act is typically proud and assertive.

confiteri refers to an act of confession provoked by questions, threats or the like; and this act is typically contrite.

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 可 kě (OC:khlaalʔ MC:khɑ )
:PROPERTIES:
:CUSTOM_ID: uuid-26532e5a-65f1-4919-8ad6-47848592c07a
:Char+: 可(30,2/5) 
:GY_IDS+: uuid-6e6b769a-36c6-400e-8a2a-02e63bc15a1e
:PY+: kě     
:OC+: khlaalʔ     
:MC+: khɑ     
:END: 
**** V [[tls:syn-func::#uuid-3eaef22c-6bef-4126-93dd-a81945be2058][vt+S]] / concede, admit
:PROPERTIES:
:CUSTOM_ID: uuid-f975ed90-18d1-4040-a39d-883a815ef9df
:END:
****** DEFINITION

concede, admit

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
