# -*- mode: mandoku-tls-view -*-
#+TITLE: ALLIANCE
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= ALLIANCE
:PROPERTIES:
:CUSTOM_ID: uuid-b5ea778f-bf2e-4634-af96-47696877f47c
:SYNONYM+:  ASSOCIATION
:SYNONYM+:  UNION
:SYNONYM+:  LEAGUE
:SYNONYM+:  CONFEDERATION
:SYNONYM+:  FEDERATION
:SYNONYM+:  CONFEDERACY
:SYNONYM+:  COALITION
:SYNONYM+:  CONSORTIUM
:SYNONYM+:  AFFILIATION
:SYNONYM+:  PARTNERSHIP
:END:
** DEFINITION

CONTRACT in which GROUPS PROMISE to COOPERATE.

** NOTES

*** Old Chinese Criteria
SEE CONTRACT 1. Méng 盟 are between feudal lords, shì 誓 can be between any respectable private individuals.

2. Méng 盟 involves the blood of sacrificial domestic animals, shì 誓 does not normally involve the use of sacrificial animals..

3. Méng 盟 involves invocation through the blood of sacrificial animals, and it is typically in red writing, while shì 誓 is by the use of invocation of the spirits through words only, inviting the gods to punish those who break the oath. Occasionally this can be accompanied by casting a jade object into the river.

4. Shì 誓 can be an oath sworn by one individual, whereas méng 盟 is always a covenant between different parties. See CONTRACT.

Zhan Jinsen 1991

*** Modern Chinese Criteria
結盟

會盟

同盟

聯盟

歃血為盟



拜盟

拜把子

結拜

結義

換帖

義結金蘭

** POINTERS
*** WORDNET synsets
 - 06786485

*** KIND OF
 - [[tls:concept:CONTRACT][CONTRACT]]

** SOURCE REFERENCES
*** HANFEI TONGYI 2004
 - [[cite:HANFEI-TONGYI-2004][Zhao(2004), 韓非子同義詞研究]], p.303

*** GIRARD 1769
 - [[cite:GIRARD-1769][Girard Beauzée(1769), SYNONYMES FRANÇOIS, LEURS DIFFÉRENTES SIGNIFICATIONS, ET LE CHOIX QU'IL EN FAUT FAIRE Pour parler avec justesse]], p.1.333.295
 (ALLIANCE.LIGUE.CONFEDERATION)
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
