# -*- mode: mandoku-tls-view -*-
#+TITLE: BUDDHIST RITUALS
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= BUDDHIST RITUALS
:PROPERTIES:
:CUSTOM_ID: uuid-55941b9a-d0ef-4e2e-ac38-0a22c460bcb5
:END:
** DEFINITION



** NOTES

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 摩頂 módǐng (OC:maal teeŋʔ MC:mʷɑ teŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-3908252c-57dd-496a-ab60-332eb8caf35d
:Char+: 摩(64,11/14) 頂(181,2/11) 
:GY_IDS+: uuid-62efd968-fcbb-4774-9c42-a22187c35c91 uuid-babfe1c9-600b-4fe4-8c61-46d6ad2a47e9
:PY+: mó dǐng    
:OC+: maal teeŋʔ    
:MC+: mʷɑ teŋ    
:END: 
**** SOURCE REFERENCES
***** FOGUANG
 - [[cite:FOGUANG][Cí 慈(unknown), 佛光大辭典 Fóguāng dàcídiǎn The Foguang Dictionary of Buddhism]], p.6075b

**** V [[tls:syn-func::#uuid-091af450-64e0-4b82-98a2-84d0444b6d19][VPi]] {[[tls:sem-feat::#uuid-f55cff2f-f0e3-4f08-a89c-5d08fcf3fe89][act]]} / BUDDH: to rub one's forehead is a symbol for the transmission of the dharma and the prediction of f...
:PROPERTIES:
:CUSTOM_ID: uuid-08ba2cfe-c547-44a8-88f8-2e9eac94d1c3
:END:
****** DEFINITION

BUDDH: to rub one's forehead is a symbol for the transmission of the dharma and the prediction of future Buddhahood. Compare LOTUS: 釋迦牟尼佛從法座起，現大神力，以右手摩無量菩薩摩訶薩頂。('the Buddha rose from his dharma-seat, displayed great supernatural powers and with his right hand rubbed the forehead of countless great Bodhisattvas').

****** NOTES

*** 灌頂 guàndǐng (OC:koons teeŋʔ MC:kʷɑn teŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-aedf5973-b3f0-40ee-9ad6-e552951bee83
:Char+: 灌(85,18/21) 頂(181,2/11) 
:GY_IDS+: uuid-fd8c8417-4a52-4610-a4e6-3d5b4b3598ce uuid-babfe1c9-600b-4fe4-8c61-46d6ad2a47e9
:PY+: guàn dǐng    
:OC+: koons teeŋʔ    
:MC+: kʷɑn teŋ    
:END: 
**** SOURCE REFERENCES
***** FOGUANG
 - [[cite:FOGUANG][Cí 慈(unknown), 佛光大辭典 Fóguāng dàcídiǎn The Foguang Dictionary of Buddhism]], p.6853a-6854b

**** N [[tls:syn-func::#uuid-db0698e7-db2f-4ee3-9a20-0c2b2e0cebf0][NPab]] / (BUDDH:) water-pouring ceremony (this term is of pre-Buddhist origin and denotes a ceremony on the ...
:PROPERTIES:
:CUSTOM_ID: uuid-987ad09d-3996-4c39-a183-52f0949bf7b4
:END:
****** DEFINITION

(BUDDH:) water-pouring ceremony (this term is of pre-Buddhist origin and denotes a ceremony on the occasion of a king's ascending of the throne, or as ceremony for conforming somebody as crown prince; in the AVATAMSAKA it is mentioned that a Bodhisattva of the 9th stage, on the occasion of entering the tenth stage of his development, undergoes a ceremnoy where Buddhas sprinkle his forehead with 'prajñā water' (智水), confirming that he entered the stage of a 'Dharma-king' (法王); as such in some sutras the tenth stage of a Bodhisattva is also referred to as 灌頂地; the ceremony also plays an important role in esoteric Buddhism, 密教); skr. abhiṣecana, abhiṣeka

****** NOTES

******* Examples
T.4/218: 801c21 在於某方受王灌頂。 

T.8/244: 789c24-25 汝受灌頂已當普為眾生增長諸佛法住於平等心 



**** V [[tls:syn-func::#uuid-091af450-64e0-4b82-98a2-84d0444b6d19][VPi]] {[[tls:sem-feat::#uuid-f55cff2f-f0e3-4f08-a89c-5d08fcf3fe89][act]]} / (BUDDH:) pour water over the forehead (this term is of pre-Buddhist origin and denotes a ceremony o...
:PROPERTIES:
:CUSTOM_ID: uuid-d93ce48d-7399-4d14-a0df-46b296f69778
:END:
****** DEFINITION

(BUDDH:) pour water over the forehead (this term is of pre-Buddhist origin and denotes a ceremony on the occasion of a king's ascending of the throne, or as ceremony for conforming somebody as crown prince; in the AVATAMSAKA it is mentioned that a Bodhisattva of the 9th stage, on the occasion of entering the tenth stage of his development, undergoes a ceremnoy where Buddhas sprinkle his forehead with 'prajñā water' (智水), confirming that he entered the stage of a 'Dharma-king' (法王); as such in some sutras the tenth stage of a Bodhisattva is also referred to as 灌頂地; the ceremony also plays an important role in esoteric Buddhism, 密教); skr. abhiṣecana, abhiṣeka

****** NOTES

******* Examples
T.1/38: 821a24 有剎帝利大灌頂王。已受灌頂得輪王位。

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
