# -*- mode: mandoku-tls-view -*-
#+TITLE: BUDDHIST GARMENT
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= BUDDHIST GARMENT
:PROPERTIES:
:CUSTOM_ID: uuid-811258cf-a100-4c80-ac25-2dea8ef6182b
:END:
** DEFINITION



** NOTES

** SOURCE REFERENCES
*** FAURE 1995
 - [[cite:FAURE-1995][Faure(), Quand l'habit fait le moine Cahiers d'extrěme-Asie]]
*** KIESCHNICK 2003
 - [[cite:KIESCHNICK-2003][Kieschnick(2003), The Impact of Buddhim on Chinese Material Culture]], p.86-107


CONCISE SUMMARY:

the three monks' robes: already in Indian Buddhist texts the typical garment for monks was described of consisting of three items: a rectangular piece of cloth which was wrapped around the waist, covering the lower part of the body (this inner robe, skr. antarv$asa) was always worn, also during periods of work; another piece of cloth was draped over the left shoulder (upper garment, skr. uttar$asa$nga), covering the upper part of the body; third robe, the upper garment (skr. sa$mg$a$ti) was usually worn when the monk was in the public, for examples on begging tours; although the basic design of this outfit is quite simple, there were many complex variations concerning these robes and the outer robe could be made several strips (tia2o 條) of cloth (usually 5, 7, 9, 13, 15, or even more; each stip consists of several patches, ge2 隔); there were also careful descriptions how to sew a robe, using different  kinds of stiching technics; in China there were many controversies concerning the proper style of monks' robes; in the course of time the robe was highly charged with symbolism the the three robes sometimes represented different sets of Buddhist terms (e.g. the three poisons greed, anger, and ignorance and their respective elimination; another symbolic connection were the three realms 三界 or the three assemblis 三會). There is evidence that the original Indian style of robe was brought to China, but underwent changes in the course of time, and there was an adaption to Chinese customs, climate, etc. Gradually, there deveoped the sleeved robe, typical of East-Asian Buddhism, usually combined with trousers; at the end of the Tang - after having been criticised for long periods of time - this style of robe seems to have been firmly established; the outer robe - originally also a rectangular piece of cloth - became heavily charged with symbolism and were still made of a number a patches; however, although originally symbolizing the poverty of a monk, often the outer robe is China (and later Japan) was eventually made of especially fine and colorful materials, becoming a status symbol for high-ranking priests. In order to hold the robe in place, eventually a ring and ribbon (gouniu 鉤紐) was attached to it. In medieval China there was also an extended discussion about the use of silk for monks' robes since the production of silk involved the taking of life; however, eventually the use of silk was firmly established since it also was the easiest obtainable material.

*** POIRIER 1991
 - [[cite:POIRIER-1991][Poirier(1991), Histoire des moeurs]], p.1.961

*** JONES 2005
 - [[cite:JONES-2005][(2005), Encyclopedia of Religion]] (CLOTHING)
*** GIRARD 1769
 - [[cite:GIRARD-1769][Girard Beauzée(1769), SYNONYMES FRANÇOIS, LEURS DIFFÉRENTES SIGNIFICATIONS, ET LE CHOIX QU'IL EN FAUT FAIRE Pour parler avec justesse]], p.1.399.360
 (VETREMENT.HABILLEMENT.HABIT)
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 衲 nà (OC:nuub MC:nəp )
:PROPERTIES:
:CUSTOM_ID: uuid-89a64e61-144c-4233-84dd-2e4bdf608875
:Char+: 衲(145,4/10) 
:GY_IDS+: uuid-b33c22a7-8dfb-495f-b08c-43cdaa304e30
:PY+: nà     
:OC+: nuub     
:MC+: nəp     
:END: 
**** N [[tls:syn-func::#uuid-8717712d-14a4-4ae2-be7a-6e18e61d929b][n]] / BUDDH: (monks') robe (short for nàyī 納（衲）衣)
:PROPERTIES:
:CUSTOM_ID: uuid-bd091cab-2ec3-4f23-8406-91de210160b7
:END:
****** DEFINITION

BUDDH: (monks') robe (short for nàyī 納（衲）衣)

****** NOTES

*** 三衣 sānyī (OC:saam qɯl MC:sɑm ʔɨi )
:PROPERTIES:
:CUSTOM_ID: uuid-6fe125da-2073-45d1-9f2b-11ee727ffb3b
:Char+: 三(1,2/3) 衣(145,0/6) 
:GY_IDS+: uuid-3b81e026-2aee-45cd-b686-7bab8c7046b3 uuid-28e4431a-02b5-45a4-82d2-9f49e5f3b29e
:PY+: sān yī    
:OC+: saam qɯl    
:MC+: sɑm ʔɨi    
:END: 
**** SOURCE REFERENCES
***** FOGUANG
 - [[cite:FOGUANG][Cí 慈(unknown), 佛光大辭典 Fóguāng dàcídiǎn The Foguang Dictionary of Buddhism]], p.551a-c

***** KIESCHNICK 2003
 - [[cite:KIESCHNICK-2003][Kieschnick(2003), The Impact of Buddhim on Chinese Material Culture]], p.89ff

***** YANG WEIZHONG 2000
 - [[cite:YANG-WEIZHONG-2000][Yáng 楊 Lài 賴(2000), 中國佛教百科全書 Zhōngguó fójiào bǎikē quánshū Encyclopedic Book Collection on Chinese Buddhism]], p.236-238

**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] / BUDDH: the three monks' robes (typical for an Indian monk); skr. trīni cīvarāṇi; pali tīni cīvarāṇi...
:PROPERTIES:
:CUSTOM_ID: uuid-293d7298-39ea-40d5-8f4d-4735fd3b5249
:END:
****** DEFINITION

BUDDH: the three monks' robes (typical for an Indian monk); skr. trīni cīvarāṇi; pali tīni cīvarāṇi (already in Indian Buddhist texts the typical garment for monks was described of consisting of three items: a rectangular piece of cloth which was wrapped around the waist, covering the lower part of the body (this inner robe, skr. antarvāsa, āntuóhuì 安陀會) was always worn, also during periods of work; another piece of cloth was draped over the left shoulder (upper garment, skr. uttarāsaṇga, yùduōluósēng 鬱多羅僧), covering the upper part of the body; the third robe, the outer garment (skr. saṃgāṭi, sēngqiélí 僧伽梨) was usually worn when the monk was in the public, for examples on begging tours; although the basic design of this outfit is quite simple, there were many complex variations concerning these robes and the outer robe could be made several strips (tiáo 條) of cloth (usually 5, 7, 9, 13, 15, or even more; each stip consists of several patches, gé 隔); there were also careful descriptions how to sew a robe, using different  kinds of stiching technics; in China there were many controversies concerning the proper style of monks' robes; in the course of time the robe was highly charged with symbolism the the three robes sometimes represented different sets of Buddhist terms (e.g. the three poisons greed, anger, and ignorance and their respective elimination; another symbolic connection were the three realms 三界 or the three assemblis 三會). There is evidence that the original Indian style of robe was brought to China, but underwent changes in the course of time, and there was an adaption to Chinese customs, climate, etc. Gradually, there deveoped the sleeved robe, typical of East-Asian Buddhism, usually combined with trousers; at the end of the Tang - after having been criticised for long periods of time - this style of robe seems to have been firmly established; the outer robe - originally also a rectangular piece of cloth - became heavily charged with symbolism and were still made of a number a patches; however, although originally symbolizing the poverty of a monk, often the outer robe is China (and later Japan) was eventually made of especially fine and colorful materials, becoming a status symbol for high-ranking priests. In order to hold the robe in place, eventually a ring and ribbon (gouniu 鉤紐) was attached to it. In medieval China there was also an extended discussion about the use of silk for monks' robes since the production of silk involved the taking of life; however, eventually the use of silk was firmly established since it also was the easiest obtainable material)

****** NOTES

*** 九條 jiǔtiáo (OC:kuʔ ɡ-lɯɯw MC:kɨu deu )
:PROPERTIES:
:CUSTOM_ID: uuid-3a9fea74-ed18-4113-8e62-0e155aed2112
:Char+: 九(5,1/2) 條(75,7/11) 
:GY_IDS+: uuid-7724a604-307a-4b9a-af74-1dc72116d850 uuid-f9f1722d-0962-4503-91cd-900ba7250d07
:PY+: jiǔ tiáo    
:OC+: kuʔ ɡ-lɯɯw    
:MC+: kɨu deu    
:END: 
**** SOURCE REFERENCES
***** NAKAMURA
 - [[cite:NAKAMURA][Nakamura 望月(1975), 佛教語大辭典 Bukkyōgo daijiten Encyclopedic Dictionary of Buddhist Terms]], p.255c

**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: this refers to the nine pieces of cloth the traditional monk's rope (jiāshā 袈裟; skr. kaṣāya)...
:PROPERTIES:
:CUSTOM_ID: uuid-7b5bc982-c43c-406b-9909-d4c6f5426046
:END:
****** DEFINITION

BUDDH: this refers to the nine pieces of cloth the traditional monk's rope (jiāshā 袈裟; skr. kaṣāya)  is made of

****** NOTES

*** 納衣 nàyī (OC:nuub qɯl MC:nəp ʔɨi ) / 衲衣 nàyī (OC:nuub qɯl MC:nəp ʔɨi )
:PROPERTIES:
:CUSTOM_ID: uuid-2f7e8eca-a560-4e2b-9602-836e2a910849
:Char+: 納(120,4/10) 衣(145,0/6) 
:Char+: 衲(145,4/10) 衣(145,0/6) 
:GY_IDS+: uuid-b6458fb7-54cf-44b6-9cd7-ad4e5a465798 uuid-28e4431a-02b5-45a4-82d2-9f49e5f3b29e
:PY+: nà yī    
:OC+: nuub qɯl    
:MC+: nəp ʔɨi    
:GY_IDS+: uuid-b33c22a7-8dfb-495f-b08c-43cdaa304e30 uuid-28e4431a-02b5-45a4-82d2-9f49e5f3b29e
:PY+: nà yī    
:OC+: nuub qɯl    
:MC+: nəp ʔɨi    
:END: 
**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] / monk's robe
:PROPERTIES:
:CUSTOM_ID: uuid-c86c2701-8423-454d-bbb0-30c3be4c0d62
:END:
****** DEFINITION

monk's robe

****** NOTES

*** 紫衣 zǐyī (OC:tseʔ qɯl MC:tsiɛ ʔɨi )
:PROPERTIES:
:CUSTOM_ID: uuid-028a0780-4bd6-4005-b01c-20f5a00bcfdd
:Char+: 紫(120,5/11) 衣(145,0/6) 
:GY_IDS+: uuid-a8248e69-0ea4-4bec-9cb6-065e14bb3075 uuid-28e4431a-02b5-45a4-82d2-9f49e5f3b29e
:PY+: zǐ yī    
:OC+: tseʔ qɯl    
:MC+: tsiɛ ʔɨi    
:END: 
**** SOURCE REFERENCES
***** KIESCHNICK 2003
 - [[cite:KIESCHNICK-2003][Kieschnick(2003), The Impact of Buddhim on Chinese Material Culture]], p.100-107

**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: the purple robe (robe given to monks of distinction, a practice which began during the Tang)
:PROPERTIES:
:CUSTOM_ID: uuid-a7c8ff09-309b-47e3-aff7-4e41f3b7c51c
:END:
****** DEFINITION

BUDDH: the purple robe (robe given to monks of distinction, a practice which began during the Tang)

****** NOTES

*** 袈裟 jiāshā (OC:kraal sraal MC:kɣɛ ʂɣɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-35ba447c-0d06-4768-812c-c5b91d861834
:Char+: 袈(145,5/11) 裟(145,7/13) 
:GY_IDS+: uuid-a77b32ad-98dd-464d-b331-faad9e02745f uuid-a329fbb7-29d5-4924-906b-6566a9ee28b1
:PY+: jiā shā    
:OC+: kraal sraal    
:MC+: kɣɛ ʂɣɛ    
:END: 
**** SOURCE REFERENCES
***** KIESCHNICK 2003
 - [[cite:KIESCHNICK-2003][Kieschnick(2003), The Impact of Buddhim on Chinese Material Culture]], p.89f.


Chinese monks used to use monks' robes of different colors (often indicating different schools), ranging grey, brown, to black until ca. the tenth cent.; afterwards the color of the robes got gradually standardized; the monks' robe was a powerful symbol for the Buddhist clergy and becoming a monk was often described in terms of changing garment; there is an abundancy of writings concerning the outfit for monks throughout Buddhist history in China....

**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: monks' robe; skr. kaṣāya (Chinese monks used to use monks' robes of different colors (often ...
:PROPERTIES:
:CUSTOM_ID: uuid-6a99bfbc-ea7b-402e-a658-3673af632950
:END:
****** DEFINITION

BUDDH: monks' robe; skr. kaṣāya (Chinese monks used to use monks' robes of different colors (often indicating different schools), ranging grey, brown, to black until ca. the tenth cent.; afterwards the color of the robes got gradually standardized; the monks' robe was a powerful symbol for the Buddhist clergy and becoming a monk was often described in terms of changing garment; there is an abundancy of writings concerning the outfit for monks throughout Buddhist history in China)

****** NOTES

*** 僧伽梨 sēngqiélí (OC:sɯɯŋ ɡal ril MC:səŋ gʷɑ li )
:PROPERTIES:
:CUSTOM_ID: uuid-09c8f7b6-354b-4f34-a6a0-0e3e1fbfeb9b
:Char+: 僧(9,12/14) 伽(9,5/7) 梨(75,7/11) 
:GY_IDS+: uuid-aff96f35-56cd-4319-a52d-054402822438 uuid-64e8ea86-68bf-4570-8770-883ece9cec54 uuid-056e20ac-c045-4b50-8bc9-12b6d95ee412
:PY+: sēng qié lí   
:OC+: sɯɯŋ ɡal ril   
:MC+: səŋ gʷɑ li   
:END: 
**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: outer monks' robe (see 三衣) skr. saṃghati
:PROPERTIES:
:CUSTOM_ID: uuid-b49d2183-0365-4f8e-9779-e0c1d32b191f
:END:
****** DEFINITION

BUDDH: outer monks' robe (see 三衣) skr. saṃghati

****** NOTES

*** 安陀會 āntuóhuì (OC:qaan laal ɡloobs MC:ʔɑn dɑ ɦɑi )
:PROPERTIES:
:CUSTOM_ID: uuid-8af3592d-39ea-484a-aec2-41fe6d67b2a9
:Char+: 安(40,3/6) 陀(170,5/8) 會(73,9/13) 
:GY_IDS+: uuid-f8753075-adb6-43d4-bf48-caa024c8d9c4 uuid-8a3817af-ba46-4d61-9a19-ff72fd8a0a0b uuid-5cd2073a-6f30-434c-bf49-acee1f8e5bd7
:PY+: ān tuó huì   
:OC+: qaan laal ɡloobs   
:MC+: ʔɑn dɑ ɦɑi   
:END: 
**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: inner lower robe, typically worn by Indian monks (a rectangular piece of cloth wrapped aroun...
:PROPERTIES:
:CUSTOM_ID: uuid-120cc700-db9e-4c5e-a8d9-60dbe5a5684a
:END:
****** DEFINITION

BUDDH: inner lower robe, typically worn by Indian monks (a rectangular piece of cloth wrapped arouned the waist, worn at all occasions, also during work); skr. antarvāsa (see 三衣) (also referred to as nèiyī 內衣, wǔtiáoyī 五條衣, zhōngsùyī 中宿衣)

****** NOTES

*** 僧伽梨衣 sēngqiélíyī (OC:sɯɯŋ ɡal ril qɯl MC:səŋ gʷɑ li ʔɨi )
:PROPERTIES:
:CUSTOM_ID: uuid-63435bae-7f23-461c-9592-b4d2618aaa48
:Char+: 僧(9,12/14) 伽(9,5/7) 梨(75,7/11) 衣(145,0/6) 
:GY_IDS+: uuid-aff96f35-56cd-4319-a52d-054402822438 uuid-64e8ea86-68bf-4570-8770-883ece9cec54 uuid-056e20ac-c045-4b50-8bc9-12b6d95ee412 uuid-28e4431a-02b5-45a4-82d2-9f49e5f3b29e
:PY+: sēng qié lí yī  
:OC+: sɯɯŋ ɡal ril qɯl  
:MC+: səŋ gʷɑ li ʔɨi  
:END: 
**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: outer monks' robe (see 三衣) skr. saṃghati
:PROPERTIES:
:CUSTOM_ID: uuid-510c0936-1cc4-4a99-b843-09f5e63372cd
:END:
****** DEFINITION

BUDDH: outer monks' robe (see 三衣) skr. saṃghati

****** NOTES

*** 鬱多羅僧 yùduōluósēng (OC:qud k-laal b-raal sɯɯŋ MC:ʔi̯ut tɑ lɑ səŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-e4ca881f-cb25-4460-bd0c-48e77db70254
:Char+: 鬱(192,19/29) 多(36,3/6) 羅(122,14/19) 僧(9,12/14) 
:GY_IDS+: uuid-256bb7c0-7627-4400-9a50-928283d18389 uuid-a07df213-b938-43db-9782-7161ec468c87 uuid-73b6e4e2-147a-4ead-8d0b-386283e2a333 uuid-aff96f35-56cd-4319-a52d-054402822438
:PY+: yù duō luó sēng  
:OC+: qud k-laal b-raal sɯɯŋ  
:MC+: ʔi̯ut tɑ lɑ səŋ  
:END: 
**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: skr. antarvāsa, the inner upper robe of an Indian Buddhist monk (also referred to as shàngyī...
:PROPERTIES:
:CUSTOM_ID: uuid-beadc8ff-705f-4867-b41f-141fbe15f1d0
:END:
****** DEFINITION

BUDDH: skr. antarvāsa, the inner upper robe of an Indian Buddhist monk (also referred to as shàngyī 上衣, see 三衣)

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
