# -*- mode: mandoku-tls-view -*-
#+TITLE: DIALECT
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= DIALECT
:PROPERTIES:
:CUSTOM_ID: uuid-01da33ec-4653-4edc-8e72-059fe6e0e345
:TR_ZH: 方言
:END:
** DEFINITION



** NOTES

*** Old Chinese Contrasts
UlLRICH UNGER DRAFT: Daß das Chinesische schon im Altertum verschiedene Dialekte aufwies, ist sicher. Ganz vereinzelt finden sich in den Texten selbst Hinweise darauf. Meng tsï spricht von einem Ts'i- und einem Ch'u-Dialekt; das Tso-chuan nennt das Ch'u-Wort für "Tiger": 於菟 *uo-tuo. Völlig offen ist indes im Einzelfall die Frage, ob es sich bei den unterschiedlichen Idiomen bloß um Dialekte derselben Sprache, also des "Chinesischen", handele, oder nicht doch um Fremdsprachen. In Yüeh jedenfalls wurde eine nicht-chinesische Sprache gesprochen. Dolmetscher sind bezeugt. B. Karlgren hat anhand einzelner Formwörter einen Lu-Dialekt (also Shan-tung) und einen Tso-Dialekt (Sprache des Tso-chuan, nicht lokalisiert) unterschieden. Reiches Material zur Dialektologie der Han-Zeit bietet das Dialektwörterbuch Fang-yen, in welchem, locker nach Sachgebieten geordnet, Dialektausdrücke verschiedener Gegenden benannt werden. Zum Teil werden dazu auch die allgemein üblichen äquivalente gegeben. Es handelt sich hierbei allerdings nur eben um einzelne Wörter; weitergehende Unterschiede, etwa der Grammatik, sind nicht registriert. Auch die phonologischen Unterschiede der einzelnen Idiome verbergen sich hinter den Zeichen. Von diesen sind nicht wenige überhaupt nur hier, nicht in Texten, bezeugt - es handelt sich hierbei also vielleicht um Zeichen, die speziell für Dialekt-Wörter erfunden wurden.

** SOURCE REFERENCES
*** REY 2005
 - [[cite:REY-2005][Rey(2005), Dictionnaire culturel en langue francaise]], p.1.484

*** REY 2005
 - [[cite:REY-2005][Rey(2005), Dictionnaire culturel en langue francaise]], p.2.30

*** RITTER 1971-2007
 - [[cite:RITTER-1971-2007][Ritter Gruender Gabriel(1971-2007), Historisches Woerterbuch der Philosophie]], p.2.164

*** UNGER SACH
 - [[cite:UNGER-SACH][Unger(ca. 1990), "Sachwoerterbuch zum Alten China"]] (DIALEKTE)
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
