# -*- mode: mandoku-tls-view -*-
#+TITLE: DUEL
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= DUEL
:PROPERTIES:
:CUSTOM_ID: uuid-aa32d315-ab03-4deb-8563-1d3c5386e73d
:END:
** DEFINITION

RITUALISED FIGHT USING WEAPONS BETWEEN TWO HUMANS BECAUSE of the SHAME CAUSED BY ONE having OFFENED the OTHER, BECAUSE of HONOUR.

** NOTES

*** Old Chinese Contrasts
Schopenhauer, Nachlass vol. 3. p. 59: An die Stelle der mit Eintritt des Christenthums aufgehobenen Gladiatorspiele ist in der Chrstlichen Zeit und christlichen Ländern das Duell getreten. Jene ein grausames Opfer der allgemeinen Belustigung gebracht; dieses ein grausames opfer dem allgemeinen Vorurtheil gebracht. Jene von Sklaven und Fefangenen; dieses von Freuen und Edlen.

** SOURCE REFERENCES
*** GUILLET 2008
 - [[cite:GUILLET-2008][Guillet(2008), 1980: Le Je-ne-sais-quoi et le presque rien]]
*** JEANNENEY 2004
 - [[cite:JEANNENEY-2004][Jeanneney(2004), Le Duel]]
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
