# -*- mode: mandoku-tls-view -*-
#+TITLE: ENGAGEMENT
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= ENGAGEMENT
:PROPERTIES:
:CUSTOM_ID: uuid-e76d9723-048b-4343-b417-b589c93c9841
:TR_ZH: 關心
:END:
** DEFINITION

THINK DILIGENTLY ABOUT THINGS DESIRING INTENSELY TO IMPROVE THEM. [read like French engagement]

** NOTES

*** Old Chinese Criteria
The history of engagement in Chinese literature is a promising topic for discussion. As is the question of public space. It is not clear to me what the word would be for "engagement".

*** Modern Chinese Criteria
???

** SOURCE REFERENCES
*** DENIS 2000
 - [[cite:DENIS-2000][Denis(2000), Litterature et engagement]]

This is an important dimension under which to view literature.  One wonders what the classical Chinese word for this kind of political engagement would be.

*** BARCK 2010
 - [[cite:BARCK-2010][Barck(2010), Ästhetische Grundbegriffe]], p.2.178

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
