# -*- mode: mandoku-tls-view -*-
#+TITLE: FINAL PARTICLES
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= FINAL PARTICLES
:PROPERTIES:
:CUSTOM_ID: uuid-069ae7d2-0c4f-45a4-99e0-012ab9c92fcf
:TR_ZH: 句後虛詞
:END:
** DEFINITION

PARTICLE USED at the END of a SENTENCE. [NOTE THAT THE GRAMMATICAL PARTICLES HAVE NOT BEEN FOCUSSED SO FAR IN THE SYSTEM AND NO SYSTEMATIC ANALYSIS HAS BEEN APPLIED SO FAR.]

** NOTES

*** Modern Chinese Criteria
LU JIANMING

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 乎 hū (OC:ɢaa MC:ɦuo̝ )
:PROPERTIES:
:CUSTOM_ID: uuid-c60e41f1-d4e9-450d-a133-28d3ad1abf79
:Char+: 乎(4,4/5) 
:GY_IDS+: uuid-02ab4456-9185-460d-8a7f-8d4ac2085a5c
:PY+: hū     
:OC+: ɢaa     
:MC+: ɦuo̝     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-d82256cd-a1c1-4a58-b15f-615a92237386][question]]} / final question particle after verbal sentence 管仲儉乎？"Was Guǎnzhòng stingy?"
:PROPERTIES:
:CUSTOM_ID: uuid-1f5c75ca-eb8e-4891-8afa-a200ad5accb0
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

final question particle after verbal sentence 管仲儉乎？"Was Guǎnzhòng stingy?"

****** NOTES

******* Examples
LY 01.04; tr. CH

 為人謀而不忠乎？ When counselling others in planning have I failed to do my loyal best[CA]

*** 云 yún (OC:ɢun MC:ɦi̯un )
:PROPERTIES:
:CUSTOM_ID: uuid-c50f0683-6469-4877-8095-0d926befdf1d
:Char+: 云(7,2/4) 
:GY_IDS+: uuid-32021026-3e9b-46d7-967b-a3563b36310b
:PY+: yún     
:OC+: ɢun     
:MC+: ɦi̯un     
:END: 
**** SOURCE REFERENCES
***** WANG FENGYANG 1993
 - [[cite:WANG-FENGYANG-1993][Wang 王(1993), 古辭辨 Gu ci bian]], p.476

***** WANG FENGYANG 1993
 - [[cite:WANG-FENGYANG-1993][Wang 王(1993), 古辭辨 Gu ci bian]], p.476

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] / marker of end of quotation
:PROPERTIES:
:CUSTOM_ID: uuid-e2fa4e61-dc50-44f2-8216-c78fdf58bc75
:END:
****** DEFINITION

marker of end of quotation

****** NOTES

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-28210b5a-450e-4014-b362-39e05decea1c][euphonic]]} / euphonic colloquial particle at the end of phrases 禮云禮云 "It is all a matter of ritual..."
:PROPERTIES:
:CUSTOM_ID: uuid-785f3b18-8bd2-4924-ab22-3eef816b7487
:END:
****** DEFINITION

euphonic colloquial particle at the end of phrases 禮云禮云 "It is all a matter of ritual..."

****** NOTES

*** 些 xiē (OC:slal MC:sɣɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-d724fb55-ea20-4b9b-8f16-90c9e62bbb61
:Char+: 些(7,5/7) 
:GY_IDS+: uuid-5997063a-a403-47bd-8b38-ec843b738890
:PY+: xiē     
:OC+: slal     
:MC+: sɣɛ     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] / in CC.  Meaning?
:PROPERTIES:
:CUSTOM_ID: uuid-d7e903ab-82f2-4bb3-b90d-0041808f80c9
:END:
****** DEFINITION

in CC.  Meaning?

****** NOTES

*** 來 lái (OC:m-rɯɯ MC:ləi )
:PROPERTIES:
:CUSTOM_ID: uuid-49e6aba2-826b-4233-bcee-5106589eef91
:Char+: 來(9,6/8) 
:GY_IDS+: uuid-9ef8de95-a9bb-45e9-a9eb-4ba693fb26c6
:PY+: lái     
:OC+: m-rɯɯ     
:MC+: ləi     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004B
 - [[cite:ANDERL-2004B][Anderl(2004), Studies in the Language of Zǔtáng jí 祖堂集]], p.517-518


In this function la2i indicates that any action should be carried out for the sake of the speaker and it expresses the direct request to the addressee to carry out this action. It is actually often an action which could be carried out by the speaker himself but which is delegated to the addressee. Consequently la2i is usually used in dialogues by the person of higher rank. The person the action is carried out for, is sometimes marked by a coverb (usually by coverb yu3 與 which regularly appears in sentences expressing a request).1395 This usage is closely connected to the one discussed above: 'to come > to come for the purpose of VERBING > request to VERB for the speaker'. In this function I regard la2i as grammaticalized into a sentence final since the original meaning has faded away and it affects the whole proposition (changing it from a statement to a request).



In the following two examples the benefactor of the action is marked by yu3 與 (COV):

1251) ZTJ 1.116; WU: 72

“與老僧過淨瓶水來。”

yu3 la3o-se1ng guo4 ji4ng pi2ng shui3 la2i

COV.INDIR/NPRO1SG.SEMIold-monk/pass(hand over)/pure/CLASSbottle/water/SF.IMP(REQUEST)

"Hand me over a jar with fresh water."



1252) ZTJ 1.173; WU: 105

“汝與我擎缽盂來。”

ru3 yu3 wo3 qi2ng bo1-yu2 la2i

NPRO2SG/COV.BENEFACT/NPRO1SG/lift/alms bowl-jar/SF.IMP(REQUEST)

"Get the alms bowl for me."1396



Note that la2i is restricted in its function to indicate a direct request (imperative). The contents of the request must indicate something which is performed for the sake of the speaker. As such the original meaning of la2i is still present to a certain extent.



Note that la2i also has this function when it appears as part of the complex verbal complement jia1ng-la2i 將來 (V.COMP). In this construction jia1ng indicates the immanent future and la2i indicates that the action is directed towares the speaker and by extension a request:

1253) ZTJ 4.060; WU: 319

“併卻咽喉唇吻，"Closing your throught and your lips, 

速道將來。”quickly speak up!"

**** V [[tls:syn-func::#uuid-c2c4bfc7-4e20-47c6-b583-2a4c5638d23b][vpostadS]] {[[tls:sem-feat::#uuid-2712e600-399e-41e1-8a65-af983a80bcff][past]]} / deverbal sentence final particle indicating a past event (indicating temporal distance to the speec...
:PROPERTIES:
:CUSTOM_ID: uuid-5ab4b9b6-44e4-4d6b-865f-40d6b29547f3
:END:
****** DEFINITION

deverbal sentence final particle indicating a past event (indicating temporal distance to the speech act, and typically action with a subjective purpose)

****** NOTES

**** V [[tls:syn-func::#uuid-c2c4bfc7-4e20-47c6-b583-2a4c5638d23b][vpostadS]] {[[tls:sem-feat::#uuid-e92d19a7-9dd9-40f7-9e71-5075ae5c0b4d][request]]} / come > come for the purpose of > do for the speaker > sentence final expressing a request (to do so...
:PROPERTIES:
:CUSTOM_ID: uuid-175456bc-2c95-41b2-bb94-cdf577ea6e9e
:END:
****** DEFINITION

come > come for the purpose of > do for the speaker > sentence final expressing a request (to do something for the sake of the speaker); sometimes more neutrally expressing mild obligation or a suggestion

****** NOTES

*** 去 qù (OC:khas MC:khi̯ɤ )
:PROPERTIES:
:CUSTOM_ID: uuid-769361e0-cfc7-4804-a0a0-85948bfe1693
:Char+: 去(28,3/5) 
:GY_IDS+: uuid-827fc8a5-b76b-4a8f-b089-157ba660ab3f
:PY+: qù     
:OC+: khas     
:MC+: khi̯ɤ     
:END: 
**** V [[tls:syn-func::#uuid-c2c4bfc7-4e20-47c6-b583-2a4c5638d23b][vpostadS]] {[[tls:sem-feat::#uuid-96e19999-b4f5-4323-96c1-8371e72b18fd][future]]} / leave from the speaker > temporally distant from the speaker > sentence final marking an event in t...
:PROPERTIES:
:CUSTOM_ID: uuid-a29b7ca5-5a6f-4955-b358-0520972b6159
:END:
****** DEFINITION

leave from the speaker > temporally distant from the speaker > sentence final marking an event in the future (marking that the act/state indicated by S has not taken occurred yet; sometimes qù also seems to mark an intention)

****** NOTES

**** V [[tls:syn-func::#uuid-c2c4bfc7-4e20-47c6-b583-2a4c5638d23b][vpostadS]] {[[tls:sem-feat::#uuid-b8276c57-c108-44c8-8c01-ad92679a9163][imperative]]} / go and V > go ahead and V (grammaticalized deverbal sentence final particle expressing a very mild ...
:PROPERTIES:
:CUSTOM_ID: uuid-208658e4-d69a-4bb4-87b5-34297006b322
:END:
****** DEFINITION

go and V > go ahead and V (grammaticalized deverbal sentence final particle expressing a very mild imperative, an invitation to do something)

****** NOTES

**** V [[tls:syn-func::#uuid-8ea309af-0157-4198-9940-927815f1972d][vpostadS1.post-S2]] {[[tls:sem-feat::#uuid-07753e6c-9183-4ff1-9668-399a8bc40c14][apodosis]]} / go and V > sentence final marking the apodosis in hypothetical conditions (if S2 then S1)
:PROPERTIES:
:CUSTOM_ID: uuid-1553c978-7dcf-4850-9016-09884e8a0fa9
:END:
****** DEFINITION

go and V > sentence final marking the apodosis in hypothetical conditions (if S2 then S1)

****** NOTES

*** 在 zài (OC:sɡɯɯʔ MC:dzəi )
:PROPERTIES:
:CUSTOM_ID: uuid-aa510721-1a63-4ad2-aee5-29f8a6567ccb
:Char+: 在(32,3/6) 
:GY_IDS+: uuid-68383a76-4bb0-42bd-abf4-1567b3ccf244
:PY+: zài     
:OC+: sɡɯɯʔ     
:MC+: dzəi     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004B
 - [[cite:ANDERL-2004B][Anderl(2004), Studies in the Language of Zǔtáng jí 祖堂集]], p.512-515, 537-539


According to Sun Xixin 1999: 87-92 sentence final za4i 在 (SF)  is commonly used in the vernacular texts of the late Tang and Song periods. He thinks that it often expresses the speaker's conviction that an event will take place in the future. Simultanously it seems to give emphasis to the speaker's statement. Za4i appeared in this function during the Tang and early examples can also be found in Tang poetry. During The Five Dynasties and Song periods the sentence final became more common in vernacular texts like the Recorded Sayings of the Cha2n school and Neo-Confucianists. During the Yuan period it gradually decreased in frequency and had completely become obsolete by Ming times.



The original meaning of za4i 在 (VT) is 'to exist' and in this meaning it also regularly appeared at the end of a sentence. This probably was one of the preconditions for the development into a sentence final particle. During the Tang za4i at the end of the sentence began to be emptied of its original meaning and began to function as sentence final. It was suggested that in some examples it seems to function comparable to Modern Mandarin ne 呢 and li 哩.





2.3.2.3.5.2 PATTERNS WITH SENTENCE FINAL za4i 在



Typical pattern of sentences with za4i in ZTJ and the Recorded Sayings and are:



Pattern (a) yo3u 有 + NP(X) + za4i 在 'a certain NP(X) exists'



1233) ZTJ 1.102; WU: 62

“更有庵在。”"There is another cottage (small hermitage) there."



In this pattern zai4 still has its original meaning 'to exist'.



Pattern (b) we4i 未 + VP + za4i 在 (SF)



Za4i often appears in the pattern we4i 未 + VP + za4i 在. We4i 未 (NEG) originally means 'not yet' but in most examples it seems more appropriate to translate it with 'not', syn. to bu4 不. In sentences with adverbs of negation za4i seems to emphasize the fact that an action which should have been performed or was expected to be performed has actually not been performed after all.

1234) ZTJ 5.044; WU: 395

“去ㄐ未見老僧在ㄐ”

qu4 we4i jia4n la3o-se1ng za4i

leave/NEGnot yet/see>understand/NPRO1SG.SEMIold-monk/SF.EMPHASIS

"Leave! You have not understood me (yet)!"



1235) ZTJ 2.048; WU: 137

“這個人未出家在。”

zhe4-ge4 re2n we4i chu1-jia1 za4i

NPRO.DEMthis-CLASS/person/NEGnot yet/leave-family/SF.EMPHASIS

"This person has not yet left home (yet) (i.e. is not a real monk)!"



1236) ZTJ 4.114; WU: 354

師云：The master said:

“某甲未喫茶在。”"I have not drunk tea yet."



1237) ZTJ 2.120; WU: 174

“雖則如此，有人未許專甲在。”

sui1-ze2 ru2 ci3 yo3u re2n we4i xu3 zhua1n-jia3 za4i 

SI.CONSalthough/be like/NPRO/exist/person/NEG/allow/NPRO1SF/SF.EMPHASIS

"Although it is like this, there is a person who does not allow [it] to me."



Pattern (c) VP + za4i 在 (SF)



In the following examples za4i gives emphasis to the statement, za4i 在 (SF.EMPHASIS):

1238) ZTJ 1.111,09; WU: 70

“猶持瓦礫在。” 

yo2u chi2 wa3-li4 za4i

be like/hold/tile-gravel/SF.EMPHASIS

"This is like holding rubble."



1239) ZTJ 5.138,05; WU: 450

“向後有多口阿師與你點破在。” 

xia4ng-ho4u yo3u duo1-ko3u a1-shi1 yu3 ni3 dia3n-po4 za4i

afterwards/exist/many-word>garrulous/PREF-master/COV.OBJ.INDIR/expose-break/SF.EMPHASIS?

"Afterwards there will be a garrulous monk who will expose you."



Pattern (d) Constructions with multiple sentence finals: za4i often co-appears with sentence final qu4 去 and za4i is always postposed to qu4.



1240) ZTJ 5.138,05; WU: 450

“長老與摩識弁人，"You elder are such an eloquent person, 

瞎卻鎮州城裡人眼去在。”you are going to blind the eyes of the people of Zhe1nzho1u city."



1241) ZTJ 2.092; WU: 160 

“每日在長連床上，"Everyday [sitting] on the long meditation platform

恰似漆村里土地相似！it just resembles adding earth in the village!

他時後日，on day in the future

魔魅人家男女去在！”you will deceive (bewitch) the men and women of the families!"



1242) ZTJ 5.052; WU: 400

“但得其本，"Just [try to] attain the origin [of the mind]

不愁其末。not worrying about its perphery (lit. branches).

他時後日，[Then] one day in the future

自具足去在。”by itself it will suffice."



In this pattern sentence final qu4 去 marks that the event is going to take place in the future and za4i 在 gives emphasis to the statement. Combined the two sentence finals mark the speaker's conviction that an event/action certainly will take place in the future.



As mentioned above the original meaning of za4i is to 'to exist' and it was often used in patterns with localizers (N.GR.LOC):

za4i 在 + NP + zho1ng 中 (N.GR.LOC)

za4i 在 + NP + sha4ng 上 (N.GR.LOC)

za4i 在 + NP + li3 P (N.GR.LOC)



1243) ZTJ 3.095; WU: 250

“老僧在你肚P。” 

la3o-se1ng za4i ni3 du4 li3

NPRO1SG.SEMIold-monk/be in(exist in)/NPRO2SG/stomack/N.GR.LOCinside

"I am in your stomach (belly)."



In phrases with za4i...li3 the NP was frequently deleted and the phrase was contracted to za4i li3 在裡, used at the end of the sentence.

1244) ZTJ 2.040; WU: 133

“若与摩和尚來時，"If that's the case then, when the Preceptor comes,

莫向他說納僧在裡。”don't tell him that there is a monk here."



li3 裡 also appears in the form li3-xu3 裡許:1386

1245) ZTJ 3.111; WU: 262

師云：“曹山在裡許。”

shi1 yu2n Ca2osha1n za4i li3-xu3

master/say/NPR/be at/N.GR.LOC-SUFF

The master said: "Ca2osha1n is inside."



In ZTJ 在裡 is still used in its original meaning, expressing the location of a  certain object but during Song times this construction was emptied of its original meaning. Originally a NP had to be placed inbetween za4i and li3 but from Song times onwards also a VP could be inserted between the two elements. Thus the construction did not express any longer a location but began to function as sentence final construction giving emphasis to an utterance (SUN XIXIN 1999: 91).

Also the construction with deleted object, za4i li3 在裡 underwent a similar change and it was emptied of its original meaning. There seems to have occurred a shift from marking a concrete location to an abstract location (such as a proposition/speech act).

One reason for this development possibly is the following: During the Tang and Five Dynasties periods both za4i and li3 were already used as sentence finals independently and in the course of time za4i li3 began to be interpreted as sentence finals in a sequence.

Interestingly, also the construction za4i zhe4-li3 在這裡 underwent a similar development. In Song texts it usually still has its literaty meaning 'be here' (WUDENG) but in some sentences it already seems to have the function of giving emphasis to a statement (e.g. in ZHUZI). During the Yuan and Ming periods it clearly could function as sentence final affirming a statement (SUN XIXIN 1999: 92 and YU GUANGZHONG 1986 who analyzes the construction in SHUIHUZHUAN).



The frequency of sentence final za4i it ZTJ is quite high (F: > 50) and as such it is one of the most frequently used vernacular sentence finals in ZTJ. Many of the examples of za4i appear in a derogatory context, and the phrases it appears in often express a notion of despise. As a consequence, in dialogues it is usually used by the person relatively higher in rank (i.e. the master).



An analysis of za4i in ZTJ shows that it does not function to indicate an event in the future or the speaker's conviction that an event/action will take place in the future. This function seems rather to be indicated by qu4 去 which often appears together with za4i. The primary function of za4i is the adding of emphasis of a statetment, and the function probably derived from its original meaning 'exist > that's how it is'; in its original meaning it indicates a concrete location whereas as sentence final it marks and gives emphasis to an abstract location, such as the proposition of the speech act.

**** V [[tls:syn-func::#uuid-c2c4bfc7-4e20-47c6-b583-2a4c5638d23b][vpostadS]] {[[tls:sem-feat::#uuid-5ae85a4e-5823-417b-b04f-58d7d9f263f5][emphatic]]} / exist > that's how it is > sentence final particle giving emphasis to a statement (frequently used ...
:PROPERTIES:
:CUSTOM_ID: uuid-9e3fec7b-f4bc-4645-bd35-e87b8a7f5d92
:END:
****** DEFINITION

exist > that's how it is > sentence final particle giving emphasis to a statement (frequently used in vernacular texts of the late Tang and Song periods)

****** NOTES

**** V [[tls:syn-func::#uuid-c2c4bfc7-4e20-47c6-b583-2a4c5638d23b][vpostadS]] {[[tls:sem-feat::#uuid-5ae85a4e-5823-417b-b04f-58d7d9f263f5][emphatic]]} / exist > that's how it is > sentence final particle giving emphasis to a statement (frequently used ...
:PROPERTIES:
:CUSTOM_ID: uuid-d0d7df23-3b3e-47c4-847c-e40e4391f177
:END:
****** DEFINITION

exist > that's how it is > sentence final particle giving emphasis to a statement (frequently used in vernacular texts of the late Tang and Song periods); in the pattern with negated VP (the negator is usually 未) the emphasis is on the fact that an action should have been performed or was expected to be performed, but was in fact not

****** NOTES

*** 婆 pó (OC:baal MC:bʷɑ )
:PROPERTIES:
:CUSTOM_ID: uuid-56d0b8e8-fad8-4439-a019-680ccb39c0a8
:Char+: 婆(38,8/11) 
:GY_IDS+: uuid-f3fd05c7-81ff-4e2d-b8b2-b7eee24b8fe0
:PY+: pó     
:OC+: baal     
:MC+: bʷɑ     
:END: 
**** SOURCE REFERENCES
***** FENG CHUNTIAN 2000
 - [[cite:FENG-CHUNTIAN-2000][Féng 馮(2000), 近代漢語語法研究 Jìndài hànyǔ yǔfǎ yánjiū]], p.524-526

***** KARASHIMA 1997
 - [[cite:KARASHIMA-1997][Karshima 辛(), 漢譯佛典的語言研究 Hànyì Fódiǎn de yǔyán yánjiū [Studies in the Language of Buddhist Texts from the Han Period] 俗語言研究 Suyuyan yanjiu]], p.45-47

***** LONG GUOFU 2004
 - [[cite:LONG-GUOFU-2004][Lóng 龍 Jiǎng 蔣(2004), 姚秦譯經助詞研究 Yáo Qín yìjīng zhùcí yánjiū Studies in Function Words in the Translated Buddhist Scriptures of the Yáo Qín Period Wei Jin NanBeichao Hanyi fojing yuyan yanjiu congshu]], p.259-263


Long counts 12 examples of sentence final 婆 in the BINAIYE, clearly indicating a question. In affirmative sentences > demanding the answer yes or no (similar to the later 摩); it also appears in sentences with negated main verbs and in these cases it seems to corrspond to 耶 or 乎. in the BINAIYE 不 and 婆 are used parallel and in a similar way., therefore it is by some regarded as 音變形式 (form representing a sound change) of 不. However, Long doubts this interpretation and also points out the two examples in ZTJ where po2 is rather used similiar to Modern Chinese 吧 (Iriya interpretes it like this). Long interpretes it as representation of a final particle in a local dialect.

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-d82256cd-a1c1-4a58-b15f-615a92237386][question]]} / This is a rare EMC interrogative sentence final particle (discovered by Seishi  Karshima) used in t...
:PROPERTIES:
:CUSTOM_ID: uuid-f544b6d7-27fb-418d-afac-62149ea6218f
:END:
****** DEFINITION

This is a rare EMC interrogative sentence final particle (discovered by Seishi  Karshima) used in the 鼻奈耶 tr. by Zhú Fóniàn 竺佛念 (used similarly to the later 摩) (examples see in SOURCES)

****** NOTES

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-ff53e5da-89f7-4601-ae05-d2119e933dfa][rhetorical question]]} / this is an extremely rare sentence final particle (discovered by Seishi Karashima in the BINAIYE), ...
:PROPERTIES:
:CUSTOM_ID: uuid-16a5515a-2a56-449f-9d23-2bf74adc5cdf
:END:
****** DEFINITION

this is an extremely rare sentence final particle (discovered by Seishi Karashima in the BINAIYE), in ZTJ it appears two times and is used quite differently from the examples in BINAIYE, in ZTJ it rather seems to function like Modern Mandarin final 吧

****** NOTES

*** 已 yǐ (OC:k-lɯʔ MC:jɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-c5a6ade3-ad44-4d13-b569-b222c345e30e
:Char+: 已(49,0/3) 
:GY_IDS+: uuid-e799b325-78d4-4326-a46d-ca3498ecce7a
:PY+: yǐ     
:OC+: k-lɯʔ     
:MC+: jɨ     
:END: 
*** 摩 mó (OC:maal MC:mʷɑ )
:PROPERTIES:
:CUSTOM_ID: uuid-dcf84913-0918-42b6-b7b7-12564f5148b8
:Char+: 摩(64,11/14) 
:GY_IDS+: uuid-62efd968-fcbb-4774-9c42-a22187c35c91
:PY+: mó     
:OC+: maal     
:MC+: mʷɑ     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-2d131ece-0e8e-4fd3-8839-9395b7aa4b14][colloquial]]} / vernacular interrogative sentence final particle, indicating a yes/no question (precursor of Modern...
:PROPERTIES:
:CUSTOM_ID: uuid-b5fd3fd3-001b-4ebe-82e9-0d3b034abd04
:END:
****** DEFINITION

vernacular interrogative sentence final particle, indicating a yes/no question (precursor of Modern Chinese 嗎)

****** NOTES

*** 焉 yān (OC:qran MC:ʔiɛn )
:PROPERTIES:
:CUSTOM_ID: uuid-6db77d38-5b17-4006-a94f-d7687e80719d
:Char+: 焉(86,7/11) 
:GY_IDS+: uuid-5e796aa6-3208-44c6-bb32-f95a2c00c89a
:PY+: yān     
:OC+: qran     
:MC+: ʔiɛn     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-ef863d81-5e5e-4d13-9533-e7b878cc3edc][result]]} / from it> as a result
:PROPERTIES:
:CUSTOM_ID: uuid-cab82859-7455-4e19-b105-ad38459b1a4c
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

from it> as a result

****** NOTES

**** V [[tls:syn-func::#uuid-3427424e-b45e-41c1-a64d-21b6508958ae][vi{vt+npro}.postadV]] / contraction for 於之: in it; from it; to it; than it; by it
:PROPERTIES:
:CUSTOM_ID: uuid-1ef8d9bc-c7a7-4c3a-893c-0d072d3766ff
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

contraction for 於之: in it; from it; to it; than it; by it

****** NOTES

****  [[tls:syn-func::#uuid-823d872a-7d32-4690-bcbb-dd5a72cd326e][p{vtonpro}postV]] / like 於之: in it, from it, to him etc.
:PROPERTIES:
:CUSTOM_ID: uuid-4a4e6166-b3ff-49c7-a960-2c6ce43369d2
:WARRING-STATES-CURRENCY: 3
:END:
****** DEFINITION

like 於之: in it, from it, to him etc.

****** NOTES

*** 爾 ěr (OC:mljelʔ MC:ȵiɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-2658efd6-16e8-4cd6-a652-54f1ef611450
:Char+: 爾(89,10/14) 
:GY_IDS+: uuid-9bbb9d85-e760-4462-bd4e-779a8bb1b5da
:PY+: ěr     
:OC+: mljelʔ     
:MC+: ȵiɛ     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] / =而已
:PROPERTIES:
:CUSTOM_ID: uuid-27795628-6aec-416d-9a1f-50e06a9db1f6
:END:
****** DEFINITION

=而已

****** NOTES

*** 矣 yǐ (OC:ɢɯʔ MC:ɦɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-ed7efa45-066c-4077-ba0d-fbc947aa2cb6
:Char+: 矣(111,2/7) 
:GY_IDS+: uuid-644760a0-b567-4543-90dd-32afbfa9849c
:PY+: yǐ     
:OC+: ɢɯʔ     
:MC+: ɦɨ     
:END: 
**** P [[tls:syn-func::#uuid-0ad45b80-da12-4e04-86f2-9a43fa9955dd][ppostadN{PRED}]] / modal particle marking new/current situation (like 了)
:PROPERTIES:
:CUSTOM_ID: uuid-11bccab6-f751-4d8d-9757-897f06ac5937
:END:
****** DEFINITION

modal particle marking new/current situation (like 了)

****** NOTES

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-dcdf1d0d-3149-4d15-9abe-7cfe96419413][logic]]} / exclamatory/emphatic: definitely
:PROPERTIES:
:CUSTOM_ID: uuid-b8e5e20d-cd5b-4676-addb-2cde1fe17446
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

exclamatory/emphatic: definitely

****** NOTES

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-ae253be7-73ea-4c00-b429-1b5fc1b45b17][tensed]]} / currently relevant verbal statement;   new situationtensed
:PROPERTIES:
:CUSTOM_ID: uuid-28dc093c-55bd-41c5-ba11-968d07a616c5
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

currently relevant verbal statement;   new situationtensed

****** NOTES

**** P [[tls:syn-func::#uuid-acfafcb7-9609-4e1a-8afb-f4be1c254f0a][ppostadS1.adS2]] / final particle after a conditional clause!
:PROPERTIES:
:CUSTOM_ID: uuid-7f4a4eb2-0361-443d-bd41-c9946fe7beda
:WARRING-STATES-CURRENCY: 2
:END:
****** DEFINITION

final particle after a conditional clause!

****** NOTES

*** 者 zhě (OC:kljaʔ MC:tɕɣɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-ee0cf7bf-38cf-41e1-b4af-307bae7e7834
:Char+: 者(125,4/10) 
:GY_IDS+: uuid-638f5102-6260-4085-891d-9864102bc27c
:PY+: zhě     
:OC+: kljaʔ     
:MC+: tɕɣɛ     
:END: 
**** SOURCE REFERENCES
***** HU ZHU'AN 1958
 - [[cite:HU-ZHU'AN-1958][Hú 胡(), 宋元白話作品中語氣助詞 Sòng Yuán báihuà zhōng yǔqì zhùcí [Modal Auxiliaries in the Vernacular Literature of the Sòng and Yuán Periods] 中國語文 Zhongguo yuwen]]
***** LV SHUXIANG 1984
 - [[cite:LV-SHUXIANG-1984][Lv3 呂(1984), 漢語語法論文集 Hànyǔ yǔfǎ lùnwénjí A Collection of Articles on Chinese Grammar]], p.70

***** SUN XIXIN 1997
 - [[cite:SUN-XIXIN-1997][Sūn 孫(1997), 漢語歷史語法叢稿 Hànyǔ lìshǐ yǔfǎ cónggǎo An Outline of an Historical Grammar of Chinese]], p.72

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-b8276c57-c108-44c8-8c01-ad92679a9163][imperative]]} / vernacular sentence final particle expressing an imperative/prohibition (this function appeared dur...
:PROPERTIES:
:CUSTOM_ID: uuid-c5071353-00d4-49f2-ba16-266fa8183ab5
:END:
****** DEFINITION

vernacular sentence final particle expressing an imperative/prohibition (this function appeared during the Tang, the particle is still used in this function in certain dialects, such as the Wǔhàn 武漢  dialect; zhe was commonly used during the Song period but during the Yuan it got gradually replaced by zá 咱 and zégè 則個; see also 著)

****** NOTES

*** 耳 ěr (OC:mljɯʔ MC:ȵɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-6431f5cc-f3e5-4037-b701-e10ed8fe1dcd
:Char+: 耳(128,0/6) 
:GY_IDS+: uuid-7c88fece-5607-45d0-8d33-133b97cc251d
:PY+: ěr     
:OC+: mljɯʔ     
:MC+: ȵɨ     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-5ae85a4e-5823-417b-b04f-58d7d9f263f5][emphatic]]} / emphatic sentence final particle: and that's how it is, and there is nothing to add to this matter,...
:PROPERTIES:
:CUSTOM_ID: uuid-49f3ec5c-b76d-4f5b-a6ba-ed9a7488a72e
:END:
****** DEFINITION

emphatic sentence final particle: and that's how it is, and there is nothing to add to this matter, and that's all to it

****** NOTES

*** 耶 yé (OC:la MC:jɣɛ ) / 邪 yé (OC:k-la MC:jɣɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-be3ddd71-d955-4d5c-ab00-0742a167cbea
:Char+: 耶(128,3/9) 
:Char+: 邪(163,4/7) 
:GY_IDS+: uuid-724ba4a2-8b6e-4d50-97be-800a29d2944d
:PY+: yé     
:OC+: la     
:MC+: jɣɛ     
:GY_IDS+: uuid-cf26f85b-5790-48dc-93fd-fdd13dc565f8
:PY+: yé     
:OC+: k-la     
:MC+: jɣɛ     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-3956b329-85df-4d4d-b1be-e6bd70198afe][alternative]]} / question particle, marking disjunctive question
:PROPERTIES:
:CUSTOM_ID: uuid-3d05bcbe-6c55-4fc3-bdbf-18fbf9e2436c
:END:
****** DEFINITION

question particle, marking disjunctive question

****** NOTES

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] / question particle
:PROPERTIES:
:CUSTOM_ID: uuid-47ec3a50-d29e-419e-a1d2-de85e3174794
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

question particle

****** NOTES

******* Nuance
This is propably a contraction of yě hū 也乎 and often used in rhetorical questions. Sometimes also yú 與 / 歟 is used in this way.

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-ff53e5da-89f7-4601-ae05-d2119e933dfa][rhetorical question]]} / ?. Surely not
:PROPERTIES:
:CUSTOM_ID: uuid-eb35babd-5524-4fbc-8028-daf86cac79d3
:END:
****** DEFINITION

?. Surely not

****** NOTES

*** 著 zhuó (OC:k-laɡ MC:ʈi̯ɐk )
:PROPERTIES:
:CUSTOM_ID: uuid-80814ba7-0fc7-4c5a-b36c-6e1e3be92044
:Char+: 著(140,8/14) 
:GY_IDS+: uuid-257cc1ea-48fa-40f5-bcac-2e75328d6894
:PY+: zhuó     
:OC+: k-laɡ     
:MC+: ʈi̯ɐk     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004C
 - [[cite:ANDERL-2004C][Anderl(2004), Studies in the Language of Zu-tang Ji 祖堂集]]
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] / colloquial sentence final particle giving emphasis to a judgemental conclusion/apodosis (it seems t...
:PROPERTIES:
:CUSTOM_ID: uuid-cb17830b-5acc-4f5a-9be0-ba9470f72ff6
:END:
****** DEFINITION

colloquial sentence final particle giving emphasis to a judgemental conclusion/apodosis (it seems to used in the way of sentence final 去 or 在 here)

****** NOTES

**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-2d131ece-0e8e-4fd3-8839-9395b7aa4b14][colloquial]]} / colloquial sentence final particle: usually expressing a straightforward imperative; however, occas...
:PROPERTIES:
:CUSTOM_ID: uuid-e7427ad5-db71-433c-8f74-5e21bcb922fa
:END:
****** DEFINITION

colloquial sentence final particle: usually expressing a straightforward imperative; however, occasionally expressing a somewhat 'indirect' imperative and conveying the notion of strong obligation

****** NOTES

*** 那 
:PROPERTIES:
:CUSTOM_ID: uuid-f18e6d83-7d8c-49ca-b635-8cf9118bfc95
:Char+: 那(163,4/7) 
:END: 
**** P [[tls:syn-func::#uuid-692c0672-88f0-46d3-9778-0dcbd2eaf54b][ppostadV]] {[[tls:sem-feat::#uuid-d82256cd-a1c1-4a58-b15f-615a92237386][question]]} / sentence final particle corresponding roughly to modern Manadarin 呢 (indicating the speaker's assum...
:PROPERTIES:
:CUSTOM_ID: uuid-1e0198bc-562f-4aa2-94a4-398ee6cb5709
:END:
****** DEFINITION

sentence final particle corresponding roughly to modern Manadarin 呢 (indicating the speaker's assumption that his proposition is true: "S, is it not?" "it is well S"

****** NOTES

*** 麼 mǒ (OC:maalʔ MC:mʷɑ )
:PROPERTIES:
:CUSTOM_ID: uuid-d27f137f-c5d6-4fff-b310-0bcda1d794fc
:Char+: 麼(200,3/14) 
:GY_IDS+: uuid-c27dc167-4b8e-4dd1-9a2d-95754ccec107
:PY+: mǒ     
:OC+: maalʔ     
:MC+: mʷɑ     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-2d131ece-0e8e-4fd3-8839-9395b7aa4b14][colloquial]]} / vernacular interrogative sentence final particle, indicating a yes/no question (precursor of Modern...
:PROPERTIES:
:CUSTOM_ID: uuid-2f0132dc-3a05-4201-8150-6fefbdd270cb
:END:
****** DEFINITION

vernacular interrogative sentence final particle, indicating a yes/no question (precursor of Modern Chinese 嗎)

****** NOTES

*** 也無 yěwú (OC:lalʔ ma MC:jɣɛ mi̯o )
:PROPERTIES:
:CUSTOM_ID: uuid-cbd373c3-bcff-4951-912e-f312425e59c9
:Char+: 也(5,2/3) 無(86,8/12) 
:GY_IDS+: uuid-208b48d4-5b38-4edb-8418-80f4dcff11e3 uuid-5de002ac-c1a1-4519-a177-4a3afcc155bb
:PY+: yě wú    
:OC+: lalʔ ma    
:MC+: jɣɛ mi̯o    
:END: 
**** SOURCE REFERENCES
***** OTA 1958
 - [[cite:OTA-1958][Ōta 太田(1958), 中國語歷史文法 Chūgokugo rekishi bunpō A Historical Grammar of the Chinese Language]]
***** PAN CHONGZHONG 1982
 - [[cite:PAN-CHONGZHONG-1982][Pān 潘(1982), 漢語語法史概要 Hànyǔ yǔfǎ shǐ gàiyào An Outline of the History of Chinese Grammar]]
***** SUN XIXIN 1999
 - [[cite:SUN-XIXIN-1999][Sūn 孫(1999), 近代漢語語氣詞 Jìndài hànyǔ yǔqǐcí Sentence Final Modal Particles in Early Mandarin]], p.50-60

***** WANG LI 1989
 - [[cite:WANG-LI-1989][Wáng 王(1989), 漢語語法史 Hànyǔ yǔfǎ shǐ A History of Chinese Grammar]]
**** P [[tls:syn-func::#uuid-04c5d26e-838a-4267-a260-5926111fe077][PPpostadS]] / final particles marking a yes/no question (usually (but not always) interrogative adverb 還 has to a...
:PROPERTIES:
:CUSTOM_ID: uuid-abcfd3e3-7640-4cc9-b2a9-9c31647fe3df
:END:
****** DEFINITION

final particles marking a yes/no question (usually (but not always) interrogative adverb 還 has to appear in this type of construction: 還...也無) (Note that ist has to be analyzed whether 也無 should be regarded as a constituent or not)

****** NOTES

*** 了也 liǎoyě (OC:reewʔ lalʔ MC:leu jɣɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-604fde62-a5f1-492e-bec4-41104680808e
:Char+: 了(6,1/2) 也(5,2/3) 
:GY_IDS+: uuid-9ee768eb-a750-42e6-ba2b-6dc77cbb010e uuid-208b48d4-5b38-4edb-8418-80f4dcff11e3
:PY+: liǎo yě    
:OC+: reewʔ lalʔ    
:MC+: leu jɣɛ    
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004B
 - [[cite:ANDERL-2004B][Anderl(2004), Studies in the Language of Zǔtáng jí 祖堂集]], p.490-491


Sentence final ye3 frequently occurs in combination with semi-grammticalized lia3o 了. There have been numerous suggestions how lia3o ye3 了也 should be interpreted in this construction. I think that the sequence of those two markers should be interpreted along the line with their individual functions. 



The typical function of lia3o 了  in ZTJ is to mark relative anteriority of a VP(X) to a VP(Y) in the pattern VP(X) + lia3o 了  + VP(Y). Lia3o indicates that an action is completed and ye3 expresses perfective, and indicating that the consequences of the action are still relevant at the moment of the speech act:



In the following example co-occurring with yi3 已:

1163) ZTJ 1.150; WU: 90

“你已是受戒了也， 

ni3 yi3 shi4 sho4u jie4 lia3o ye3

NPRO2SG/ADV.TEMPalready/COP.EMPHASIS/receive/precept/V.GR.TEMPcomplete/SF.PERF

"You have already received the precepts

還聽律也無？”do you still obey to the disciplinary rules?"



In the sentence above the person has already received the set of precepts, i.e. the event of being ordained is completed and has occurred in the past. However, this event has consequences which are still relevant at the moment of the speech act, indicated by the question whether the person still obeys to the precepts.



1164) ZTJ 1.156,02; WU: 94

“何不問老僧？”"Why do you not ask me?"

僧曰： The monk said:

“問則問了也。”"I have already asked [you]."



1165) ZTJ 1.166; WU: 101

師曰： The master said:

“吃飯也未?”"Have you eaten?"

對曰：[The monk] answered:

“喫飯了也。”"I have [already] eaten."



In the next example co-occurring together with za3o 早 'already' which can function synonymous to yi3 已 in vernacular texts:

1166) ZTJ 1.173; WU: 105

雲嵒問：Yu2nya2n asked:

“一句子如何言說?”"How about expounding one sentence with words?" 

師曰：The master said:

“非言說。”"There are no words to expound (express) [it]."

道吾曰：Da4owu2 said:

“早說了也。”"I have already expounded (expressed) [it]."

**** P [[tls:syn-func::#uuid-04c5d26e-838a-4267-a260-5926111fe077][PPpostadS]] {[[tls:sem-feat::#uuid-229a701e-1341-4719-9af8-a0b4e69c6c71][perfective]]} / vernacular sentence final construction indicating the perfective: (already) have Ved
:PROPERTIES:
:CUSTOM_ID: uuid-3f1979a4-2f3a-4563-bd6b-de18b20496d7
:END:
****** DEFINITION

vernacular sentence final construction indicating the perfective: (already) have Ved

****** NOTES

*** 云爾 yúněr (OC:ɢun mljelʔ MC:ɦi̯un ȵiɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-09e864f6-e8f4-4418-bffe-47b32ac044c2
:Char+: 云(7,2/4) 爾(89,10/14) 
:GY_IDS+: uuid-32021026-3e9b-46d7-967b-a3563b36310b uuid-9bbb9d85-e760-4462-bd4e-779a8bb1b5da
:PY+: yún ěr    
:OC+: ɢun mljelʔ    
:MC+: ɦi̯un ȵiɛ    
:END: 
COMPOUND TYPE: [[tls:comp-type::#uuid-a0da14bb-d0f5-4204-86ed-9093d6f0a17a][]]


**** P [[tls:syn-func::#uuid-04c5d26e-838a-4267-a260-5926111fe077][PPpostadS]] / particle marking the end of quotation
:PROPERTIES:
:CUSTOM_ID: uuid-6ed44188-40ec-45de-aace-587a54310f0e
:END:
****** DEFINITION

particle marking the end of quotation

****** NOTES

*** 在 zài (OC:sɡɯɯʔ MC:dzəi )
:PROPERTIES:
:CUSTOM_ID: uuid-2b4718d2-354d-48ff-986e-c3cb0855b393
:Char+: 在(32,3/6) 裡(145,7/13) 
:GY_IDS+: uuid-68383a76-4bb0-42bd-abf4-1567b3ccf244
:PY+: zài     
:OC+: sɡɯɯʔ     
:MC+: dzəi     
:END: 
**** SOURCE REFERENCES
***** SUN XIXIN 1999
 - [[cite:SUN-XIXIN-1999][Sūn 孫(1999), 近代漢語語氣詞 Jìndài hànyǔ yǔqǐcí Sentence Final Modal Particles in Early Mandarin]], p.91

***** WUDENG
 - [[cite:WUDENG][(1990), 五燈會元 Wǔdēng huìyuán]]
**** V [[tls:syn-func::#uuid-153e71e2-aea6-4e63-a4f7-fae445cad6dd][VPpostadS]] {[[tls:sem-feat::#uuid-5ae85a4e-5823-417b-b04f-58d7d9f263f5][emphatic]]} / vernacular sentence final phrase giving emphasis to a statement (Song period)
:PROPERTIES:
:CUSTOM_ID: uuid-b594b4cd-4159-451e-93a1-95b98a41eedc
:END:
****** DEFINITION

vernacular sentence final phrase giving emphasis to a statement (Song period)

****** NOTES

*** 已矣 yǐyǐ (OC:k-lɯʔ ɢɯʔ MC:jɨ ɦɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-8a147961-7d7f-4b33-a8a0-9926aa1d9c68
:Char+: 已(49,0/3) 矣(111,2/7) 
:GY_IDS+: uuid-e799b325-78d4-4326-a46d-ca3498ecce7a uuid-644760a0-b567-4543-90dd-32afbfa9849c
:PY+: yǐ yǐ    
:OC+: k-lɯʔ ɢɯʔ    
:MC+: jɨ ɦɨ    
:END: 
****  [[tls:syn-func::#uuid-87bb7159-67cd-4bc9-91a6-b79fb2422227][VPipostadS]] / and that is all there is to be said (We take this difficult case to be one of a grammaticalised VP ...
:PROPERTIES:
:CUSTOM_ID: uuid-eb92335f-73d9-4fbe-b0cd-d4507da8f5c7
:END:
****** DEFINITION

and that is all there is to be said (We take this difficult case to be one of a grammaticalised VP which is no longer accessible to negation, even "in principle"

****** NOTES

*** 矣哉 yǐzāi (OC:ɢɯʔ skɯɯ MC:ɦɨ tsəi )
:PROPERTIES:
:CUSTOM_ID: uuid-d1b96739-c1fa-4af5-9485-2799ed3cc0c1
:Char+: 矣(111,2/7) 哉(30,6/9) 
:GY_IDS+: uuid-644760a0-b567-4543-90dd-32afbfa9849c uuid-37d48986-0938-4d3c-84fb-6e713e43a651
:PY+: yǐ zāi    
:OC+: ɢɯʔ skɯɯ    
:MC+: ɦɨ tsəi    
:END: 
COMPOUND TYPE: [[tls:comp-type::#uuid-dd191d8b-31fa-4f37-9baf-8702c3cbf719][]]


**** P [[tls:syn-func::#uuid-04c5d26e-838a-4267-a260-5926111fe077][PPpostadS]] / emphatic and exclamatory final particle combination
:PROPERTIES:
:CUSTOM_ID: uuid-85a172fb-c12c-44c3-90b2-c448bd9f1821
:END:
****** DEFINITION

emphatic and exclamatory final particle combination

****** NOTES

****  [[tls:syn-func::#uuid-9fc32025-1965-4a87-aa41-ffb936acf969][PPpostadV.adS]] / exclamatory particles
:PROPERTIES:
:CUSTOM_ID: uuid-d8ce72b9-6cd1-491f-8d4d-7fd819d97cbf
:END:
****** DEFINITION

exclamatory particles

****** NOTES

*** 在 zài (OC:sɡɯɯʔ MC:dzəi )
:PROPERTIES:
:CUSTOM_ID: uuid-541ffb34-4c7d-4984-8760-706b57307762
:Char+: 在(32,3/6) 這(162,7/11) 裡(145,7/13) 
:GY_IDS+: uuid-68383a76-4bb0-42bd-abf4-1567b3ccf244
:PY+: zài     
:OC+: sɡɯɯʔ     
:MC+: dzəi     
:END: 
**** SOURCE REFERENCES
***** SUN XIXIN 1999
 - [[cite:SUN-XIXIN-1999][Sūn 孫(1999), 近代漢語語氣詞 Jìndài hànyǔ yǔqǐcí Sentence Final Modal Particles in Early Mandarin]], p.92

***** YU GUANGZHONG 1986
 - [[cite:YU-GUANGZHONG-1986][Yú 俞(), 《水滸全傳》句末的‘在這（那）里’考 Shuǐhǔ quán zhuàn jùmò de 'zài zhè (nà) lǐ' kǎo 中國語文 Zhongguo yuwen]]

analysis of the phrase in SHUIHUZHUAN

**** V [[tls:syn-func::#uuid-153e71e2-aea6-4e63-a4f7-fae445cad6dd][VPpostadS]] {[[tls:sem-feat::#uuid-5ae85a4e-5823-417b-b04f-58d7d9f263f5][emphatic]]} / vernacular sentence final phrase giving emphasis to a statement (early examples in Song texts, more...
:PROPERTIES:
:CUSTOM_ID: uuid-d302355f-2fd5-459f-b6ef-5e07fe674f4b
:END:
****** DEFINITION

vernacular sentence final phrase giving emphasis to a statement (early examples in Song texts, more frequently used during Yuan and Ming)

****** NOTES

*** 夫 fū (OC:pa MC:pi̯o )
:PROPERTIES:
:CUSTOM_ID: uuid-65e069bd-d162-4c39-9754-18d5262c5f96
:Char+: 夫(37,1/4) 
:GY_IDS+: uuid-438dbee0-c789-4bb0-8bb3-91aff4d4487c
:PY+: fū     
:OC+: pa     
:MC+: pi̯o     
:END: 
**** P [[tls:syn-func::#uuid-c086c9bd-8ec5-463f-9803-c938c8b0d4d9][ppostadS]] {[[tls:sem-feat::#uuid-ee80ba53-f7eb-484d-b807-f36f9e0404a7][subjective]]} / n'est-ce pas?
:PROPERTIES:
:CUSTOM_ID: uuid-6af07dfa-fdd5-4592-ba2c-e928b359f29c
:END:
****** DEFINITION

n'est-ce pas?

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
