# -*- mode: mandoku-tls-view -*-
#+TITLE: GALLANTRY
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= GALLANTRY
:PROPERTIES:
:CUSTOM_ID: uuid-a7537145-a2ff-49f4-83a1-3b494ce0fa34
:END:
** DEFINITION

COMMENDABLY POLITE TEASING ATTENTION, ESPECIALLY of MEN towards WOMEN, PLAYFULLY PRETENDING SEXUAL INTEREST.

** NOTES

*** Modern Chinese Criteria
The Chinese words offered in dictionaries are words of flattery and connote no erotic interest. On the other hand the field of flattery is abundantly populated with words:

殷勤

獻殷勤

拍馬屁

灌米湯

吹喇叭

抬轎子

吹吹拍拍

戴高帽子

阿諛逢迎

阿諛奉承

阿其所好

投其所好

依阿取容

偷合苟容

先意承旨

曲意逢迎

脅肩諂笑

吮癰舐痔

溜須拍馬

*** Old Chinese Contrasts
Il s'agit de faire sentir que le séducteur - plus séduit que séducteur - est toujours prêt a lâcher prise. Il ne cherche pas de consentement de la femme - terme trop lourd, qui pèse son poids d'engagement. Le galant homme cherche en toute occasion l'agrément féminin - c'est une visée plus diffuse. Que les femmes se plaisent avc lui qu'elles s'amusent, c'est tout ce qu'il prétend vouloir..... Derrière les prévenances souffle une inspiration qu'on pourrait dire libérale, car elle consiste à ne pas crraindre la liberte des femmes. (HABIB 2006.58)

** POINTERS
*** SEE ALSO
 - [[tls:concept:EROTIC][EROTIC]]

*** KIND OF
 - [[tls:concept:POLITE][POLITE]]

** SOURCE REFERENCES
*** HABIB 2006
 - [[cite:HABIB-2006][Habib(2006), Galanterie francaise]]
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
