# -*- mode: mandoku-tls-view -*-
#+TITLE: IDEOLOGY
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= IDEOLOGY
:PROPERTIES:
:CUSTOM_ID: uuid-9b3fd8b9-3cf7-476b-af35-981054b1d58e
:SYNONYM+:  BELIEFS
:SYNONYM+:  IDEAS
:SYNONYM+:  IDEALS
:SYNONYM+:  PRINCIPLES
:SYNONYM+:  ETHICS
:SYNONYM+:  MORALS
:SYNONYM+:  DOCTRINE
:SYNONYM+:  CREED
:SYNONYM+:  CREDO
:SYNONYM+:  FAITH
:SYNONYM+:  TEACHING
:SYNONYM+:  THEORY
:SYNONYM+:  PHILOSOPHY
:SYNONYM+:  TENETS
:SYNONYM+:  CANON(S)
:SYNONYM+:  CONVICTION(S)
:SYNONYM+:  PERSUASION
:SYNONYM+:  INFORMAL ISM
:TR_ZH: 意識形態
:END:
** DEFINITION

SYSTEM of DOCTRINES TRANSMITTED so as to SUPPORT POLITICAL MOVEMENTS.

** NOTES

*** Modern Chinese Criteria
[LIST KINDLY COMPILED AND PROVIDED FOR TLS BY IVO SPIRA, OSLO UNIVERSITY]

人文主義 humanism

人道主義 humanitarianism

實用主義 pragmatism

共產主義 communism

民族帝國主義 national imperialism

巴枯寧主義 Bakuninism

布爾什維主義 Bolshevism

民族主義 nationalism

大民族主義 ?big-nationality chauvinism

地方民族主義 local/narrow nationalism/?nationality

民族國家主義 nationalism

國粹主義 national essentialism

國家主義 nationalism, ?statism

民粹主義 national essence-ism

保守主義 conservatism

自由主義 liberalism

自由意志主義 libertarianism

自由人主義 libertarianism

博愛主義 philanthropism

本本主義 pedantry, book worship

英雄主義 heroism

革命英雄主義 revolutionary heroism

個人英雄主義 individualistic heroism

宗派主義 sectarianism, factionalism

功用主義 utilitarianism

恐怖主義 terrorism

東方主義 orientalism

西方主義 occidentalism

鄉土主義 nativism

愛國主義 patriotism

反閃族主義 anti-semitism

反閃米特主義 anti-semitism

排猶主義 antisemitism

反猶太主義 anti-semittism

立憲主義 constitutionalism

憲政主義 constitutionalism

國際主義 internationalism

功利主義 utilitarianism

民主主義 democracy?

立體主義 cubism

民主個人主義 democratic individualism

共和主義 republicanism

權力主義 authoritarianism

擴張主義 expansionism

大國主義 ?great-nation chauvinism, great-nation-ism

大國沙文主義 great-nation chauvinism

團體主義 solidarity-ism, (trade) unionism

投降主義 capitulationism, defeatism?

復仇主義 revanchism

平均主義 egalitariansim

報復主義 revanchism

廢止努力主義 abolitionism

改良主義 reformism

順從主義 conformism

工聯主義 trade unionism, syndicalism?

泛日耳曼主義 pan-germanism

泛伊斯蘭主義 pan-islamism

泛阿拉伯主義 pan-arabism

泛非主義 pan-africanism

泛美主義 pan-americanism

平等主義 equalitarianism,

泛突厥主義 pan-turkism

泛斯拉夫主義 pan-slavism

現世主義 secularism

孤立主義 isolationism

干涉主義 interventionism

集權主義 centralism

經濟主義 economism

重農主義 physiocracy, agrarianism

重商主義 mercantilism

王道主義 governmentalism

同等主義 equalitarianism

天皇主義 mikado doctrine, tennoism

狂熱主義 fanaticism

熱狂主義 fanaticism

折衷主義 eclecticism

唯美主義 aestheticism

懷疑主義 scepticism

孔子主義 confucianism

孔教主義 confucianism

西雄主義 zionism

錫安主義 zionism

猶太復國主義 zionism, jewish revivalism

猶太擴張主義 zionism, jewish expansionism

郇山主義 zionism

法西斯主義 fascism

納粹主義 nazism

古典主義 classicism

左傾機會主義 leftist opportunism

男女平權主義 egalitarianism (in gender), feminism

左傾冒險主義 leftist adventurism

命令主義 commandism?

生物恐怖主義 bioterrorism

列寧主義 leninism

托洛茨基主義 trotzkyism

敵托主義 titoism

鐵托主義 titoism

撒切爾主義 thatcherism

易卜生主義 ibsenism

拜占庭主義 byzantinism?

帝國主義 imperialism

修正主義 revisionism

女性主義 feminism

官僚主義 bureaucratism, bureaucracy

改革主義 reformism?

工會組織主義 syndicalism

嚴正主義 puritanism

封建主義 feudalism

獨裁主義 dictorship, despotism

極權主義 totalitarianism, dictatorship

霸權主義 hegemonism

軍國主義 militarism

資本主義 capitalism

聯邦主義 federalism

集產主義 collectivism

集體主義 collectivism

女權主義 feminism

殖民主義 colonialism

歷史決定主義 historical determinism

歷史主義 historicism

達爾文主義 darwinism

現代主義 modernism

唯心主義 idealism <philosophy>

物質主義 ?materialism

唯物主義 materialism

辯證唯物主義 dialectical materialism

人格主義 personalism

大漢族主義 han-chauvinism

男性沙文主義 male chauvinism

存在主義 existentialism

守舊主義 conservatism?

鎖國主義 isolationism?

破壞主義 "destructionism", iconoclasm?

突飛主義 "launchism", "kick-startism"

東身寡過主義

兼愛主義 altruism, universalism, universal love

為我主義 egoism, selfishness

狷主義 timidism, restraintism

愛主義 "caritism", principle of love

狂主義 insane-ism, wild-ism

勿主義 don't-ism, passivism

為主義 activism, do-ism

坤主義 female-ism, receptivism, inactivism

乾主義 male-ism, activism, creativism

命主義 fatalism

力主義 dynamism, force-ism

良主義 "goodism"

頁主義

利主義 utilitarianism? useful ism?

自尊主義 egoism? self-respect-ism?

直覺主義 intuitionism

進化主義 evolutionism? progressivism?

結構主義 structuralism

達達主義 dadaism

法理主義 legalism?

開放主義 ??

支配主義 pominatism?

普救主義 universalism

福利主義 welfare ??

暴力主義 violence-ism

贍徇主義 favouritism

沙文主義 chauvinism

尾巴主義 khvostizm, tailism <pol.> nachtrabpolitik

普遍主義 universalism

召回主義 otzovizm, <pol.> ??

野蠻主義 barbarism?? savagery??

諾斯底主義 ?? gnosticism???

費邊主義 fabianism

精英主義 elitism

大同主義 cosmopolitanism? utopianism? socialism?

利人主義 altruism

新保守主義 neo-conservatism

消費主義 consumerism

實驗主義 experimentalism

個性主義 individualism?

八不主義 "eight-nots-ism"

利他主義 altruism

利己主義 egoism

自我主義 egoism

犬儒主義 cynicism

後主義 post-ism

尼采主義 Nietzsche-ism

軍閥主義 warlordism

共濟主義 universalism, mutual help-ism

君主主義 monarchism

赤化主義 communism

均當主義 communism

單邊主義 unilateralism

啟蒙主義 didacticism?

個人主義 individualism

相對主義 relativism

國民主義

獨身主義 bachelorism

新君主義 "nearchism", new-ruler-ism?

專制主義 despotism, absolutism, autocracy

德國主義 "germanism"?, German ism/doctrine

世界主義 cosmopolitanism?

排外主義 anti-foreign policy, xenophopia, antiforeignism, exclusivism

倒楣主義 defeatism?

救國主義 save-state-ism

家族主義 familism, clanism

宗族主義 clanism, lineagism??, familism??

國族主義 state-clan-ism, nationalism

種族主義 racism

西方主義 ?occidentalism

地方主義 localism, regionalism

過激主義 extremism, radicalism

急進主義 radicalism, extremism

極進主義 radicalism, extremism

興亞主義 revive Asia-ism, Asian revivalism

激進主義 radicalism, extremism

民族解放主義 national liberationism

根本主義 fundamentalism

民政主義 democracy?

性法主義 naturalism?

日和見主義 opportunism

原教旨主義 fundamentalism

實證主義 positivism

樂利主義 utilitarianism

公利主義 ??

門羅主義 Monroe doctrine, "Monroeism"

放任主義 policy of non-interference, laissez-faire doctrine, non-interventionism

自殺主義 suicidism, suicidalism, self-kill-ism

平民主義 democracy, democratism, level-people-ism,

基要主義 fundamentalism

冒險主義 adventurism, love of adventure

風頭主義 mannerism; showing off; striving for the limelight

感傷主義 sentimentalism

錦標主義 trophies mania; desire for distinctions and disregard for the quality of work

教條主義 dogmatism, doctrinairism

虛無主義 nihilism

傳承主義 ?traditionalism

傳統主義 traditionalism

後現代主義 postmodernism

行動主義 activism

積極行動主義 (positive) activism

盲動主義 putschism

機會主義 opportunism

本位主義 ?selfish departmentalism; chauvinism

自家主義 individualism

進步主義 progressivism

現實主義 realism

革命的現實主義 revolutionary realism

革命現實主義 revolutionary realism

純粹主義 purism

理想主義 idealism

革命理想主義

快樂主義 hedonism, eudaimonism

享樂主義 hedonism

烏托邦主義 utopianism

苦樂主義 ascetism

司脫葛主義 stoicism

伊比鳩主義 epicureanism

部落主義 tribalism

威權主義 authoritarianism

少數統治主義 oligarchy

內求主義 intrinsicism

理性主義 rationalism

經院主義 scholasticism

非道德主義 immoralism

工具主義 instrumentalism

苦行主義 ascetism

慶世主義 misantropy??

科學主義 scientism

唯科學主義 scientism

環境主義 environmentalism

美洲主義 americanism

素食主義 vegetarianism

裸體主義 nudism

浪漫主義 romanticism, romantism

空想主義 utopianism

革命的浪漫主義 revolutionary romanticism

斯多葛主義 stoicism

革命浪漫主義 revolutionary romanticism

樂觀主義 optimism

革命樂觀主義 revolutionary optimism

小圈子主義 provincialism

大伊斯蘭主義 great-islamism, pan-islamism

伊斯蘭原教旨主義 islamic fundamentalism

蘇菲主義 sufism

千禧年主義 millenialism, chiliasm

加耳文主義 calvinism

實效主義 pragmat(ic)ism

喀爾文主義 calvinism

絕對主義 absolutism

抽象主義 abstractionism

美學主義 aestheticism

非統治主義 anarchism

禁慾主義 ascetism

行為主義 behaviorism

公社主義 communalism

社區主義 communitarianism

通俗主義 conventionalism

因襲主義 conventionalism

解構主義 deconstructionism

情感主義 emotionalism

經驗主義 empiricism; experientialism

表現主義 expressionism

形式主義 formalism

古代個人主義 gnosticism;

黑格爾主義 hegelism

王法主義 legalism

古典自由主義 libertarianism

邏輯主義 logicism

毛澤東主義 maoism

新柏拉圖主義 neo-platonism

和平主義 pacifism

心理學主義 psychologism

蘭德主義 randism?

化約主義 reductionism

呈現主義 representationalism

社會達爾文主義 social darwinism

史大林主義 stalinism

非統治工團主義 syndicalism

工團主義 syndicalism

有用主義 utilitarianism

清教徒主義 puritanism

信義教主義 new teaching-ism, Lutheranism

路德主義 lutheranism

修道主義 monasticism

神秘主義 mysticism

惡魔主義 satanism

虔敬主義 pietism

敬虔主義 pietism

信仰主義 fideism

實用化主義

福音主義 evangelism

自利主義 egoism

山岸主義 [ 日本一種空想社會主義...]

馬克思主義 marxism

馬克思列寧主義 marxism-leninism

無政府主義 anarchism

安那其主義 anarchism

公有主義 communism

社會主義 socialism

空想社會主義 utopian socialism

康門尼斯姆主義 communism

[LIST KINDLY PROVIDED BY IVO SPIRA, OSLO UNIVERSITY]

** POINTERS
*** TAXONOMY
 - [[tls:concept:URBANISM][URBANISM]]
 - [[tls:concept:MANNERISM][MANNERISM]]

*** SEE ALSO
 - [[tls:concept:DOCTRINE][DOCTRINE]]

*** KIND OF
 - [[tls:concept:DOCTRINE][DOCTRINE]]

** SOURCE REFERENCES
*** FRANKE 1989
 - [[cite:FRANKE-1989][Franke Gipper Schwarz(1989), Bibliographisches Handbuch zur Sprachinhaltsforschung. Teil II. Systematischer Teil. B. Ordnung nach Sinnbezirken (mit einem alphabetischen Begriffsschluessel): Der Mensch und seine Welt im Spiegel der Sprachforschung]], p.139B

*** HAHN 1981
 - [[cite:HAHN-1981][Hahn Welskopf(1981), Die Begriffe auf -ismos Soziale Typenbegriffe]]
*** KOSELLECK 1972-97
 - [[cite:KOSELLECK-1972-97][Koselleck(1972-97), Geschichtliche Grundbegriffe]], p.3.131-170

*** LIU JIANGUO 1995
 - [[cite:LIU-JIANGUO-1995][Liu  劉(1995), 主義大詞典]]

Many modern Chinese words in zhu3yi4 do not translate into English "-isms" but rather doctrines.  Thus the application of the Chinese zhu3yi4 is singificantly broader than the Western "ism" from which it derives by loan translation.

*** RITTER 1971-2007
 - [[cite:RITTER-1971-2007][Ritter Gruender Gabriel(1971-2007), Historisches Woerterbuch der Philosophie]], p.4.158
 (IDEOLOGIE)
*** UEDING 1992ff
 - [[cite:UEDING-1992ff][Ueding(1992ff), Historisches Woerterbuch der Rhetorik]], p.4.155

*** WERNER 1981
 - [[cite:WERNER-1981][Werner Welskopf(1981), Das Suffix -ismus von -ismos Soziale Typenbegriffe]]

There is a wealth of biblographic references concerning a range of European languages, and a lively discussion with the important student of the German vocabulary F. Dornseiff.

*** POIRIER 1991
 - [[cite:POIRIER-1991][Poirier(1991), Histoire des moeurs]], p.2.1419-1487

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
