# -*- mode: mandoku-tls-view -*-
#+TITLE: INTERRUPT
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= INTERRUPT
:PROPERTIES:
:CUSTOM_ID: uuid-cb22b5dd-9568-4d1c-aa9e-392e26532c52
:SYNONYM+:  CUT IN (ON)
:SYNONYM+:  BREAK IN (ON)
:SYNONYM+:  BARGE IN (ON)
:SYNONYM+:  INTERVENE (IN)
:SYNONYM+:  PUT ONE'S OAR IN
:SYNONYM+:  PUT ONE'S TWO CENTS IN
:SYNONYM+:  INTERJECT
:SYNONYM+:  INFORMAL BUTT IN (ON)
:SYNONYM+:  CHIME IN (WITH
:TR_ZH: 插嘴
:END:
** DEFINITION

SPEAK so as to CAUSE someone who WISHES TO CONTINUE TO SPEAK to STOP SPEAKING.

** NOTES

*** Modern Chinese Criteria
打斷 is a current modern word interrupting someone.

插嘴 is a colloquial modern word for interrupting someone.

插話 is a formal way of referring to an interruption.

搶嘴 (lit) is slightly more literary way of referring to an interruption.

插口 is a slightly less colloquial word for interrupting someone.

多嘴 can come to refer to someone interrupting everybody and talking too much.

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** SOURCE REFERENCES
*** DOEDERLEIN 1840
 - [[cite:DOEDERLEIN-1840][Doederlein(1840), Lateinische Synonyme und Etymologien]]

INTERRUPT

intercapedo refers to a quiet, often even a well-meaning interruption.

interruptio refers to a violent or at least abrupt interruption.

interpellatio refers to interruption by speech only whereby a speaker is prevented from going on speaking.

interlocutio refers to an act of speaking while someone else is already speaking without stopping the other person from speaking at the same time.

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
