# -*- mode: mandoku-tls-view -*-
#+TITLE: KOWTOW
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= KOWTOW
:PROPERTIES:
:CUSTOM_ID: uuid-d8d580bd-ed86-422d-b433-817d79185a5a
:TR_ZH: 扣頭
:END:
** DEFINITION

BOW DOWN and KNOCK one's HEAD against the FLOOR IN FRONT of someone so as to SHOW RESPECT.

** NOTES

*** Old Chinese Criteria
Not yet done. See MODERN CHINESE

*** Modern Chinese Criteria
磕頭 / 叩頭 is the current modern word for kowtowing.

頓首 (lit) is a literary word current in epistolary style.

叩首 (lit) is an elevated way of saying the same thing.

跪拜 is an analytic dramatising way of referring to kowtowing, specifying the kneeling and bowing.

叩拜 focusses on the knocking and the bowing.

下拜 focusses on the low bowing.

展拜 focusses on the spreading of the hands as one knocks the floor with one's forehead.

泥首 "dirty one's head" dramatises the dirtying of one's forehead as one hits the ground with one's forehead.

稽首 is a current traditionalist way of referring to kowtowing.

稽顙 (lit, obs) is an elevated term for kowtowing.

叩

拜

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** POINTERS
*** SEE ALSO
 - [[tls:concept:KNEEL][KNEEL]]

*** KIND OF
 - [[tls:concept:BOW DOWN][BOW DOWN]]

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
