# -*- mode: mandoku-tls-view -*-
#+TITLE: LAP
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= LAP
:PROPERTIES:
:CUSTOM_ID: uuid-4d9cf4aa-94f2-4846-a895-56bc51191a1c
:TR_ZH: 膝部
:END:
** DEFINITION

SURFACE OF THIGH AND STOMACH. [] (Comparison with Russian interesting, hence the group.)

** NOTES

*** Modern Chinese Criteria
膝部

膝上

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** SOURCE REFERENCES
*** DOEDERLEIN 1840
 - [[cite:DOEDERLEIN-1840][Doederlein(1840), Lateinische Synonyme und Etymologien]]

LAP

gremium refers to the lap in general, especially as a place where one seeks protection or solace.

sinus refers to the bosom, all within the compass of breast and arms, and the word is also used in transferred senses "a bay" as well as figuratively "the heart/bosom" as the seat of feelings.

*** IORDANSKAJA 1996
 - [[cite:IORDANSKAJA-1996][Iordanskaja Paperno Leed(1996), A Russian-English Collocational Dictionary of the Human Body]], p.160

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
