# -*- mode: mandoku-tls-view -*-
#+TITLE: NONSENSE
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= NONSENSE
:PROPERTIES:
:CUSTOM_ID: uuid-fdd2e445-4a61-4cf3-bfd1-158726b36de6
:TR_ZH: 廢話
:END:
** DEFINITION

CONFUSED SPEECH which LACKS MEANING.

** NOTES

*** Old Chinese Criteria
The concept of nonsense is not prominent in ancient Chinese discourse.

*** Modern Chinese Criteria
胡說 is the current modern Chinese verb for talking nonsense.

放屁 (informal) is a highly colloquial word referring to talking nonsense.

胡扯 is a highly colloquial modern Chinese word for nonsense.

嚼舌 focusses in a colloquial way on inarticulateness as the cause for the production of nonsense.

瞎扯 is colloquial and intensitive.

瞎說 is a more literary common word for talking nonsense or nominally nonsense.

亂說 focusses on the intellectually chaotic nature of nonsense.

亂道 (lit) refers to confused discourse in a rather formal way.

瞎謅 (lit, rare) refers to un-thought-through wild talk in a dignified way.

嚼蛆 jiáoqū refers to talking nonsense.

咧咧 (coll) refers to meaningless blabbering.

亂彈琴 "strum the lute chaotically" is a figurative literary way of referring to talking nonsense.

胡言亂語 (prov) refers in a hyperbolic literary way to the talking of nonsense.

胡說八道 (prov) is a highly colloquial idiomatic way of referring to the talking of nonsense.

妄言妄語 (prov) is a formal and still way of referring to the talking of nonsense.

說夢話 "talk dream talk" is a figurative way of referring to the talking of nonsense.

鬼話連篇 (prov) focusses on the lengthiness of the onsense.

囈語連天 (prov, obs) refers in a recondite way to the talking of nonsense.

言不及義 (prov) focusses on the failure of nonsense to articulate even wrong meaning.

信口開河 (prov) focusses on the irresponsibility of talk and is marginal in the group.

信口雌黃 (prov) focusses on the irresponsibility of talk and is marginal in the group.

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** POINTERS
*** SEE ALSO
 - [[tls:concept:FART][FART]]

*** KIND OF
 - [[tls:concept:SPEAK][SPEAK]]

** SOURCE REFERENCES
*** CASSIN 2004
 - [[cite:CASSIN-2004][Cassin(2004), Vocabulaire européen des philosophies. Dictionnaire des intraduisibles]], p.859

*** RITTER 1971-2007
 - [[cite:RITTER-1971-2007][Ritter Gruender Gabriel(1971-2007), Historisches Woerterbuch der Philosophie]], p.11.270
 (UNSINN)
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 話 huà (OC:ɡroods MC:ɦɣɛi )
:PROPERTIES:
:CUSTOM_ID: uuid-a28378d9-e9c1-4251-90e7-9f60a771acb7
:Char+: 話(149,6/13) 
:GY_IDS+: uuid-0d7f8f0a-539c-4b9c-a0a5-4a6fcb9b85d2
:PY+: huà     
:OC+: ɡroods     
:MC+: ɦɣɛi     
:END: 
**** N [[tls:syn-func::#uuid-76be1df4-3d73-4e5f-bbc2-729542645bc8][nab]] {[[tls:sem-feat::#uuid-f55cff2f-f0e3-4f08-a89c-5d08fcf3fe89][act]]} / empty talk
:PROPERTIES:
:CUSTOM_ID: uuid-111254de-d808-4513-9338-98aa00ef78a4
:END:
****** DEFINITION

empty talk

****** NOTES

**** V [[tls:syn-func::#uuid-fbfb2371-2537-4a99-a876-41b15ec2463c][vtoN]] / talk nonsense about
:PROPERTIES:
:CUSTOM_ID: uuid-9e2cb857-cbed-4100-b698-0ebe2af8c290
:END:
****** DEFINITION

talk nonsense about

****** NOTES

*** 邪哆 xiéchǐ (OC:sɢlja khljalʔ MC:zɣɛ tɕhiɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-3d2c8cac-018a-4820-91ab-cac36205de3a
:Char+: 邪(163,4/7) 哆(30,6/9) 
:GY_IDS+: uuid-9c17ae43-ec35-48c3-8bec-a69c9a87fb1c uuid-533cb576-97f0-4db4-96ac-0491619327d9
:PY+: xié chǐ    
:OC+: sɢlja khljalʔ    
:MC+: zɣɛ tɕhiɛ    
:END: 
**** N [[tls:syn-func::#uuid-db0698e7-db2f-4ee3-9a20-0c2b2e0cebf0][NPab]] {[[tls:sem-feat::#uuid-e8b7b671-bbc2-4146-ac30-52aaea08c87d][text]]} / gibberish; nonsense; blah-blah; heterodoxy
:PROPERTIES:
:CUSTOM_ID: uuid-cd93a865-64f4-4ead-b204-bd5a506e3742
:END:
****** DEFINITION

gibberish; nonsense; blah-blah; heterodoxy

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
