# -*- mode: mandoku-tls-view -*-
#+TITLE: OBJECT MARKER
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= OBJECT MARKER
:PROPERTIES:
:CUSTOM_ID: uuid-bd1a4a4f-d944-4c3e-8013-9a83d46b17a3
:TR_ZH: 賓語標記
:END:
** DEFINITION

PARTICLE that SHOWS that something is the grammatical OBJECT. []

** NOTES

*** Modern Chinese Criteria
rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／ LU JIANMING

** SOURCE REFERENCES
*** CASSIN 2004
 - [[cite:CASSIN-2004][Cassin(2004), Vocabulaire européen des philosophies. Dictionnaire des intraduisibles]], p.867
 (OBJET)
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 之 zhī (OC:kljɯ MC:tɕɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-a473e45d-3b7f-4530-b0b7-db5061a38991
:Char+: 之(4,3/4) 
:GY_IDS+: uuid-dd2ad4ab-7266-4ee9-a622-5790a96a6515
:PY+: zhī     
:OC+: kljɯ     
:MC+: tɕɨ     
:END: 
**** N [[tls:syn-func::#uuid-5920aca6-2ca6-44a9-a64b-55b3c07b342d][npro+Vt.postN{OBJ}]] / 是之謂
:PROPERTIES:
:CUSTOM_ID: uuid-f1f96cfd-6eb0-4883-b80f-f1d77b9244e4
:END:
****** DEFINITION

是之謂

****** NOTES

*** 以 yǐ (OC:k-lɯʔ MC:jɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-176200e6-6722-421f-9a18-3caeb2f5f82f
:Char+: 以(9,3/5) 
:GY_IDS+: uuid-4a877402-3023-41b9-8e4b-e2d63ebfa81c
:PY+: yǐ     
:OC+: k-lɯʔ     
:MC+: jɨ     
:END: 
**** SOURCE REFERENCES
***** DUAN DESEN 1992A
 - [[cite:DUAN-DESEN-1992A][Duan 段(1992), 簡明古漢語同義詞詞典]], p.609

**** V [[tls:syn-func::#uuid-73761cec-9c0f-41e0-83fe-b7e107452f86][vt(oN.)adVt]] / object marker: 把它
:PROPERTIES:
:CUSTOM_ID: uuid-304103d0-7d78-4f72-91f0-aa09ef6eb6b3
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

object marker: 把它

****** NOTES

**** V [[tls:syn-func::#uuid-7d39b066-57d7-4249-8fae-906ed8d750fb][vt0oN.postV]] / introduces the direct object of verbs of giving or saying something to somebody etc.
:PROPERTIES:
:CUSTOM_ID: uuid-388213b2-314a-40b0-91a1-3bb303f8dde5
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

introduces the direct object of verbs of giving or saying something to somebody etc.

****** NOTES

**** V [[tls:syn-func::#uuid-25270f92-78eb-4334-a1b2-61ee030801df][vtoN.adVt]] / object marker: 把(這個東西) also: 以。。。而。。。
:PROPERTIES:
:CUSTOM_ID: uuid-6f3d5aea-0e0e-4bfd-a327-a299f8fbbd12
:WARRING-STATES-CURRENCY: 5
:END:
****** DEFINITION

object marker: 把(這個東西) also: 以。。。而。。。

****** NOTES

**** V [[tls:syn-func::#uuid-73761cec-9c0f-41e0-83fe-b7e107452f86][vt(oN.)adVt]] {[[tls:sem-feat::#uuid-5da3200a-c46f-4d20-9917-726937666d0b][N=nonref]]} / object marker with an omitted dummy object
:PROPERTIES:
:CUSTOM_ID: uuid-a8677025-470a-4282-a8b7-27af90d8c2d4
:END:
****** DEFINITION

object marker with an omitted dummy object

****** NOTES

*** 取 qǔ (OC:skhoʔ MC:tshi̯o )
:PROPERTIES:
:CUSTOM_ID: uuid-307d13e0-b8d5-4745-92bf-ac742c5fa5f4
:Char+: 取(29,6/8) 
:GY_IDS+: uuid-ae7faa0b-7337-42ff-bf3e-a4d370dad65d
:PY+: qǔ     
:OC+: skhoʔ     
:MC+: tshi̯o     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004C
 - [[cite:ANDERL-2004C][Anderl(2004), Studies in the Language of Zu-tang Ji 祖堂集]], p.283-284


This is another early coverb of disposal which recently has come into focus. Cao Guangshun and Yu Xiaorong have conducted extensive research on this coverb, analyzing a number of early s$utra translations.825 [[fn. 825: The source materials dating from the Eastern Han are: Da4o-di4 ji1ng 道地經, Da4o-xi2ng bo1-re3 ji1ng 道行般若經, Chua2n-zho1u sa1n-me4i ji1ng 船舟三昧經, We2n-shu1 shi1-li4 we4n pu2-sa4 shu3 ji1ng 文殊師利問菩薩署經, Fo2-shuo1 Du3nzhe1ntuo2luo2 suo3 we4n Ru2la2i sa1n-me4i ji1ng 佛說伅真陀羅所問如來三昧經, A1-ha2n ko3u-jie3 shi2-e4r yi1n-yua2n ji1ng 阿含口解十二因緣經, Fo2-shuo1 che2ng-ju4 gua1ng-mi2ng di4ng-yi4 ji1ng 佛說成具光明定意經, Zho1ng be3n-qi3 ji1ng 中本起經, Xiu1-xi2ng be3n-qi3 ji1ng 修行本起經, Ze1ng-yi1 a1-ha2n ji1ng 增壹阿含經; later texts include: Chu1-ya4o ji1ng 出曜經, Da4 zhua1ng-ya2n lu4n ji1ng 大庄巖論經, Xia2n-yu2 ji1ng 賢愚經, Fo2-be3n xi2ng-ji2 ji1ng 佛本行集經 (FOBEN XINGJI JING). See Cao Guangshun/Yu Xiaorong 2000: 555-556.]] They found out that qu4 was an important coverb of disposal in early s$utra translations and appeared in the 'extended' as well as the 'narrow' form.826 [[fn. 826: Examples of the 'extended form': V{make into}: 當取汝身分為三分。(Chu1-ya4o ji1ng 出曜經). V{transport}: 即取眾淚置右掌中。(Da4 zhua1ng-ya2n lu4n ji1ng 大庄巖論經).]] Surprisingly, they found also numerous examples of the 'narrow' form, including the following patterns: 



(a) qu3 取 (COV.DISP) + N + V 827

[[fn. 827: N is the coverbal object. E.g. 欲取我殺。 '[He] wanted to kill me.] (Ze1ng-yi1 a1-ha2n ji1ng 增壹阿含經); 取門閉 'Shut the door.' (Ze1ng-yi1 a1-ha2n ji1ng 增壹阿含經) (Cao Guangshun/Yu Xiaorong 2000: 557).]]

(b) qu3 取 (COV.DISP) + N (+ ADV) + V (+ X)828

[[fn. 828: X is an additional element like a verbal complement. E.g. 正使王今取我身體碎如芥子。 '...causing the king to pulverize my body into [pieces the size of] mustard seeds.' [?] (Chu1-ya4o ji1ng 出曜經).]]

(c) qu3 取 (COV.DISP) + N + V + zhi1 之829

[[fn. 829: In these examples the object pronoun zhi1 之 is resumptive of N. (i.e. the coverbal object is identical with the object of the main verb). E.g. 取守門人殺之。 '[He] killed the gate keeper.' (Ze1ng-yi1 a1-ha2n ji1ng 增壹阿含經); 王取父王害之。 'The king inflicted damage on his father.' (Ze1ng-yi1 a1-ha2n ji1ng 增壹阿含經); (Cao Guangshun/Yu Xiaorong 2000: 558). The pattern with resumptive object pronoun in the disposal sentence is preserved in a number of modern Chinese dialects (with ba3 把 instead of qu3 and ta1 他/她/它 instead of zhi1 之; for examples see Cao Guangshun/Yu Xiaorong 2000: 559).]]

(d) qu3 取 (COV.DISP) + V + zhi1 之830

[[fn.830: In this construction the coverbal object is deleted: 乃得七瓶，悉取埋之。(Xia2n-yu2 ji1ng 賢愚經); 般若波羅密者，當取供養之。 'As for the perfection of wisdom, offerings should be made to it.' (Da4o-xi2ng bo1-re3 ji1ng 道行般若經); see Cao Guangshun/Yu Xiaorong 2000: 560.]]



Cao/Yu regard (b) as an extension of (a); (a) and (d) as an abbreviated form of (c) (in (a) the resumptive object pronoun is deleted and in (d) the coverbal object is deleted). Cao/Yu argue against the description of the disposal form as 'preposed object' but rather see it as development from the serial verb construction 

V1 + N1 + V2 + N2 (N1 is not N2)  > V1 + N1 + V2 + N2 (N1 = N2) 

and the subsequent deletion of N2 (or N1 as in (d) above) and a reanalysis of qu3.831 During this early period the occurrences of the disposal form were quite limited and the semantic fields of the main verbs restricted (usually expressing that something unpleasant is inflicted on the recepient of the action, e.g. being hit, killed, etc.). This is an indiation that the construction was still in the beginning of its development. Cao/Yu think that the development of the disposal form (with its presposed object) was maybe influenced by the grammar of Sanskrit and Pali where the object is frequently preposed to the verb.832 However, in these early texts, examples where the first object is deleted (and as such to a higher degree conforms with Chinese word-order) are still more frequent:



qu3 取 + N + V + zhi1 之 F: 25

qu3 取 + N + V F: 29

qu3 取 + V + zhi1 之 F: 63



Cao/Yu interprete the emergence of the 'narrow' disposal form as a 'distortion' of Chinese word-order.833

***** CAO GUANGSHUN/YU XIAORONG 2000
 - [[cite:CAO-GUANGSHUN/YU-XIAORONG-2000][Cáo 曹 Yù 遇(), 中古譯經中的處置式 Zhōnggǔ yìjīng zhōng de chùzhìshì [The Disposal Form in Medieval Sutra Translations] 中國語文 Zhongguo yuwen]], p.555-561

**** V [[tls:syn-func::#uuid-6c799c2c-5270-4aab-abd9-8b5253865818][vad.VtoN]] / take the object and V it
:PROPERTIES:
:CUSTOM_ID: uuid-7470d574-1eb1-4a79-9527-644ddcef7426
:END:
****** DEFINITION

take the object and V it

****** NOTES

*** 將 jiāng (OC:skaŋ MC:tsi̯ɐŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-cfe200ff-01cd-4465-b41b-3ca59f10451f
:Char+: 將(41,8/11) 
:GY_IDS+: uuid-69629cac-c2c1-4e4e-973b-f5d11b631144
:PY+: jiāng     
:OC+: skaŋ     
:MC+: tsi̯ɐŋ     
:END: 
**** V [[tls:syn-func::#uuid-18044d90-be6f-41c1-a339-ba079218aa31][vt(+N.)adVt]] / 把這個東西
:PROPERTIES:
:CUSTOM_ID: uuid-ca435c87-7928-4be9-9b5a-019a7185989f
:END:
****** DEFINITION

把這個東西

****** NOTES

**** V [[tls:syn-func::#uuid-97bf7569-f7ae-4de1-a7b3-99ec2ed24fe8][vt(oN1.)+VtoN2]] {[[tls:sem-feat::#uuid-dcc7a785-d784-4137-b2d0-b8910a9a9b5d][N1 and N2 coreferential]]} / 把這個東西
:PROPERTIES:
:CUSTOM_ID: uuid-ab491c73-ffad-4686-9818-1c6886a52ab0
:END:
****** DEFINITION

把這個東西

****** NOTES

**** V [[tls:syn-func::#uuid-9e8c327b-579d-4514-8c83-481fa450974a][vtoN.adV]] / taking N to go on to V it> object marker
:PROPERTIES:
:CUSTOM_ID: uuid-69f07be6-015b-4c02-b331-23fda433c8fc
:END:
****** DEFINITION

taking N to go on to V it> object marker

****** NOTES

****  [[tls:syn-func::#uuid-2a03c0b2-5ce5-4358-b6ec-b15cb0ca3a90][vtoNpro.adVtt]] / marker of the diposal form (with ditransitive main verbs of the semantic category {to give}
:PROPERTIES:
:CUSTOM_ID: uuid-ab703a27-c9cd-47bb-871a-5374a3a05d7e
:END:
****** DEFINITION

marker of the diposal form (with ditransitive main verbs of the semantic category {to give}

****** NOTES

*** 對 duì (OC:k-luubs MC:tuo̝i )
:PROPERTIES:
:CUSTOM_ID: uuid-597bc9c2-6718-4e41-b84b-29730f941c00
:Char+: 對(41,11/14) 
:GY_IDS+: uuid-8bb517d7-1338-4c4c-ade1-75c15d83ba3a
:PY+: duì     
:OC+: k-luubs     
:MC+: tuo̝i     
:END: 
**** V [[tls:syn-func::#uuid-9e8c327b-579d-4514-8c83-481fa450974a][vtoN.adV]] / with respect to the object N
:PROPERTIES:
:CUSTOM_ID: uuid-ec98334f-26b3-40a8-922e-67ff96c6dd6e
:END:
****** DEFINITION

with respect to the object N

****** NOTES

*** 把 bǎ (OC:praaʔ MC:pɣɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-1a8a5430-9355-412e-92f2-fef926c60df6
:Char+: 把(64,4/7) 
:GY_IDS+: uuid-f279a2af-5eea-4f8a-b4aa-90d1be3d7b50
:PY+: bǎ     
:OC+: praaʔ     
:MC+: pɣɛ     
:END: 
**** V [[tls:syn-func::#uuid-113eed72-b938-441f-8478-72121ec7c111][vtoN1.adVtoN2]] {[[tls:sem-feat::#uuid-fe16de41-8940-4993-820c-31205850fa62][N1=concrete]]} / object marker in the disposal form
:PROPERTIES:
:CUSTOM_ID: uuid-6c817aa6-561a-484e-ba59-e16971b745e9
:END:
****** DEFINITION

object marker in the disposal form

****** NOTES

*** 持 chí (OC:ɡrlɯ MC:ɖɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-b61d7c51-ce3b-4306-a8f4-822ad03f371f
:Char+: 持(64,6/9) 
:GY_IDS+: uuid-35496ae0-38af-446e-afca-6b472a46c411
:PY+: chí     
:OC+: ɡrlɯ     
:MC+: ɖɨ     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004C
 - [[cite:ANDERL-2004C][Anderl(2004), Studies in the Language of Zu-tang Ji 祖堂集]], p.280-283


Recently a number of less known COV.DISP have come into focus in the study of the origin of the disposal form. Zhu Guanming has analyzed a number of Buddhist translations and found already early occurrences of chi3 持 used in the function of the earlier yi3 以 (COV.DISP).814 In the second century Yi2-ri4 mo2-ni2-ba3o ji1ng 遺日摩尼寶經 he found the following sentence:

582) Yi2-ri4 mo2-ni2-ba3o ji1ng 遺日摩尼寶經, T.12/350: 190a

一者持法施與人。

yi1-zhe3 chi2 fa3 shi1 yu3 re2n

NUMone/PART/COV.DISP/dharma/bestow on/give/person

As for the first (or: firstly) [he] bestowed the dharma on people.



In the example above chi2 is used with an abstract object which is an indication that it is already grammaticalized to a certain degree. Another indication is that it is used identical to yi3 以 (COV.DISP) and appears with VTT{give}. In the following example the coverbal object is N.CONCR:

583) She1ng ji1ng 生經, T.3/154: 88a

即持此寶與諸兄弟。

ji2 chi2 ci3 ba3o yu3 zhu1 xio1ng-di4

ADVthen/COV.DISP/treasure/give/QUANTall/elder brother-younger brother

[He] then gave this treasure to the brothers.815



Zhu also found an example with VTT{make into}, the first object is concrete and the second abstract:

584) Yi2-ri4 mo2-ni2-ba3o ji1ng 遺日摩尼寶經, T.12/350: 192a

譬如持灰作城，持無常作有常。

pi4-ru2 chi2 hui1 zuo4 che2ng chi2 wu2-cha2ng zuo4 yo3u-cha2ng

exemplify-be like/COV.DISP/ash/make into/city/COV.DISP/not have-permanence/make into/have-permanence

This is like making ashes into a city and turning impermanence into permanence.



Zhu found that most constructions with chi2 are of the type where the main verb is a VTT, appearing in the following pattern:

 chi2 持 (COV.DISP) + OBJ.DIR + V + OBJ.INDIR816

The VTT has the semantic contents V{give}; V{make into}; V{transport}; V{speak} (of the last type there is only one example).



Examples of the disposal in its 'narrow sense' (xia2 yi4 狹義) amount only to six.817 [[fn.817 In this pattern there are other elements than an indirect object following the verb, e.g. a complement. 譬如樹萌卻雨，菩薩如是，持極大慈雨於經道。(Yi2-ri4 mo2-ni2-ba3o ji1ng 遺日摩尼寶經, T.12/350: 190c). In this sentence the main VP consists of a verb and COV.LOC phrase ('...the Bodhisattva is like this and he expounds the uttermost kindness in the s$utras.' Is there an instrumental interpretation possible '..with uttermost kindness...')?; 當持是經典為諸沙門一切說之。(Ta4i-zi3 xu1 da4 nou ji1ng 太子須大M經, T.3/171: 424a). In this example the main VP consists of a coverbal phrase 'for the sake of all monks' and an adverb 'completely' and a resumptive object pronoun zhi1 之 which is identical to the object of chi2 持 ('this s$utra': 'at that time he expounded this s$utra in its entirety to all the monks.' 各持已女將來，奉上于淨飯王。(FOBEN, T.3/190: 692b); 'each brought along his own woman (daughter?) and presented her to King Ji4ngfa4n.' In this example the verb is complemented by la2i, a complement of direction.]] 

Zhu notes that in the texts dating from the eastern Han, chi2 appears mainly with V{give} and V{make into}. During the Eastern Jin there are also some examples with V{transport}.818 After the Eastern Han the main VP got increasingly complex and there are also more examples of the 'narrow' form. However, the frequency of the construction does not seem to have increased significantly.819 Zhu compared his findings with texts composed in LC and non-Buddhist semi-vernacular texts and found that chi2 as COV.DISP is virtually absent in those texts.820 However, in popular songs and poetry (as e.g. yue4-fu3 樂府) he found more examples than in LC literature. This led Zhu to the conclusion that chi2 is a grammatic marker of the colloquial language which began to surface during the Eastern Han in Buddhist translations. It was never completely grammaticalized into a COV.DISP since it was gradually replaced by new markers like jia1ng 將 and ba3 把. By Tang times chi2 had nearly completely disappeared in this function. In accordance with the functions of yi3 以, chi2 持 (COV.INSTR) could also function as an instrumental coverb.821 [[fn.821: E.g. 當持佛法藥愈人病。(Yi2-ri4 mo2-ni2-ba3o ji1ng 遺日摩尼寶經, T.12/350: 192a, cited in Zhu Guanming 2001: 4). 'One should cure the sicknesses of people with the Buddha-dharma.' On the relation between those two functions see also Mei Zulin 1990, Sun Xixin 1992: 351, Wu Fuxiang: 1996: 441. That is also an extension of the meanings as main verbs: 'grasp/hold (something) > grasp/hold and use something' (V{hold/grasp} > COV.INSTR > COV.DISP).]] 



[TABLE...]



In ZTJ there are a few examples with chi2 持 (COV.DISP). The majority of these examples are based on s$utra citations or earlier sources.

585) ZTJ 1.013 (based on the FOBEN)822

思惟是已， After having thought this,

則持國事付諸大臣， 

ze2 chi2 guo2 shi4 fu4 zhu1 da4 che2n

CONJthen/COV.DISP/state/matter/hand over to/QUANTall/great/official

he entrusted all matters of the state to the high officials

王乃入山修道； and he then went into the mountains in order to practice the Way (i.e. Buddhism);



In the following example the main verb is a V{speack}, ju3 舉 偆ring up (verbally) > cite':

586) ZTJ 1.152; WU: 91

侍者持此偈舉似師。 The attendant cited these verses to the master.823



The next example is probably based on BLZ: The object of COV chi2 consists of two NP in marked coordination:

587) ZTJ 1.059; WU: 35

如是展轉， Like this it spread (i.e. was passed on continuously)

乃至於我。 until it reached me.

我持此法並僧伽梨衣囑付於汝，

wo3 chi2 ci3 fa3 bi4ng se1ng qie2-li2 yi1 zhu3-fu4 yu2 ru3

NPRO1SG/COV.DISP/NPRO.DEMthis/dharma/CONJand/monk/TERMskr/garment/entrust to-hand over/PREP.OBJ.INDIR/NPRO2SG

I entrust this dharma and the monk's robe to you,

汝當護持， you should protect it well

無令斷絕。 and do not let it be disrupted.

***** MEI ZULIN 1990
 - [[cite:MEI-ZULIN-1990][Méi 梅(), 唐宋處置式來源 Táng Sòng chùzhìshì de láiyuán [The Origin of the Disposal Form of the Táng and Sòng Dynasties] 中國語文 Zhongguo yuwen]]
***** SUN XIXIN 1992
 - [[cite:SUN-XIXIN-1992][Sūn 孫(1992), 漢語歷史語法要略 Hànyǔ lìshǐ yǔfǎ yào lüè An Outline of a Historical Grammar of Chinese]], p.351

***** WU FUXIANG 1996
 - [[cite:WU-FUXIANG-1996][Wú 吳(1996), 敦煌變文語法研究 Dūnhuáng biànwén yǔfǎ yānjiū A Study of the Grammar of the Duānhuáng Transformation Texts]], p.441

***** ZHU GUANMING 2001
 - [[cite:ZHU-GUANMING-2001][Zhū 朱(2001), 中古譯經中的‘持’字處置式 Zhōnggǔ yìjīng zhōng de 'chí' zì chùzhìshì [The Disposal Form chí in Middle Chinese Sutra Translations] 第二屆中古漢語學術研討論 Dìèr jiè zhōnggǔ hànyǔ xuéshù yántàohuì]]
***** ZHU GUANMING 2002
 - [[cite:ZHU-GUANMING-2002][Zhū 朱(), 中古譯經中的‘持’字處置式 Zhōnggǔ yìjīng zhōng de 'chí' zì chùzhìshì [The Disposal Form chí in Middle Chinese Sutra Translations] 漢語史學報 Hanyushi xuebao]]
**** V [[tls:syn-func::#uuid-18044d90-be6f-41c1-a339-ba079218aa31][vt(+N.)adVt]] / take the object and V it
:PROPERTIES:
:CUSTOM_ID: uuid-0c033fa6-f697-4c69-bf55-2c52fc3b4bb9
:END:
****** DEFINITION

take the object and V it

****** NOTES

****  [[tls:syn-func::#uuid-a68c06ff-cdc6-4130-832a-095884df6673][vtoNab.adVtoN]] {[[tls:sem-feat::#uuid-28ffcaa2-14eb-4c9b-a878-1d9e8bf3a432][N=abstract]]} / object marker, precursor of 將 and 把 (used in sutra translations (the earliest dating from 2nd cent....
:PROPERTIES:
:CUSTOM_ID: uuid-228a5542-e1b1-4ba1-976a-c7febbd24501
:END:
****** DEFINITION

object marker, precursor of 將 and 把 (used in sutra translations (the earliest dating from 2nd cent.) and Buddhist texts (see especially FOBEN XINGJI JING); for examples see SOURCES)

****** NOTES

**** V [[tls:syn-func::#uuid-113eed72-b938-441f-8478-72121ec7c111][vtoN1.adVtoN2]] / object marker, precursor of 將 and 把 (used in sutra translations (the earliest dating from 2nd cent....
:PROPERTIES:
:CUSTOM_ID: uuid-f351f683-9acc-44f8-b690-68755ad6bf5b
:END:
****** DEFINITION

object marker, precursor of 將 and 把 (used in sutra translations (the earliest dating from 2nd cent.) and Buddhist texts (see especially FOBEN XINGJI JING); for examples see SOURCES) 

FOBEN XINGJI JING, T.3/190: 661c15 是故我今持此摩尼置於塔上。

****** NOTES

*** 捉 zhuō (OC:tsrooɡ MC:ʈʂɣɔk )
:PROPERTIES:
:CUSTOM_ID: uuid-7b63c99c-5146-4076-b785-252cc5bcd2e4
:Char+: 捉(64,7/10) 
:GY_IDS+: uuid-52f8d7e2-fde7-45e6-b0c5-cf8d319b0b3e
:PY+: zhuō     
:OC+: tsrooɡ     
:MC+: ʈʂɣɔk     
:END: 
**** SOURCE REFERENCES
***** ZHU GUANMING 2001
 - [[cite:ZHU-GUANMING-2001][Zhū 朱(2001), 中古譯經中的‘持’字處置式 Zhōnggǔ yìjīng zhōng de 'chí' zì chùzhìshì [The Disposal Form chí in Middle Chinese Sutra Translations] 第二屆中古漢語學術研討論 Dìèr jiè zhōnggǔ hànyǔ xuéshù yántàohuì]], p.6

**** V [[tls:syn-func::#uuid-6c799c2c-5270-4aab-abd9-8b5253865818][vad.VtoN]] {[[tls:sem-feat::#uuid-40885358-4ad0-489c-b609-df23830eca19][N=concrete]]} / early rare object marker used in certain sutra translations and some vernacular texts of the Tang (...
:PROPERTIES:
:CUSTOM_ID: uuid-24b7e316-031f-4e3d-8c20-058677185723
:END:
****** DEFINITION

early rare object marker used in certain sutra translations and some vernacular texts of the Tang (WANGFANZHI, BIANWEN)

****** NOTES

*** 於 yú (OC:qa MC:ʔi̯ɤ )
:PROPERTIES:
:CUSTOM_ID: uuid-26861a42-8a3f-40f2-98b0-5f79da2e11df
:Char+: 於(70,4/8) 
:GY_IDS+: uuid-fb67b697-a7f5-4e27-8090-d90ec205fd5c
:PY+: yú     
:OC+: qa     
:MC+: ʔi̯ɤ     
:END: 
**** V [[tls:syn-func::#uuid-0fd422be-1422-4d55-8ec6-1446bc841e83][vt/0/oN.postVt]] / empty object marker used only as a filler to make quadrisyllabic or pentasyllabic lines as required.
:PROPERTIES:
:CUSTOM_ID: uuid-df5fcbdd-4746-46b2-8a19-3e7ad4722ed3
:END:
****** DEFINITION

empty object marker used only as a filler to make quadrisyllabic or pentasyllabic lines as required.

****** NOTES

*** 是 shì (OC:ɡljeʔ MC:dʑiɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-5f0def8c-e312-4a21-8452-f7a7ddcc757d
:Char+: 是(72,5/9) 
:GY_IDS+: uuid-4342b9fe-7e09-40cb-ad1a-fbf479505d5f
:PY+: shì     
:OC+: ɡljeʔ     
:MC+: dʑiɛ     
:END: 
**** N [[tls:syn-func::#uuid-5920aca6-2ca6-44a9-a64b-55b3c07b342d][npro+Vt.postN{OBJ}]] / this
:PROPERTIES:
:CUSTOM_ID: uuid-6fef2f46-597a-449e-8476-6ba92caa2ed2
:END:
****** DEFINITION

this

****** NOTES

*** 用 yòng (OC:k-loŋs MC:ji̯oŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-e0005837-f40f-4775-b485-3927ce1ee9c0
:Char+: 用(101,0/5) 
:GY_IDS+: uuid-2e64086a-bc0d-434c-8b75-076fa5837220
:PY+: yòng     
:OC+: k-loŋs     
:MC+: ji̯oŋ     
:END: 
**** V [[tls:syn-func::#uuid-18044d90-be6f-41c1-a339-ba079218aa31][vt(+N.)adVt]] / using N to V it > object marker
:PROPERTIES:
:CUSTOM_ID: uuid-580557f0-fc54-424e-b10d-491c6a264aa1
:END:
****** DEFINITION

using N to V it > object marker

****** NOTES

**** V [[tls:syn-func::#uuid-25270f92-78eb-4334-a1b2-61ee030801df][vtoN.adVt]] / using N to V it > object marker
:PROPERTIES:
:CUSTOM_ID: uuid-27cee886-7a97-482b-8408-30839ebd0731
:END:
****** DEFINITION

using N to V it > object marker

****** NOTES

*** 而 ér (OC:njɯ MC:ȵɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-72aea558-e23c-46d2-92bf-228711c92810
:Char+: 而(126,0/6) 
:GY_IDS+: uuid-d4f6516f-ad7d-4a23-a222-ee0e2b5082e8
:PY+: ér     
:OC+: njɯ     
:MC+: ȵɨ     
:END: 
**** P [[tls:syn-func::#uuid-9a498439-e165-4ae4-8251-4af844bacb11][p+Vt1.postVt2(oN)]] {[[tls:sem-feat::#uuid-ae23bc41-061a-4571-ad66-3b727bf9b82b][Vt1=object of Vt2]]} / verbal-object marker 得而見"get to see"
:PROPERTIES:
:CUSTOM_ID: uuid-24646e16-c26a-48fc-b280-1f6fa8d40d33
:WARRING-STATES-CURRENCY: 3
:END:
****** DEFINITION

verbal-object marker 得而見"get to see"

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
