# -*- mode: mandoku-tls-view -*-
#+TITLE: RIGHT
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= RIGHT
:PROPERTIES:
:CUSTOM_ID: uuid-25ec2d38-3cb5-4ee1-9aef-868862465d21
:TR_ZH: 權利
:END:
** DEFINITION

What one DESERVES AND CAN DEMAND BECAUSE of LAW OR JUSTICE.

** NOTES

*** Old Chinese Criteria
Classical Latin distinguishes between

LEX "written law", and

IUS "1. "principles of justice as (partly) embodied in laws"; 2. "right, privilege, just claim". A law may confer legal rights. Rights without a basis in written law are natural rights.

FAS "divine right, divine justice".

It is this second meaning of IUS that is relevant under our synonym group RIGHT. Thus in ancient Rome we have iura populi "the legal rights of the people", ius civitatis "rights of citizenship", ius libertatis "freedom rights", iura muliebria "women's rights". Crucial for the history of property was the ius retinendi "the right to continue to have what one owns". There also was the important ius suffragii "the right to vote in an assembly". In later times, there was, for example, the notorious ius primae noctis "the right to spend the first night with the newly-wed bride".

The IUS of a person is his or her legal standing with respect to specific rights. Thus one can have or not have IUS "legal standing" in Latin, and one can be sui iuris "of legally independent status, legally free to act".

According to Hobbes, Leviatan p. 86, the lex imposes obligations whereas the the ius conveys liberties.

A IUS could be moribus constitutum "customary", or statutory.

One category of rights that is of crucial importance is that of ius nudum "naked rights, i.e. rights without a remedy, rights which one has but which are unenforcable".

Among enforcable rights a crucial distinction is between real rights which were enforced by actio in rem "action concerning the matter at issue" and personal rights which were enforcable by actio in personam "measures taken regarding the person (whose duty it is to fulfill the right)".

Note that in Latin, as in modern Chinese, the word for power, POTESTAS, can also be used to refer to a rightful power, i.e. a right to do something.



In English, the distinction between LAW and RIGHT is discussed in Owen Barfield's classic History in English Words, ed. 1985 p. 53: "Thus our useful distinction between law and right was once geographical rather than semantic, the two words covering roughly the eastern and the western halves of England."

Jeremy Bentham explained rights as originating from duties imposed by a legislator on a society with the intention of benefiting a persons or groups of persons. This definition or explanation is useful, but clearly too broad.

H.L.A Hart explains a right as a legally protected choice to decide on the performance of a correlative duty by whoever he has a claim on.

Philosophers of language have claimed that rights are best explained as speech acts involving a demand presupposed to be justified by a owner of a right to the effect that his right be effectuated or acted according to by whover is presupposed to have the duty to guarantee this right.

Claim-rights of A involve legislation obliging another party B to satisfy these rights.

Liberty-rights of A involve the absence of the right in another party B to prevent A in the exercise of that right.

Any statement that "someone A has a right to X" must probably te taken to logically imply that "someone B has a duty concerning X vis-a-vis A".

There are active rights for A to do something, and passive rights for R to have done something to him. The passive rights have a clearer link to specific duty or obligation for someone B to do to A what A has a right to have done to him.

C. Arnold (Analyses or right) argues that the notions of rights and duties are mutually reducible to each other.

Compare the notions of LEFT and RIGHT. A is to the LEFT of B exactly when B is to the RIGHT of A. Thus essentially we do not need both concepts and we can make do with either one of them. Similarly for the concepts of rights and duties/obligations.

If one considers non-persons like animals and even landscapes as possessors of rights, then there are rights which do not in any way involve or imply underlying speech acts of agents.

*** Modern Chinese Criteria
權利

權力

** POINTERS
*** TAXONOMY
 - [[tls:concept:HUMAN RIGHT][HUMAN RIGHT]]

*** SEE ALSO
 - [[tls:concept:LAW][LAW]]
 - [[tls:concept:NATURAL LAW][NATURAL LAW]]

*** KIND OF
 - [[tls:concept:DESERVE][DESERVE]]

** SOURCE REFERENCES
*** BARFIELD 1953
 - [[cite:BARFIELD-1953][Barfield(1953), History in English Words]], p.53

*** CASSIN 2004
 - [[cite:CASSIN-2004][Cassin(2004), Vocabulaire européen des philosophies. Dictionnaire des intraduisibles]], p.700

*** DWORKIN 1977
 - [[cite:DWORKIN-1977][Dworkin(1977), Taking Rights Seriously]]
*** HOHFELD 1919
 - [[cite:HOHFELD-1919][Hohfeld(1964), Fundamental Legal Conceptions]]
*** RITTER 1971-2007
 - [[cite:RITTER-1971-2007][Ritter Gruender Gabriel(1971-2007), Historisches Woerterbuch der Philosophie]], p.8.230

*** MELDON 1959
 - [[cite:MELDON-1959][Meldon(), Rights and Right Conduct]]
*** MITTELSTRASS 1996
 - [[cite:MITTELSTRASS-1996][Mittelstrass(1996), Enzyklopaedie Philosophie und Wissenschaftstheorie]]
*** PECK 1965
 - [[cite:PECK-1965][Peck(1965), Harper's Dictionary of Classical Literature and Antiquities]], p.901

*** REY 2005
 - [[cite:REY-2005][Rey(2005), Dictionnaire culturel en langue francaise]], p.2.209

*** RITTER 1971-2007
 - [[cite:RITTER-1971-2007][Ritter Gruender Gabriel(1971-2007), Historisches Woerterbuch der Philosophie]], p.8.233
 (RECHT, POSITIVES)
*** STOLJAR 1984
 - [[cite:STOLJAR-1984][Stoljar(1984), An Analysis of Rights]]
*** WALDRON 1984
 - [[cite:WALDRON-1984][Waldron(1984), Theories of Rights]]
*** ZHANG DAINIAN 2002
 - [[cite:ZHANG-DAINIAN-2002][Zhang  Ryden(2002), Key Concepts in Chinese Philosophy]], p.364

*** BORCHERT 2005
 - [[cite:BORCHERT-2005][Borchert(2005), The Encyclopedia of Philosophy]]
*** GIRARD 1769
 - [[cite:GIRARD-1769][Girard Beauzée(1769), SYNONYMES FRANÇOIS, LEURS DIFFÉRENTES SIGNIFICATIONS, ET LE CHOIX QU'IL EN FAUT FAIRE Pour parler avec justesse]], p.1.375.329
 (PREROGATIVE. PRIVILEGE)
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
