# -*- mode: mandoku-tls-view -*-
#+TITLE: RUMOUR
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= RUMOUR
:PROPERTIES:
:CUSTOM_ID: uuid-a98104c1-d140-4140-b7a2-b1accc813ecd
:SYNONYM+:  GOSSIP
:SYNONYM+:  TITTLE-TATTLE
:SYNONYM+:  WHISPERS
:SYNONYM+:  CANARDS
:SYNONYM+:  TIDBITS
:SYNONYM+:  SCANDAL
:SYNONYM+:  HEARSAY
:SYNONYM+:  INFORMAL DIRT
:SYNONYM+:  BUZZ
:SYNONYM+:  SCUTTLEBUTT
:TR_ZH: 謠言
:END:
** DEFINITION

COMMON BELIEF that is NOT BASED on REALITY.

** NOTES

*** Modern Chinese Criteria
謠言 is the current modern word for a rumour.

謠傳 focusses on the oral transmission of rumours.

妄言 focusses on the misleadingness of rumours.

無稽之談 (prov) focusses on the baselessness of rumours.

黃色新聞 (prov) refers to lurid published rumours.

桃色新聞 (prov) refers to lurid published rumours.

謠 (cl)

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** SOURCE REFERENCES
*** COMENIUS 1665
 - [[cite:COMENIUS-1665][Komensky(1966), De Rerum Humanarum Emendatione]], p.637


RUMOR est publice sine authore certo ortus de re qvapiam sermo. Conc. 1. ut publice fiat. 2. incerto authore veniat. 3. certi nihil habeat.

*** DOEDERLEIN 1840
 - [[cite:DOEDERLEIN-1840][Doederlein(1840), Lateinische Synonyme und Etymologien]]

RUMOUR

rumor "report, word-of-mouth" is the uncertain, often clandestine dissemination of hidden facts, and this is typically of interest only by its novelty, is an object of curiosity, and passes away with the generation in which it sprung up.

fama "information" is the open and public dissemination of some facts, and the fama is typically of interest through its importance, and will often be handed down to posterity as permanent knowledge.

*** THEOPHRASTUS 1960
 - [[cite:THEOPHRASTUS-1960][Steinmetz(1960), Theophrast, Charaktere]], p.no. 8

*** BARNARD AND SPENCER 2002
 - [[cite:BARNARD-AND-SPENCER-2002][Barnard Spencer(2002), Encyclopedia of Social and Cultural Anthropology]] (GOSSIP)
** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
