# -*- mode: mandoku-tls-view -*-
#+TITLE: SILKWORM
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= SILKWORM
:PROPERTIES:
:CUSTOM_ID: uuid-bfc00057-59ea-43a9-b864-9108cc565160
:TR_ZH: 蠶
:END:
** DEFINITION

WORM that is REARED FOR PRODUCING SILK.

** NOTES

*** Huang Jingui
HUANG JINGUI 2006

*** Modern Chinese Criteria
蠶

家蠶

桑蠶

蠶寶寶

蠶蟻

蟻蠶

烏娘

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 蛹 yǒng (OC:k-loŋʔ MC:ji̯oŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-cf477643-bc9f-4774-8a59-7124f05f94e6
:Char+: 蛹(142,7/13) 
:GY_IDS+: uuid-7cf7a65c-3b3c-4cf2-b8f4-a67d1680a780
:PY+: yǒng     
:OC+: k-loŋʔ     
:MC+: ji̯oŋ     
:END: 
**** N [[tls:syn-func::#uuid-8717712d-14a4-4ae2-be7a-6e18e61d929b][n]] / silkworm chrysalis
:PROPERTIES:
:CUSTOM_ID: uuid-9035f353-d039-4d1e-8d2d-7f8c29d15195
:WARRING-STATES-CURRENCY: 2
:END:
****** DEFINITION

silkworm chrysalis

****** NOTES

*** 蠶 cán (OC:sɡɯɯm MC:dzəm )
:PROPERTIES:
:CUSTOM_ID: uuid-f026e01d-ae4d-41b2-b6ad-605ccbaa60f8
:Char+: 蠶(142,18/24) 
:GY_IDS+: uuid-23b97126-4fa7-4ad5-a628-f6c819a1a66e
:PY+: cán     
:OC+: sɡɯɯm     
:MC+: dzəm     
:END: 
**** N [[tls:syn-func::#uuid-8717712d-14a4-4ae2-be7a-6e18e61d929b][n]] / silkworm
:PROPERTIES:
:CUSTOM_ID: uuid-6e7854e0-5fc9-4d5e-b181-6471e6db6ff4
:WARRING-STATES-CURRENCY: 4
:END:
****** DEFINITION

silkworm

****** NOTES

**** N [[tls:syn-func::#uuid-a0671d23-390b-4f93-8886-40cacfb6c9d7][nadV{PASS}]] / be V-ed as if by a silkworm
:PROPERTIES:
:CUSTOM_ID: uuid-ce916bd5-4e90-4987-b21f-3008eb6ff96c
:END:
****** DEFINITION

be V-ed as if by a silkworm

****** NOTES

**** N [[tls:syn-func::#uuid-91666c59-4a69-460f-8cd3-9ddbff370ae5][nadV]] {[[tls:sem-feat::#uuid-bedce81f-bac5-4537-8e1f-191c7ff90bdb][analogy]]} / (eat away territory) in silkworm-fashion
:PROPERTIES:
:CUSTOM_ID: uuid-a9e78743-4c05-4140-858f-adda8b31ef50
:END:
****** DEFINITION

(eat away territory) in silkworm-fashion

****** NOTES

******* Nuance
This expression nearly exclusively modifies shì and often appears together with the adv. shāo 稍 "gradually": "gradually eat away territory in silkworm -fashion". It is interesting that this 蠶 in all checked examples refers to the state of Qín and seems to have become the stereotyped description of Qín's power-politics in gaining superiority at the end of the Warring State period.

******* Examples
SJ 6/0276 tr. Watson 1993, p.74

 自繆公以來， From the time of Duke Mu on,

 稍蠶食諸侯， it gradually ate away at the domains of the other feudal rulers

 竟成始皇。 until the process was finally completed by the First Emperor.



SJ 86/2528#2; tr. Watson 1993, p.168

 其後秦日出兵山東 Meanwhile, Qin day by day dispatched more troops east of the mountains,

... 以伐齊、楚、三晉， attacking Qi, Chu, Hann, Wei, and Zhao

 稍蠶食諸侯， and gradually eating away at the lands of the other feudal lords,

 且至於燕， until it became obvious that Yan 哀 turn would be next.



SJ 87/2541-2542; tr. Watson 1993, Qin, p.182

 昭王得范睢， King Zhaoxiang obtained the services of Fan Ju,

 廢穰侯， dismissed the marquis of Rang,

 逐華陽， and expelled Lord Huayang,

 彊公室， strengthening the ruling house,

 杜私門， closing the door to private privilege,

 蠶食諸侯， eating away silkworm-fashion at the lands of the other feudal lords,

 使秦成帝業。 and making it possible for Qin to set up an imperial regime.



SJ 16/0759#2

 秦起襄公，章於文、繆，獻、孝之後，稍以蠶食六國，百有餘載，至始皇乃能并冠帶之倫。 



SJ 43/1825

 對曰：「夫秦蠶食韓氏地，中絕不令相通，固自以為坐而受上黨之地也。 



SJ 69/2247

 秦之攻韓、魏也，無有名山大川之限，稍蠶食之，傅國都而止。 



SJ 72/2325-2326

 秦，貪戾之國也，而毋親。蠶食魏氏，又盡晉國，戰勝暴子，割八縣，地未畢入，兵復出矣。 



SJ 112/2953-2954

 昔秦皇帝任戰勝之威，蠶食天下，并吞戰國，海內為一，功齊三代。

**** V [[tls:syn-func::#uuid-fed035db-e7bd-4d23-bd05-9698b26e38f9][vadN]] / related to sericulture
:PROPERTIES:
:CUSTOM_ID: uuid-a6593b0f-c3b9-4b51-b923-5b7cde939139
:END:
****** DEFINITION

related to sericulture

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
