# -*- mode: mandoku-tls-view -*-
#+TITLE: TRIBE
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= TRIBE
:PROPERTIES:
:CUSTOM_ID: uuid-760112aa-ba84-446d-ae9d-a80b5e6a075e
:TR_ZH: 部落
:END:
** DEFINITION

GROUP of HUMANS which HAS COMMON ANCESTORS AND a COMMON CULTURE.

** NOTES

*** Huang Jingui
HUANG JINGUI 2006

*** Modern Chinese Criteria
部落 is the current modern word for a tribe.

人種 is refers to the concept of an ethnicity.

民族 refers to a nation.

種族 is a scientific word for an ethnic group.

種

族

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** SOURCE REFERENCES
*** BUCK 1988
 - [[cite:BUCK-1988][BUCK(1988), A Dictionary of Selected Synonyms in the Principal Indo-European Languages]], p.19.23

*** DOEDERLEIN 1840
 - [[cite:DOEDERLEIN-1840][Doederlein(1840), Lateinische Synonyme und Etymologien]]

RACE

stirps "root" can refer to a common biological and human kind.

genus refers to a natural race, and it consists of a species of individuals which by their common properties belong to one and the same class of beings.

gens refers to a politically organised race consisting of families whom the founder of states has united into a community or into a complex family.

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
