# -*- mode: mandoku-tls-view -*-
#+TITLE: TRY
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= TRY
:PROPERTIES:
:CUSTOM_ID: uuid-7d16f180-72e5-4880-b20c-dc135e68166c
:SYNONYM+:  ATTEMPT
:SYNONYM+:  ENDEAVOR
:SYNONYM+:  VENTURE
:SYNONYM+:  MAKE AN EFFORT
:SYNONYM+:  EXERT ONESELF
:SYNONYM+:  STRIVE
:SYNONYM+:  DO ONE'S BEST
:SYNONYM+:  DO ONE'S UTMOST
:SYNONYM+:  MOVE HEAVEN AND EARTH
:SYNONYM+:  UNDERTAKE
:SYNONYM+:  AIM
:SYNONYM+:  TAKE IT UPON ONESELF
:SYNONYM+:  INFORMAL HAVE A GO
:SYNONYM+:  GIVE IT ONE'S BEST SHOT
:SYNONYM+:  BEND OVER BACKWARDS
:SYNONYM+:  BUST A GUT
:SYNONYM+:  DO ONE'S DAMNEDEST
:SYNONYM+:  PULL OUT ALL THE STOPS
:SYNONYM+:  GO ALL OUT
:SYNONYM+:  KNOCK ONESELF OUT
:SYNONYM+:  FORMAL ESSAY
:TR_ZH: 嘗試
:TR_OCH: 試
:END:
** DEFINITION

ACT, BUT DOUBT WHETHER one WILL be SUCCESSFUL ACTING.

** NOTES

*** Old Chinese Criteria
1. The current general word for trying is shì 試, but the word generally refers to brief attempts rather than a concerted lasting campaign.

2. Cháng 嘗 "make an attempt at" typically takes nominal objects, and the attempt referred to is typically of a transient kind.

3. Qiú 求 refers to a sustained attempt to achieve a result.

NB: There are apparently no nominal uses of any of these words. It will be interesting to find a case of a nominalised "attempt".

*** Modern Chinese Criteria
試

試試

嘗試

試試看

努力

試驗

試作

触球

設法

rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／

** POINTERS
*** TAXONOMY
 - [[tls:concept:EFFORT][EFFORT]]
 - [[tls:concept:FAIL][FAIL]]
 - [[tls:concept:FOR][FOR]]
 - [[tls:concept:HELP][HELP]]
 - [[tls:concept:INVESTIGATE][INVESTIGATE]]
 - [[tls:concept:LISTEN][LISTEN]]
 - [[tls:concept:LOOK][LOOK]]
 - [[tls:concept:SEEK][SEEK]]
 - [[tls:concept:STRIVE FOR][STRIVE FOR]]

*** ANTONYMY
 - [[tls:concept:INACTIVE][INACTIVE]]

*** SEE ALSO
 - [[tls:concept:STRIVE FOR][STRIVE FOR]]

*** KIND OF
 - [[tls:concept:ACT][ACT]]

** SOURCE REFERENCES
*** APRESJAN 2004
 - [[cite:APRESJAN-2004][Apresjan(2004), Novyj objasnitel'nyj Slovar' Sinonimov Russkogo Jazyka]], p.905

*** BUCK 1988
 - [[cite:BUCK-1988][BUCK(1988), A Dictionary of Selected Synonyms in the Principal Indo-European Languages]], p.9.99

*** COMENIUS 1665
 - [[cite:COMENIUS-1665][Komensky(1966), De Rerum Humanarum Emendatione]], p.489


CONATUS est ad aliqvid efficiendum virium intensio. Reqv. 1. aliquid bonum, arduum tamen 2. qvod tamen superatu speratur possibile. 3. si vires intendantur.

Ax. 1. Failia conatu non egent.

2. Ubi nulla spes superandi, nullus conatus.

3. ardua sino conatu non superantur.

Opus qvo magis arduum, eo intensionem reqvirit majorem.

*** DOEDERLEIN 1840
 - [[cite:DOEDERLEIN-1840][Doederlein(1840), Lateinische Synonyme und Etymologien]]

TRY

tentare refers to making an experiment in order to form a judgment of something, from a desire of knowledge.

peiclitari refers to making an experiment with courage and contempt of the danger associated with the experiment.

experiri is merely to learn something by trying it out.

*** HANFEI TONGYI 2004
 - [[cite:HANFEI-TONGYI-2004][Zhao(2004), 韓非子同義詞研究]], p.148

*** LANGIUS 1631
 - [[cite:LANGIUS-1631][Langius(1631), Anthologia sive Florilegium rerum et materiarum selectarum]] (CONATUS)
*** MENGE
 - [[cite:MENGE][Menge Schoenberger(1978), Lateinische Synonymik]]
*** GIRARD 1769
 - [[cite:GIRARD-1769][Girard Beauzée(1769), SYNONYMES FRANÇOIS, LEURS DIFFÉRENTES SIGNIFICATIONS, ET LE CHOIX QU'IL EN FAUT FAIRE Pour parler avec justesse]], p.1.286.243
 (EXPERIENCE.ESSAI.EPREUVE)
*** FRANKE 1989
 - [[cite:FRANKE-1989][Franke Gipper Schwarz(1989), Bibliographisches Handbuch zur Sprachinhaltsforschung. Teil II. Systematischer Teil. B. Ordnung nach Sinnbezirken (mit einem alphabetischen Begriffsschluessel): Der Mensch und seine Welt im Spiegel der Sprachforschung]], p.59B

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 嘗 cháng (OC:djaŋ MC:dʑi̯ɐŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-cb9653f3-e09b-4264-9a6f-d0fd1bad7027
:Char+: 嘗(30,11/14) 
:GY_IDS+: uuid-599114b6-a3a5-43cd-910e-980cf9e48c59
:PY+: cháng     
:OC+: djaŋ     
:MC+: dʑi̯ɐŋ     
:END: 
**** V [[tls:syn-func::#uuid-09d661ae-604f-4650-8a7f-97c36f14acf3][vt(+V/0/)]] / try to do the contextually determinate thing
:PROPERTIES:
:CUSTOM_ID: uuid-76eb6c86-f298-4fb6-8324-2576d1c25635
:END:
****** DEFINITION

try to do the contextually determinate thing

****** NOTES

**** V [[tls:syn-func::#uuid-fbfb2371-2537-4a99-a876-41b15ec2463c][vtoN]] / make an attempt at, give a try
:PROPERTIES:
:CUSTOM_ID: uuid-5d8553ae-ebf7-4060-bb19-92d352814ff6
:WARRING-STATES-CURRENCY: 3
:END:
****** DEFINITION

make an attempt at, give a try

****** NOTES

**** V [[tls:syn-func::#uuid-dd717b3f-0c98-4de8-bac6-2e4085805ef1][vt+V/0/]] / try to V
:PROPERTIES:
:CUSTOM_ID: uuid-449cc1be-6543-4e1a-b95b-28985d0c83f3
:END:
****** DEFINITION

try to V

****** NOTES

*** 求 qiú (OC:ɡu MC:gɨu )
:PROPERTIES:
:CUSTOM_ID: uuid-9063c6eb-51cb-43b8-9c1f-1cbb9dc82c4a
:Char+: 求(85,2/6) 
:GY_IDS+: uuid-f68bbc45-0deb-4d2f-bd88-bef660d91d75
:PY+: qiú     
:OC+: ɡu     
:MC+: gɨu     
:END: 
**** V [[tls:syn-func::#uuid-dd717b3f-0c98-4de8-bac6-2e4085805ef1][vt+V/0/]] / seek to, make every effort to V 求仙 "try to become an immortal" 求及
:PROPERTIES:
:CUSTOM_ID: uuid-e4400727-2de1-45ad-81d8-90b387240e37
:END:
****** DEFINITION

seek to, make every effort to V 求仙 "try to become an immortal" 求及

****** NOTES

******* Nuance
This takes verbal complements.

**** V [[tls:syn-func::#uuid-dd717b3f-0c98-4de8-bac6-2e4085805ef1][vt+V/0/]] {[[tls:sem-feat::#uuid-52f9b87c-5688-4b46-b992-a5fb0bf27fb9][copula]]} / try to become
:PROPERTIES:
:CUSTOM_ID: uuid-7a60b266-da11-4b58-87bf-d7e0e9cd809d
:WARRING-STATES-CURRENCY: 3
:END:
****** DEFINITION

try to become

****** NOTES

**** V [[tls:syn-func::#uuid-dd717b3f-0c98-4de8-bac6-2e4085805ef1][vt+V/0/]] {[[tls:sem-feat::#uuid-d99ae971-35b1-48eb-8a45-a21dde414945][V=passive]]} / try to be V-ed
:PROPERTIES:
:CUSTOM_ID: uuid-0b0b1b98-4729-401a-81b3-2ff4ca6df700
:END:
****** DEFINITION

try to be V-ed

****** NOTES

*** 看 kàn (OC:khaans MC:khɑn )
:PROPERTIES:
:CUSTOM_ID: uuid-fa16fa7f-6dd1-42a4-a02e-700e7586c0b5
:Char+: 看(109,4/9) 
:GY_IDS+: uuid-27bd433a-421e-4fd1-9d12-ac269819bf05
:PY+: kàn     
:OC+: khaans     
:MC+: khɑn     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004B
 - [[cite:ANDERL-2004B][Anderl(2004), Studies in the Language of Zǔtáng jí 祖堂集]], p.500-503


2.3.2.3.2 SENTENCE FINAL ka4n 看



As in the case of sentence final ha3o, I do not regard ka4n as fully grammaticalized. By contrast to the most of the other sentence finals, ka4n derives from a full verb: 'to look > to look and see what happens1344 > to try out'. The usage as sentence final originated during the Six Dynasties period but examples prior to the Tang/Five Dynasties periods are very scarce.1345

 In Bianwen there are six examples of sentence final ka4n1346 and Song Yinsheng counts 38 examples in ZTJ. 37 of the examples appear in imperative sentences/requests and ka4n indicates that the speaker wants the addressee to try to perform a certain action. 35 of the verbs co-occurring with ka4n are monosyllabic and there are 3 example where ka4n appears with disyllabic verbs.1347 In Bianwen all verbs occurring with ka4n convey a speech act. However, in ZTJ some of the verbs belong to other semantic categories. In Bianwen all occurrences of SF ka4n are in imperative sentences whereas in ZTJ there are also a few examples where the person who is trying out an action is the speaker himself. Song Yinsheng interpretes these data that there was a development of this function of ka4n inbetween the period of Bianwen and ZTJ. After the Song the usage of sentence final ka4n became even more frequent. However, the function and usage of ka4n in these early texts does not seem to be identical with its usage in Modern Mandarin.



Ka4n is most frequent with verbs expressing an act of speech (V{speak} +... + ka4n 看):

1203) ZTJ 5.142,08; WU: 453

“某甲有一句子， "I have a phrase,

不借諸聖口。” which does not borrow from the the words of the sages."

師云： The master said:

“汝試道看。” 

ru3 shi4 da4o ka4n 

NPRO2SG/VTVtry to/speak/SF.ATTEMPT

"Try to tell [me this sentence]!"

洞山云： Do4ngsha1n said:

“不是某甲，” "It is not me."



1204) ZTJ 5.096; WU: 426

其僧云： The monk said:

“問佛法不相當， "Asking for the Buddha-dharma is not appropriate,

所以卻歸來。” therefore I will return."

雪峰云： Xue3fe1ng said:

“你舉看。” 

ni3 ju3 ka4n 

NPRO1SG/bring up > cite orally/SF.ATTEMPT

"Try to bring up (i.e. cite a case for discussion)."



Ka4n with other action verbs (V +... + ka4n 看):



zhuo2 啄 (VT) +... + ka4n 看 (SF.ATTEMPT) 'try to peck'



1205) ZTJ 4.133; WU: 364

“這個老漢行腳時， "At the time when I, this old fellow here, was practicing as itinerant monk

或遇著草根下有個老漢， I happened to meet an old fellow (i.e. myself) below the grass root, [?]

便從頂o上啄一下錐看。”

bia4n co2ng di3ng-ning sha4ng zhuo2 yi1 xia4 zhui1 ka4n 

then I tried to peck him once with an awl on his front head."



che2ng 呈 (VT) +... + ka4n 看 (SF.ATTEMPT): 'try to present (to a superior)'



1206) ZTJ 4.090; WU: 339

師曰： The master said:

“還將得此珠來也無？” "Did you bring this pearl along?"

對云： [The student] answered:

“將得來。” "I brough [it] along."

師云： The master said:

“若將得來， "If you brought it along

則呈似老僧看。” 

ze2 che2ng si4 la3o se1ng ka4n

then/present/PREP.OBJ.INDIR/NPRO1SG.SEMIold monk/SF.ATTEMPT

then try to present it to me."



In the example below the attempt is marked by shi4 試 (VTV) 'try to VERB' and sentence final ka4n 看 (multiple marking):



shi4 試 (VTVtry to) + VP +... + ka4n 看 (SF.ATTEMPT):



1207) ZTJ 4.084; WU: 334

僧問： The monk asked:

“何物大於天地？” "Which being (or: thing) is greater than heaven?

師云： The master said:

“無人識得伊。” "Nobody can know him (it)."

僧云： The monk said:

“還可彫啄也無？” "Can it be carved?" 

師云： The master said:

“你試下手看。” 

ni3 shi4 xia4 sho3u ka4n 

NPRO2SG/VTVtry to/lower-hand>set about/SF.ATTEMPT

"Try to set about."1348



fe1n 分 (VT) +... + ka4n 看 (SF.ATTEMPT): 'to divide; to make a distinction':



1208) ZTJ 4.026; WU: 300

師云： The master said:

“你試分看。” 

ni3 shi4 fe1n ka4n 

NPRO2SG/VTVtry to/devide/SF.ATTEMPT

"Try to make a division."



In the following example ka4n appears with a verb of perception, V{perceive}.



ti1ng 聽 (VT) +... + ka4n 看 (SF.ATTEMPT) 'try to listen to':



1209) ZTJ 4.019; WU: 295

“本自圓成， "The original self is perfect

凝然湛寂。 congealed in tranquility.

和尚對聖人， When you, Preceptor, are confronted with a sage,

說個甚摩事？” what matter would you tell [him]?"

師云： The master said:

“汝更聽看。” "Try to listen to it further."



dua4n 斷 (VT) +... + ka4n 看 (SF.ATTEMPT) 'try to cut in half; to seperate'



1210) ZTJ 3.103; WU: 256

學曰： The student said:

“人王與法王， "The king of men and the king of the dharma,

相去幾何？” how far are they apart from each other (i.e. what is the difference between them)?"

師云： The master said:

“汝自斷看。” "Try yourself to divide [them]."

進云： [The student] added:

“學人斷不得。 "I cannot divide them.

卻請和尚斷。” However, I ask you to divide [them]."

***** CAI JINGHAO 1990A
 - [[cite:CAI-JINGHAO-1990A][Cái 蔡(), 重談語助詞‘看’的起源 Chóngtán yǔzhùcí kàn de qǐyuán [A Further Discussion of the origin of the Auxiliary Word 'kan'] 中國語文 Zhongguo yuwen]]
***** LI QUAN 1992
 - [[cite:LI-QUAN-1992][Lǐ 李(), 敦煌變文中的助詞系統 Dūnhuáng biànwén zhōng de zhùcí xìtǒng [The System of Auxiliary Words in the Dunhuang Transformation Texts] 語言研究 Yuyan yanjiu]]
***** LI WEIQI 2004
 - [[cite:LI-WEIQI-2004][Lǐ 李 Jiǎng 蔣(2004), 佛經詞語匯釋 Fójīng cíyǔ huìshì The Translation of the Vocabulary of Buddhist Sūtras]], p.194


Appears in the Buddhist translations of the Sui period

***** SONG YINSHENG 1996
 - [[cite:SONG-YINSHENG-1996][Sòng 宋(1996), 《祖堂集》虛詞研究 Zǔtáng jí xūcí yánjiū A Study of Function Words in Zǔtáng jí]], p.545-546

***** T.
 - [[cite:T.][Takakusu(1922-1933), 大正新修大藏經 Taishō shinshū daizōkyō Revised Edition of the Buddhist Canon in the Taishō Era]], p.2/190: 781a24
 (此乃是我試彼心看)
***** T.
 - [[cite:T.][Takakusu(1922-1933), 大正新修大藏經 Taishō shinshū daizōkyō Revised Edition of the Buddhist Canon in the Taishō Era]], p.3/190: 798b7


汝但說看 just try to speak up

***** T.
 - [[cite:T.][Takakusu(1922-1933), 大正新修大藏經 Taishō shinshū daizōkyō Revised Edition of the Buddhist Canon in the Taishō Era]], p.3/190: 815b4


FOBEN XINGJI JING:

少忍耐看，莫聲優惱 try to be a little patient and do not be said

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-e92d19a7-9dd9-40f7-9e71-5075ae5c0b4d][request]]} / V and investigate > try to V, V and see what happens (already appearing in sūtra translations of th...
:PROPERTIES:
:CUSTOM_ID: uuid-c4360523-9bf8-435c-9f03-49b76b8ac3d8
:END:
****** DEFINITION

V and investigate > try to V, V and see what happens (already appearing in sūtra translations of the Sui period (see LI WEIQI 2004: 194); the verbal phrase it follows can be complex and consist of a vt+N; in the colloquial language of the Tang this construction became increasingly popular, expressing mild requests; sometimes also defined as sentence final particle)

****** NOTES

*** 試 shì (OC:lʰɯɡs MC:ɕɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-e62ab021-85e2-46a1-9a88-4ed73f496cbb
:Char+: 試(149,6/13) 
:GY_IDS+: uuid-ce612313-dbcf-4aec-be39-176410f4cd28
:PY+: shì     
:OC+: lʰɯɡs     
:MC+: ɕɨ     
:END: 
**** V [[tls:syn-func::#uuid-dd717b3f-0c98-4de8-bac6-2e4085805ef1][vt+V/0/]] / try to, make an effort to
:PROPERTIES:
:CUSTOM_ID: uuid-5f959230-a526-4bc6-bcad-49fc89d0f697
:END:
****** DEFINITION

try to, make an effort to

****** NOTES

**** V [[tls:syn-func::#uuid-fbfb2371-2537-4a99-a876-41b15ec2463c][vtoN]] / try (a task etc)
:PROPERTIES:
:CUSTOM_ID: uuid-bd23d117-649b-4920-a7ff-6ac2b060487e
:END:
****** DEFINITION

try (a task etc)

****** NOTES

*** 嘗試 chángshì (OC:djaŋ lʰɯɡs MC:dʑi̯ɐŋ ɕɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-2a5d925e-c0cc-464f-85c9-6c9ff46174b8
:Char+: 嘗(30,11/14) 試(149,6/13) 
:GY_IDS+: uuid-599114b6-a3a5-43cd-910e-980cf9e48c59 uuid-ce612313-dbcf-4aec-be39-176410f4cd28
:PY+: cháng shì    
:OC+: djaŋ lʰɯɡs    
:MC+: dʑi̯ɐŋ ɕɨ    
:END: 
**** V [[tls:syn-func::#uuid-b0372307-1c92-4d55-a0a9-b175eef5e94c][VPt+prep+N]] / attempt to do something for N
:PROPERTIES:
:CUSTOM_ID: uuid-ab199d0b-d0d9-4457-8bdc-70d91e17ae84
:END:
****** DEFINITION

attempt to do something for N

****** NOTES

**** V [[tls:syn-func::#uuid-7918d628-430e-4537-afca-f2b1b4144611][VPt+V/0/]] / try (to do something)
:PROPERTIES:
:CUSTOM_ID: uuid-e01fc33d-e336-4408-89d3-6a3656c91f4f
:END:
****** DEFINITION

try (to do something)

****** NOTES

**** V [[tls:syn-func::#uuid-98f2ce75-ae37-4667-90ff-f418c4aeaa33][VPtoN]] / try (something) out
:PROPERTIES:
:CUSTOM_ID: uuid-e414c3d7-7975-4268-97a5-f9875276c7ef
:WARRING-STATES-CURRENCY: 3
:END:
****** DEFINITION

try (something) out

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
