# -*- mode: mandoku-tls-view -*-
#+TITLE: VARIABLE
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= VARIABLE
:PROPERTIES:
:CUSTOM_ID: uuid-a42eb765-5cf8-40e7-b201-5831aa255ed5
:TR_ZH: 變數的符號
:END:
** DEFINITION

IMAGE:symbol NOT REFERRING to ONE OBJECT BUT SHOWING RELATIONS of SAME REFERENCE.

** NOTES

*** Old Chinese Criteria
甲乙丙 are currently used as variables ranging over persons in legal texts, and also in mathematical texts like JIUZHANG. The analysis of the use of variables in mathematical texts is obviously of great importance. An abstract term for a variable does not exist in Chinese, and neither does it in Greek, where Aristotle made extensive and highly systematic use of variables which stand for predicates.

*** Modern Chinese Criteria
rough draft to BEGIN TO identify synonym group members for analysis, based on CL etc. 18.11.2003. CH ／ LU JIANMING

** SOURCE REFERENCES
*** HARBSMEIER 1998
 - [[cite:HARBSMEIER-1998][Harbsmeier(1998), Language and Logic Science and Civilisation in China]], p.333

*** RITTER 1971-2007
 - [[cite:RITTER-1971-2007][Ritter Gruender Gabriel(1971-2007), Historisches Woerterbuch der Philosophie]], p.11.545

*** QUINE 1987
 - [[cite:QUINE-1987][Quine(1987), Quiddities. An Intermittently Philosophical Dictionary]], p.236

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
