# -*- mode: mandoku-tls-view -*-
#+TITLE: VOLUNTARY
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= VOLUNTARY
:PROPERTIES:
:CUSTOM_ID: uuid-e662fa0d-9658-4aa4-82fb-6dbb88f4430a
:END:
** DEFINITION

DECIDE FREELY AND NOT BE FORCED

** NOTES

** SOURCE REFERENCES
*** T.W.HARBSMEIER 2004
 - [[cite:T.W.HARBSMEIER-2004][Harbsmeier(2004), A New Dictionary of Classical Greek Synonyms]], p.NO. 203


VOLUNTARY



hekôn is an adjectives describing persons who act of their own free will and on their own initiative

hekousios is an adjective which is mainly used to describe action of people who act of their own free will and on their own initiative. In Soph. Trach. 1123, however, it is used of a person.

ethelousios and ethelêmos (from ethelô, "want, consent") are adjectives usually used to describe people who act of their own free will upon stimulus, i. e. people who conform to, consent to, accept something voluntarily. ethelousios is also used to describe an action that one may consent to or accept voluntarily.

ethelontês, m./f., ethelontêr, m./f. and ethelêmôn, m./f., are nouns with a meaning and etymology similar to ethelousios. ethelontêr is poetic.

ethelourgos (from ethelô, "want, consent" and ergon, "work") is an adjective found describing persons and animals (or their inner drive or urge) willing to accept work. 

authairetos is an adjective describing things, officials, generals and the like that are to be elected freely.

autoboulos (from autos, "self" and boulê, "advice") is and adjective describing people who freely take their own decisions.

autokeleustos (from autos, "self" and keleuô, "order, command")  is an adjective describing persons who command themselves to do things and thus is a word for voluntary carrying connotations of selfdiscipline.



Related words (lacking the notion of WILL):



autokinêtos (from auto, "self" and kineô, "move") is an dadjective describing persons or things who move themselves spontaneously.

automatos is an adjective describing people, plants or things that act or behave spontaneously

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
