# -*- mode: mandoku-tls-view -*-
#+TITLE: WEAK VERBAL SUFFIX
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= WEAK VERBAL SUFFIX
:PROPERTIES:
:CUSTOM_ID: uuid-0ec307f0-0c61-4f89-8d21-7ca15a4396f6
:END:
** DEFINITION

[GRAMMAR][NOTE THAT THE GRAMMATICAL PARTICLES HAVE NOT BEEN FOCUSSED SO FAR IN THE SYSTEM AND NO SYSTEMATIC ANALYSIS HAS BEEN APPLIED SO FAR.]

** NOTES

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 來 lái (OC:m-rɯɯ MC:ləi )
:PROPERTIES:
:CUSTOM_ID: uuid-8dac3081-0174-4020-9b0c-710736f9a448
:Char+: 來(9,6/8) 
:GY_IDS+: uuid-9ef8de95-a9bb-45e9-a9eb-4ba693fb26c6
:PY+: lái     
:OC+: m-rɯɯ     
:MC+: ləi     
:END: 
**** V [[tls:syn-func::#uuid-1b60394c-c1b3-4f05-bb22-7cffe0450a62][vpostadV.adN]] / "adjective-marker"???? (Look for more examples to see how this works!)
:PROPERTIES:
:CUSTOM_ID: uuid-0c17215e-3a0f-4776-b5b1-34850027f393
:END:
****** DEFINITION

"adjective-marker"???? (Look for more examples to see how this works!)

****** NOTES

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] / colloquial suffix (continuative) "having V-ed"
:PROPERTIES:
:CUSTOM_ID: uuid-23dff8a0-0444-4f68-aaf5-2ee458f9087d
:END:
****** DEFINITION

colloquial suffix (continuative) "having V-ed"

****** NOTES

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-229a701e-1341-4719-9af8-a0b4e69c6c71][perfective]]} / verbal suffix specifying the direction of the action towards the speaker and the completion or succ...
:PROPERTIES:
:CUSTOM_ID: uuid-c4b40eab-45cf-44fb-a7df-ba904f1d6b14
:END:
****** DEFINITION

verbal suffix specifying the direction of the action towards the speaker and the completion or successful performance of an action

****** NOTES

*** 個 gè (OC:kaals MC:kɑ )
:PROPERTIES:
:CUSTOM_ID: uuid-c4989029-a367-43f4-949b-458f8858fe8a
:Char+: 個(9,8/10) 
:GY_IDS+: uuid-8dc49d39-8e34-4572-b2a2-81533b7b1936
:PY+: gè     
:OC+: kaals     
:MC+: kɑ     
:END: 
**** P [[tls:syn-func::#uuid-692c0672-88f0-46d3-9778-0dcbd2eaf54b][ppostadV]] / suffix (structure word) after verbs and adverbs
:PROPERTIES:
:CUSTOM_ID: uuid-87726e77-b80d-46b1-b6a7-a26585e552d5
:END:
****** DEFINITION

suffix (structure word) after verbs and adverbs

****** NOTES

*** 卻 què (OC:khaɡ MC:khi̯ɐk )
:PROPERTIES:
:CUSTOM_ID: uuid-ad2638dd-3225-4c50-8c1e-83c80c309703
:Char+: 卻(26,7/9) 
:GY_IDS+: uuid-c13e9847-d859-4e08-8257-41148a9a378c
:PY+: què     
:OC+: khaɡ     
:MC+: khi̯ɐk     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004B
 - [[cite:ANDERL-2004B][Anderl(2004), Studies in the Language of Zǔtáng jí 祖堂集]], p.258-259


Typical main verbs appearing with complement que4 are: 

fa4ng 放 'to release; let go', qi4 棄 'throw away', she3 捨 'remove'; shi1 失 'loose'; sha1o 燒 'burn'; li2 離 'to seperate; leave'; tuo1 脫 'to remove'; bo1 剝 'to peel'; ma2i 埋 'to bury';  chu2 除 'eliminate; get rid of'; hua4i 壞 'to destroy'; pa1o 拋 'to throw away; abandon'; chi1 喫 'to eat; drink'; tu3 吐 'to spit; vomit'; zhuo2 斫 'to chop off; cut'; hui4 諱 'to avoid'; wu1 污 'to stain; to defile'; ya3 啞 'to mute'; xia1 瞎 'to blind'; gua1n 關 'to shut; to lock'.

Most of the verbs belong to the semantic field V{remove} and que4 indicates that this removal is performed to its full, often resulting in the permanent removal, seperation from, or even destruction of the object. Often que4 also adds the notion that the object involved is beyond repair, i.e. the damaging affect on the object is permanent and not reversible.



546) ZTJ 5.111; WU: 437

“某甲自住此山，"Since I have lived on this mountain

未曾瞎卻一師僧眼。”I have never blinded the eyes of (i.e. deceived) a single monk."



547) ZTJ 5.104; WU: 431

“早是污卻也。”"It has already been defiled."



548) ZTJ 5.058; WU: 403

“除卻這個色，"After having removed this form,

還更有色也無？”is there an additional form?"



This is one of the rare examples where que4 follows a disyllabic verb (fa1-qia3n 發遣 'send away'):

549) ZTJ 5.061; WU: 404

行者隨童子到五祖處，The Postulant followed the child to the place of the Fifth Patriarch

五祖發遣卻童子後，and after the Fifth Patriarch had sent away the child

遂改盧行者名為慧能，he then changed the name of Postulant Lu2 to Hui4ne2ng,

授與衣缽，and bestowed the monk's robe and bowl [on him],

傳為六祖。giving him the transmission as Sixth Patriarch.

***** CAO GUANGSHUN 1986A
 - [[cite:CAO-GUANGSHUN-1986A][Cáo 曹(), 《祖堂集》中的底（地），卻（了），著 Zǔtáng jí zhōng de dǐ (dì), què (liǎo), zhu (zhe) 中國語文 Zhongguo yuwen]], p.195


Cao counts ca. 200 occurrences of complement 卻 in ZTJ, appearing with more than 70 different main verbs.

***** LI CHONGXING 1990
 - [[cite:LI-CHONGXING-1990][Lǐ 李(), 《祖堂集》中的助詞‘去’ Zǔtáng jí zhōng de zhùcí 'qù' [The Auxiliary Word 'qu' in ZTJ] 中國語文 Zhongguo yuwen]], p.74


Li remarks that also 去 can occasionally have the funtion of 卻 and that the phonetic value of the two words were very similar.

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-075a3430-764f-4aff-a41d-3d698b141898][degree]]} / resultative complement/complement of degree indicating that V has been performed to its full extant...
:PROPERTIES:
:CUSTOM_ID: uuid-599b5ba0-62c0-49b7-b81e-a633c8eb6c81
:END:
****** DEFINITION

resultative complement/complement of degree indicating that V has been performed to its full extant (often used after process verbs, indicating that a result of the process has been achieved)

****** NOTES

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-229a701e-1341-4719-9af8-a0b4e69c6c71][perfective]]} / perfective verbal complement
:PROPERTIES:
:CUSTOM_ID: uuid-0b13e9d8-4319-420a-adee-bfbe5f40436c
:END:
****** DEFINITION

perfective verbal complement

****** NOTES

*** 去 qù (OC:khaʔ MC:khi̯ɤ )
:PROPERTIES:
:CUSTOM_ID: uuid-b809c545-e08c-4f28-a6ab-9fd0e7dfea02
:Char+: 去(28,3/5) 
:GY_IDS+: uuid-b5af6e67-ab6f-4bf7-a18a-978223e2e8c9
:PY+: qù     
:OC+: khaʔ     
:MC+: khi̯ɤ     
:END: 
**** V [[tls:syn-func::#uuid-72f5e2dc-7a19-4993-9c8e-ffcce854ebea][vpost-V]] / go along V-ing; keep on V-ing?????
:PROPERTIES:
:CUSTOM_ID: uuid-852e3025-73c9-4ba2-8167-933d7392c8aa
:END:
****** DEFINITION

go along V-ing; keep on V-ing?????

****** NOTES

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] / indicator of direction of action away from agent
:PROPERTIES:
:CUSTOM_ID: uuid-eae328bf-9431-4f45-945b-5eb1bf9bafff
:END:
****** DEFINITION

indicator of direction of action away from agent

****** NOTES

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-9fe88d7d-3165-4402-a3f9-d9d6d511ad5b][direction]]} / weak verb added at the end of verb phrases to indicate direction of the action away from the speake...
:PROPERTIES:
:CUSTOM_ID: uuid-19f811ca-290b-43da-ace7-640ecddb971f
:END:
****** DEFINITION

weak verb added at the end of verb phrases to indicate direction of the action away from the speaker.

****** NOTES

*** 取 qǔ (OC:skhoʔ MC:tshi̯o )
:PROPERTIES:
:CUSTOM_ID: uuid-131ec68a-8dcb-4a5a-a185-0f62ede5adc4
:Char+: 取(29,6/8) 
:GY_IDS+: uuid-ae7faa0b-7337-42ff-bf3e-a4d370dad65d
:PY+: qǔ     
:OC+: skhoʔ     
:MC+: tshi̯o     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004B
 - [[cite:ANDERL-2004B][Anderl(2004), Studies in the Language of Zǔtáng jí 祖堂集]], p.257-258


Main verbs appearing with 取 often express mental processes  (especially 'to realize; get to know', e.g. 會，覺，識，了，驗，體，記，看) and speech acts (e.g. 道，說，問). Other verbs include 擬 'to imitate', 行 'to practice', 覓 'to search for', 揀 'to choose', 試 'to try', 移 'to move'.

The meaning as complement is probably connected to the meaning as main verb 'to grasp' and by extension 'to perform an action fully'. Many verbs qu3 appears together with can be interpreted as process verbs, e.g. describing a mental process. Qu3 indicates that the process should be completed so that a desired result can be achieved. It is no coincidence that qu3 often appears in sentences including modal verbs indicating obligation, and other modal markers such as sentence final 去.

I think that qu3 does not primarily indicate a result but a 'desired result' and as such differs from suffix 卻.

***** LI QUAN 1992
 - [[cite:LI-QUAN-1992][Lǐ 李(), 敦煌變文中的助詞系統 Dūnhuáng biànwén zhōng de zhùcí xìtǒng [The System of Auxiliary Words in the Dunhuang Transformation Texts] 語言研究 Yuyan yanjiu]], p.45


In Bianwen postverbal qu3 has two main functions. One function is marking completion or a resultative state. All in all there are ca. 20 examples of this kind in Bianwen, e.g. 

大夫若要商量取，一依處分不諍（爭）論。。。 (BIANWEN: 61);

玉女盡皆覺悟取，嬋媚各要出塵埃。(BIANWEN: 626); 

汝須努力莫為難，造取些些好果盤，待到眾僧解懮日，羅漢騰空盡喜歡。(BIANWEN: 708); 

今此覓取一員政官。(BIANWEN: 212); 

佛教如是觀虛幻，弁取前生識取因，莫在有為心有相。(BIANWEN: 444). 

The examples are cited in Li Quan 1992: 44. Li Quan thinks that the degree of grammaticalization of qu3 is not as high as the one of que4 卻 and the meaning as main verb is still present. However, early in the evolution of function words it is not uncommon that the original meaning as main verb has not completely faded. Viewed from this angle qu3 can be regarded as function word. Another function of qu3 in Bianwen is the indication of continuous aspect, qu3 取 (V.COMP.CONT). Quan Li counts ca. 14 examples of this function, e.g.:

我兒不宜住此方，將取金瓶歸下界。(Bianwen: 113); 

說法頭頭蒙告喻，。。。今於末代流傳取。(Bianwen: 525); 

記取今朝相動語，這身看即是無常。(Bianwen: 557).

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] / verbal suffix
:PROPERTIES:
:CUSTOM_ID: uuid-21b5fc16-ceea-40b4-97cc-e21e39c6e842
:END:
****** DEFINITION

verbal suffix

****** NOTES

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-516a7b20-3abd-49d2-a05c-65dace0c5337][continuative]]} / verbal suffix indicating continuative aspect
:PROPERTIES:
:CUSTOM_ID: uuid-ff65b281-8900-46d6-91cf-72272736018e
:END:
****** DEFINITION

verbal suffix indicating continuative aspect

****** NOTES

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-40457aee-75b5-4d96-a69c-34b0de40c16a][desired result]]} / weak verbal suffix (which sometimes seems to indicate a desired result by the speaker, often appear...
:PROPERTIES:
:CUSTOM_ID: uuid-d5d2258b-f351-4c59-9400-f14f42ad332c
:END:
****** DEFINITION

weak verbal suffix (which sometimes seems to indicate a desired result by the speaker, often appearing in sentences expressing a mild imperative/request; these sentences are often marked by sentence final 去)

****** NOTES

*** 地 dì (OC:lils MC:di )
:PROPERTIES:
:CUSTOM_ID: uuid-663b93e2-63b5-4a7c-9798-bf8cc5ddfbfd
:Char+: 地(32,3/6) 
:GY_IDS+: uuid-71cdcf18-a71b-4c14-9cad-7f42b728af2e
:PY+: dì     
:OC+: lils     
:MC+: di     
:END: 
**** P [[tls:syn-func::#uuid-692c0672-88f0-46d3-9778-0dcbd2eaf54b][ppostadV]] / suffix after stative verbs and adverbs
:PROPERTIES:
:CUSTOM_ID: uuid-9618daf1-72e0-4f1e-9476-5e7a9bf143fb
:END:
****** DEFINITION

suffix after stative verbs and adverbs

****** NOTES

**** P [[tls:syn-func::#uuid-692c0672-88f0-46d3-9778-0dcbd2eaf54b][ppostadV]] {[[tls:sem-feat::#uuid-1f824140-f0b0-43bf-a10b-b2c686121560][V=reduplicated]]} / suffix after reduplicated stative verbs
:PROPERTIES:
:CUSTOM_ID: uuid-82653431-aee7-43af-bd6b-badca8ec5258
:END:
****** DEFINITION

suffix after reduplicated stative verbs

****** NOTES

**** P [[tls:syn-func::#uuid-97f66b45-329f-413f-a60c-848681d456aa][ppostadV1.adV2]] {[[tls:sem-feat::#uuid-035572d0-d3a0-4cab-be07-69d4ceb9ca25][V1=reduplicated]]} / suffix after reduplicated adverbs
:PROPERTIES:
:CUSTOM_ID: uuid-e8d495c3-1c9f-4b66-b806-bd540ba9d9c4
:END:
****** DEFINITION

suffix after reduplicated adverbs

****** NOTES

*** 有 yǒu (OC:ɢʷɯʔ MC:ɦɨu )
:PROPERTIES:
:CUSTOM_ID: uuid-f3e59c33-0212-45ac-96fc-27e132f009c8
:Char+: 有(74,2/6) 
:GY_IDS+: uuid-5ba72032-5f6c-406d-a1fc-05dc9395e991
:PY+: yǒu     
:OC+: ɢʷɯʔ     
:MC+: ɦɨu     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004B
 - [[cite:ANDERL-2004B][Anderl(2004), Studies in the Language of Zǔtáng jí 祖堂集]], p.265

***** JIANG/CAO 1997
 - [[cite:JIANG/CAO-1997][Jiāng 江 Cáo 曹(1997), 唐五代語言詞典 Táng Wǔdài yǔyán cídiǎn A Dictionary of the Language of the Tang and Five Dynasties Periods]], p.420-421

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] / 有 can function as weak verbal suffix, sometimes also regarded as 'varbal structure word' (e.g. 知有 k...
:PROPERTIES:
:CUSTOM_ID: uuid-23667cda-7baa-4231-888b-c64928f1320a
:END:
****** DEFINITION

有 can function as weak verbal suffix, sometimes also regarded as 'varbal structure word' (e.g. 知有 know; 有請 'request', 有似 'resemble')

****** NOTES

*** 生 shēng (OC:sraaŋ MC:ʂɣaŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-ea3114eb-277d-4e11-838c-4b0b3fa5098c
:Char+: 生(100,0/5) 
:GY_IDS+: uuid-de384d51-47f4-44d9-8910-20aef1caaded
:PY+: shēng     
:OC+: sraaŋ     
:MC+: ʂɣaŋ     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004B
 - [[cite:ANDERL-2004B][Anderl(2004), Studies in the Language of Zǔtáng jí 祖堂集]], p.159-163


p. 159

It has been suggested that she1ng originally was a graphical representation of a colloquial suffix/word of a Southern dialect. One of the earliest examples appears in the 8th century She2nhu4i yu3-lu4 神會語錄 (SHENHUI YULU), probably written in South-China and containing many colloquial expressions, among them many Chinese graphs which are used phonetically. 

Oota cites the cryptic sentence:

yi4-mo4 shi2 zuo4-wu4-she1ng 異沒時作勿生 

The sentence corresponds to Modern Mandarin 那樣時怎麼樣 and it would be completely obscure if one did not know that all graphs in the sentence (with the exception of shi2 時) were used for their phonetic value and not the meaning of the graph. Thus they are phonetic loan graphs.

The verbal suffix she1ng 生 originated during the Tang dynasty but did not become common before the Five Dynasites and Song periods. There are a few early examples in Tang poetry. During this early period she1ng was attached to stative verbs, mostly in the pattern ta4i 太 (ADV) + VI-she1ng 生

During the late Tang and Five Dynasties periods the suffix became more frequent, especially in the Recorded Sayings and Du1nhua2ng literature (especially Bianwen). Most common was the usage of she1ng in the interrogative pronoun zuo4-mo2-she1ng 作摩生 (NPRO.QUEST). 

[...]

p. 162

The crucial question is whether she1ng should be regarded as verbal suffix or as some kind of intensifying sentence final particle. In zuo4-mo2-she1ng 作摩生 it is quite convincing to assume that she1ng is fused to the interrogative pronoun zuo4-mo2, and she1ng also does not seem to have any intensifying function. Probably she1ng is the graphic representation of a Southern dialect suffix (this would also explain the absence of this pronoun in Bianwen). On the other hand, she1ng may also gives emphasis to the verbal features of zuo4-mo2-she1ng 作摩生 (i.e. its usage as predicate).

By contrast, in the patterns vi + she1ng (and N + she1ng) the word rather has the features of a sentence final particle expressing high intensity and high degree (see the parallel sentence with ye3 也 above). In this function she1ng usually appears together with intensifying adverb ta4i 太 (see also CAO GUANGSHUN: 121)

Cao Guangshun thinks it is an important function of she1ng to give emphasis to the descriptive nature of the VP in all these constructions. (ibid.)

During the Song period she1ng 生 continued to be used in vernacular texts and there are somewhat more examples than in texts dating from the late Tang and Five Dynasties periods. She1ng was still most commonly used in constructions with intrasitive verbs (and often an intensifying adverb) and there were no changes as compared to the Tang period. Also attached to interrogative pronouns the suffix seems to indicate descriptive character (ze3n-she1ng 怎生; re4n-mo2-she1ng 恁麼生; she4n-she1ng 甚生), i.e. the usage as predicate 'be like what; how is it'.

However, there occurred some changes with respect to the construction VP + she1ng. This pattern became quite frequent during the Song. At this time also le 了 began to be used in a similar function. After the Yuan period le 了 began to replace she1ng 生, and she1ng became gradually obsolete and only survived in some customized phrases (see CAO GUANGSHUN 1995: 123).

The origin of verbal suffix she1ng is difficult to reconstruct. There are no examples predating the Tang and the examples from the Tang period are quite limited in number. Some scholars think that she1ng is connected to the suffix xi1n 馨 of the Wei, Jin and Six Dynasties periods which occasionally appeared after pronouns and verbal phrases.

Also Liu Jian thinks that the main function of she1ng is the emphasis of the descriptive nature of a VP, occasionally even marking an exaggeration. From Song times onwards the VP preceding she1ng could be increasingly complex (LIU JIAN 1992A: 285). Thus the development is from a suffix attached to monosyllabic and rarely disyllabic stative verbs to a 'particle' modifying the whole VP or sentence. By contrast to le 了, she1ng eventually did not develop further and its usage became restricted to a few idiomized phrases in the colloquial language.

I think that she1ng 生 is a dialect word which was originally used in Southern dialects. Its function is closely related to the later ya4ng 樣 which originally means 'appearance; shape; model; pattern'. t is obvious that the interrogative pronoun zuo4-mo2-she1ng 作摩生 is the precursor of Modern Mandarin ze3nmeya4ng 怎麼樣. However, the similarities are not restricted to the above pronouns. As discussed above, she1ng is also placed after VPs and adds emphasis to the VP, often co-occurring with intensifying adverbs. I think that this function is directly connected to the meaning she1ng 生 'sort; kind' which can be found in Yuan dramas. During this time this meaning also occurred in the compound zhe4-she1ng 這生 'be like this' which is used directly parallel to zhe4-ba1n 這般 and zhe4-ya4ng 這樣 (see JOHNSON 2000: 208). I conclude that she1ng probably should not be regarded as suffix but as the graphic (and phonetic) representation of a dialect word. In its usage as component of interrogative pronouns it should be regarded as morphem similar in meaning and function to the later ya4ng 樣. Placed after VPs it adds emphasis ('that's how it is') to the statement (or the description) and is not used as a suffix (rather resembles particle di3 底 in this function).

***** CAO GUANGSHUN 1995
 - [[cite:CAO-GUANGSHUN-1995][Cáo 曹(1995), 近代漢語助詞 Jìndài hànyǔ zhùcí Auxiliary Words in Early Mandarin]], p.121ff.

***** CREAMER 1991
 - [[cite:CREAMER-1991][Creamer(1991), A Chinese-English Dictionary of the Wu dialect]], p.161


In the Wu 吳 dialect the suffix is still used today, usually after stative verbs.

***** GUZUN
 - [[cite:GUZUN][Yí 頤(), 古尊宿語錄 Gǔzūnsù yǔlù Recorded Sayings of Old Worthies ZZ]]

After VPs containing nouns, here she1ng resembles a sentence final rather than a suffix;

大煞費力生。 "too much of an effort; too exhausting."

with negated VP:

太不速道生。"Not spoken fast enough!"

***** JINGDECHUANDENGLU
 - [[cite:JINGDECHUANDENGLU][(), 景德傳燈錄 Jǐngdé chuándēng lù The Record of the Transmission of the Lamp Published in the Jǐngdé Era Taishō]]

日出太早生。"The sun goes up too early!"

***** JOHNSON 2000
 - [[cite:JOHNSON-2000][Johnson(2000), A Glossary of Words and Phrases in the Oral Performing and Dramatic Literatures of the Jin, Yuan, and Ming]], p.208

***** OTA 1988
 - [[cite:OTA-1988][Ōta 太田(1988), 中國語史通考 Chūgoku goshi tsūkō A Historical Study of the Chinese Language]], p.140-141

***** YU GU 1995
 - [[cite:YU-GU-1995][Yú 于(1995), 禪宗語言和文獻 Chánzōng yǔyán hé wénxiàn The Language and Literary Works of the Zen School]], p.72

*** 當 dāng (OC:taaŋ MC:tɑŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-eca13351-f64c-4882-b8c9-dabd94671e42
:Char+: 當(102,8/13) 
:GY_IDS+: uuid-4761ef26-92d1-497a-8a8d-7052c2b86ca2
:PY+: dāng     
:OC+: taaŋ     
:MC+: tɑŋ     
:END: 
**** SOURCE REFERENCES
***** ANDERL 2004C
 - [[cite:ANDERL-2004C][Anderl(2004), Studies in the Language of Zu-tang Ji 祖堂集]], p.261

***** JIANG/CAO 1997
 - [[cite:JIANG/CAO-1997][Jiāng 江 Cáo 曹(1997), 唐五代語言詞典 Táng Wǔdài yǔyán cídiǎn A Dictionary of the Language of the Tang and Five Dynasties Periods]], p.85

**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] / verbal suffix (probably used for disyllabication); sometimes categorized as 'structure word' (結構詞) ...
:PROPERTIES:
:CUSTOM_ID: uuid-8d7e391d-e41c-48f4-be6a-b0375f7ec4f5
:END:
****** DEFINITION

verbal suffix (probably used for disyllabication); sometimes categorized as 'structure word' (結構詞) without any meaning, or as suffix/complement/ auxiliary similar to 著); e.g. 記當, 問當 (BIANWEN);  in Tang texts 當 can also be added to copula 為, however, the resulting 為當 is restricted in its function to marking alternative questions

****** NOTES

*** 知 zhī (OC:te MC:ʈiɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-a095392b-86b4-4848-9999-536dfaa716cf
:Char+: 知(111,3/8) 
:GY_IDS+: uuid-66c0756c-fd79-48b2-a2cd-ee269a87f3c6
:PY+: zhī     
:OC+: te     
:MC+: ʈiɛ     
:END: 
**** SOURCE REFERENCES
***** JIANG/CAO 1997
 - [[cite:JIANG/CAO-1997][Jiāng 江 Cáo 曹(1997), 唐五代語言詞典 Táng Wǔdài yǔyán cídiǎn A Dictionary of the Language of the Tang and Five Dynasties Periods]], p.443, #3
 (助詞，無實義。《變文集》卷一《李陵變文》：“自從按節為君將，一戰凡知幾百年。”又《伍子胥變文》：“王今伐吳，定知自損。”)
**** P [[tls:syn-func::#uuid-692c0672-88f0-46d3-9778-0dcbd2eaf54b][ppostadV]] / suffix/structure word in adverbs (this usage of zhī appeared during the Tang, e.g. 但知, 定知, 凡知)
:PROPERTIES:
:CUSTOM_ID: uuid-f812503d-a5a0-43c1-98a9-10a44af613ce
:END:
****** DEFINITION

suffix/structure word in adverbs (this usage of zhī appeared during the Tang, e.g. 但知, 定知, 凡知)

****** NOTES

*** 自 zì (OC:sblids MC:dzi )
:PROPERTIES:
:CUSTOM_ID: uuid-38861bce-e993-417a-b375-c699d5d8caf1
:Char+: 自(132,0/6) 
:GY_IDS+: uuid-27f414fe-6bec-4eef-88d1-0e87a4bfbc33
:PY+: zì     
:OC+: sblids     
:MC+: dzi     
:END: 
**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-b7202919-801b-4e6a-8a0e-4bbf3755324c][suffix]]} / suffix after adverbs
:PROPERTIES:
:CUSTOM_ID: uuid-ef65d203-3cbe-4fb1-98f9-c37a43532a79
:END:
****** DEFINITION

suffix after adverbs

****** NOTES

*** 著 zhuó (OC:k-laɡ MC:ʈi̯ɐk )
:PROPERTIES:
:CUSTOM_ID: uuid-f5d2c239-64ed-4520-bc39-6d6455ed8d4c
:Char+: 著(140,8/14) 
:GY_IDS+: uuid-257cc1ea-48fa-40f5-bcac-2e75328d6894
:PY+: zhuó     
:OC+: k-laɡ     
:MC+: ʈi̯ɐk     
:END: 
**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] {[[tls:sem-feat::#uuid-516a7b20-3abd-49d2-a05c-65dace0c5337][continuative]]} / verbal complement indicating a continuous action or state
:PROPERTIES:
:CUSTOM_ID: uuid-db820617-0d11-45db-a00e-765262e261d9
:END:
****** DEFINITION

verbal complement indicating a continuous action or state

****** NOTES

*** 許 xǔ (OC:hŋaʔ MC:hi̯ɤ )
:PROPERTIES:
:CUSTOM_ID: uuid-dcde11af-e62b-426a-86ce-eb332e450dd1
:Char+: 許(149,4/11) 
:GY_IDS+: uuid-cea102cd-f4c1-4145-8afa-fcbd88ec12f1
:PY+: xǔ     
:OC+: hŋaʔ     
:MC+: hi̯ɤ     
:END: 
**** SOURCE REFERENCES
***** JIANG/CAO 1997
 - [[cite:JIANG/CAO-1997][Jiāng 江 Cáo 曹(1997), 唐五代語言詞典 Táng Wǔdài yǔyán cídiǎn A Dictionary of the Language of the Tang and Five Dynasties Periods]], p.396, #5

**** P [[tls:syn-func::#uuid-692c0672-88f0-46d3-9778-0dcbd2eaf54b][ppostadV]] / vernacular verbal suffix (similar in function to suffixes 生 and 馨)
:PROPERTIES:
:CUSTOM_ID: uuid-f848f719-4ee7-4a5b-ba3f-484cafef4038
:END:
****** DEFINITION

vernacular verbal suffix (similar in function to suffixes 生 and 馨)

****** NOTES

*** 以 yǐ (OC:k-lɯʔ MC:jɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-8333bd1d-d267-46ac-b60a-77c72ea6e4d2
:Char+: 以(9,3/5) 
:GY_IDS+: uuid-4a877402-3023-41b9-8e4b-e2d63ebfa81c
:PY+: yǐ     
:OC+: k-lɯʔ     
:MC+: jɨ     
:END: 
**** V [[tls:syn-func::#uuid-6bcabe16-89d8-45be-aa0b-57177f67b1f9][vpostadV]] / postverbal coverb in idioms like 可以，足以，難以
:PROPERTIES:
:CUSTOM_ID: uuid-0dbe0618-35bd-4a19-8c62-6ec06ccd4cc7
:END:
****** DEFINITION

postverbal coverb in idioms like 可以，足以，難以

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
