# -*- mode: mandoku-tls-view -*-
#+TITLE: ZEN PHRASES
#+DATE: 2017-03-18T10:35:30.668+09:00        
#+STARTUP: content
* =CONCEPT= ZEN PHRASES
:PROPERTIES:
:CUSTOM_ID: uuid-039dd702-55e3-48cb-9de5-9c9a24d234d4
:END:
** DEFINITION

TEMPORARY GROUP TO BE REANALISED IN TERMS OF SYNONYM GROUPS.

** NOTES

** WORDS
   :PROPERTIES:
   :VISIBILITY: children
   :END:
*** 不念 bùniàn (OC:pɯʔ mɢlɯɯms MC:pi̯ut nem )
:PROPERTIES:
:CUSTOM_ID: uuid-f58f880b-e8b5-4a8d-8405-28a0c58c1cfd
:Char+: 不(1,3/4) 念(61,4/8) 
:GY_IDS+: uuid-12896cda-5086-41f3-8aeb-21cd406eec3f uuid-b7be0ebb-3f71-4942-850c-3361b128a506
:PY+: bù niàn    
:OC+: pɯʔ mɢlɯɯms    
:MC+: pi̯ut nem    
:END: 
**** N [[tls:syn-func::#uuid-db0698e7-db2f-4ee3-9a20-0c2b2e0cebf0][NPab]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: non-thinking, not engaging in thinking activities (one of the important terms of the early C...
:PROPERTIES:
:CUSTOM_ID: uuid-d143c5d9-ab95-4ebb-925f-e804dd0a49e7
:END:
****** DEFINITION

BUDDH: non-thinking, not engaging in thinking activities (one of the important terms of the early Chán School)

****** NOTES

**** V [[tls:syn-func::#uuid-091af450-64e0-4b82-98a2-84d0444b6d19][VPi]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: not to engage in any (discriminating) thinking activities
:PROPERTIES:
:CUSTOM_ID: uuid-04e50c76-13d0-4eb1-8aea-ce3fbb807fc6
:END:
****** DEFINITION

BUDDH: not to engage in any (discriminating) thinking activities

****** NOTES

*** 坐佛 zuòfó (OC:sɡoolʔ bɯd MC:dzʷɑ bi̯ut )
:PROPERTIES:
:CUSTOM_ID: uuid-406f399e-6dfb-4a34-8402-99a69c824313
:Char+: 坐(32,4/7) 佛(9,5/7) 
:GY_IDS+: uuid-f88c4755-7f5b-4f25-8190-8d5a961a2884 uuid-d47e7bd5-88a4-4216-b6ee-b266d66dd08c
:PY+: zuò fó    
:OC+: sɡoolʔ bɯd    
:MC+: dzʷɑ bi̯ut    
:END: 
**** SOURCE REFERENCES
***** NAKAMURA
 - [[cite:NAKAMURA][Nakamura 望月(1975), 佛教語大辭典 Bukkyōgo daijiten Encyclopedic Dictionary of Buddhist Terms]], p.442b

**** V [[tls:syn-func::#uuid-091af450-64e0-4b82-98a2-84d0444b6d19][VPi]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: sit in meditation in order to become a Buddha > become a Buddha through sitting in meditatio...
:PROPERTIES:
:CUSTOM_ID: uuid-d07a8b47-2896-4bdd-b258-100eb2b59e86
:END:
****** DEFINITION

BUDDH: sit in meditation in order to become a Buddha > become a Buddha through sitting in meditation (this is a rare a late compound, see JINGDECHUANDENGLU)

****** NOTES

*** 安心 ānxīn (OC:qaan slɯm MC:ʔɑn sim )
:PROPERTIES:
:CUSTOM_ID: uuid-5cfed922-07d9-4fe2-a952-66463d73cfaf
:Char+: 安(40,3/6) 心(61,0/4) 
:GY_IDS+: uuid-f8753075-adb6-43d4-bf48-caa024c8d9c4 uuid-8a9907df-7760-4d14-859c-159d12628480
:PY+: ān xīn    
:OC+: qaan slɯm    
:MC+: ʔɑn sim    
:END: 
**** SOURCE REFERENCES
***** CHAPPELL 1983
 - [[cite:CHAPPELL-1983][Chappell Lai Lancaster(1983), The Teachings of the Fourth Ch'an Patriarch Tao-hsin (580-651) Early Ch'an in China and Tibet]], p.96


"Standing in the middle of these texts, the 入道安心要方便法門 [contained in LENGQIE SHIZI JI] is perhaps the most developed in terms of language and thought. We immediately see from the title that it picks up a theme from Bodhidharma by emphasizing 'fundamental expedient teachings for calming the mind'. In the XUGAOSENGXZHUAN biography of Bodhidharma in the preface to the 二入四行論 attributed to Ta2nli2n by the Transmission of the Lamp, 安心 is equated with 壁觀 ('wall-contemplation') as the key practice of Bodhidharma. In a Dunhuang manuscript of the ERRU SIXING LUN, anxin was listed as one of four practices subsumed under the general title of 'The Method of Calming the Mind (anxin) according to Mah$ay$ana'. [in STEIN 2715, reprintedin SUZUKI 1968, vol.2: 141)]. Consequently we see that anxin in the title of the 入道安心要方便法門 links it directly to a term designating the overall practices of Bodhidharma. In addition,  in the section on Gunabadhra in the LENGQIE SHIZI JI, anxin is broken down into four stages in terms of the degree to which one actualizes the mind which has insight into the true reality (理心) [T.85: 1284 a,b]. This indentifies anxin not with a specific practice, therefore, but with realization of the truth. For Daoxin, anxin is a unified mindfulness which is to be maintained without deviation (守一不移). It is the removal of all objectified or dualistic thinking in the clear light of nonsubstantiality and interpenetration [ibid.: 1288]."

***** ERRU SIXING LUN(A)
 - [[cite:ERRU-SIXING-LUN(A)][YANAGIDA 1969(), 二入四行論 Èrrù sìxíng lùn Treatise on the Two Entries and Four Practices]], p.25


In the preface by Ta2nli2n 曇林

如是安心，如是發行，如是順物，如是方便。此是大乘安心之法。如是安心者壁觀。。。



安心 is here interpreted as one of four essential aspects of Mah$ay$ana Buddhism and is related to (or even regarded as syn. for) 'wall-contemplation' 壁觀.

***** FAURE 1989
 - [[cite:FAURE-1989][Faure(1989), Le Bouddhisme Ch'an en Mal d'Histoire]], p.106-107


French translation of the passage on four kinds of 'pacifying the mind' in the LENGQIE SHIZI JI

***** LENGQIE SHIZI JI
 - [[cite:LENGQIE-SHIZI-JI][(), 楞伽師資記 Léngqié shīzī jì Record on the Masters and Disciples of the Lañkāvatāra Taishō]]

T85n2837_p1284a29(02)今言安心者。

T85n2837_p1284b01(01)略有四種。一者背理心。謂一向凡夫心也。

T85n2837_p1284b02(01)二者向理心。謂厭惡生死。以求涅槃。

T85n2837_p1284b03(03)趣向寂靜。名聲聞心也。三者入理心。

T85n2837_p1284b04(06)謂雖復斷障顯理。能所未亡。是菩薩心也。四者理心。

T85n2837_p1284b05(03)謂非理外理。非心外心。理即是心。心能平等。

T85n2837_p1284b06(03)名之為理。理照能明。名之為心。心理平等。

T85n2837_p1284b07(04)名之為佛心。會實性者。不見生死涅槃有別。凡聖為異。

T85n2837_p1284b08(00)境智無二。理事俱融。真俗齊觀。染淨一如。

T85n2837_p1284b09(01)佛與眾生。本來平等一際。楞伽經云。

T85n2837_p1284b10(04)一切無涅槃。無有涅槃佛。無有佛涅槃。遠離覺所覺。

T85n2837_p1284b11(01)若有若無有。是二悉俱離。大道本來廣遍。

T85n2837_p1284b12(01)圓淨本有。不從因得。如似浮雲底日光。

T85n2837_p1284b13(03)雲霧滅盡。日光自現。何用更多廣學知見。

T85n2837_p1284b14(04)涉歷文字語言。覆歸生死道。用口說文傳為道此者。

T85n2837_p1284b15(00)人貪求名利。自壞壞他。亦如磨銅鏡。

T85n2837_p1284b16(02)鏡面上塵落盡。鏡自明淨。諸無行。



There is a French translation of this passage in FAURE 1989: 106-107. Faure comments that this concept of four kinds of pacifying the mind is probably influenced by the ERRU SIXING LUN, and that there are parallels to the four kinds of dhy$ana in the the LANKAVATARA (see Suzuki 1977: 85-86)

***** SEKIDA 1977
 - [[cite:SEKIDA-1977][Sekida(1977), Two Zen Classics]], p.118, 148


T48n2005_p0298a16(00)達磨面壁。二祖立雪斷臂云。弟子心未安。

T48n2005_p0298a17(01)乞師安心。磨云。將心來。與汝安。祖云。

T48n2005_p0298a18(03)覓心了不可得。磨云。為汝安心竟

"Bodhidharma set facing the wall. The second Patriarch stood in the snow. He cut off his arm and presented it to Bodhidharma, crying: 'My mind has no peace as yet! I beg you, master, please pacify my mind!' 'Bring your mind here and I will pacify it for you,' replied Bodhidharma. 'I have searched for my mind, and I cannot take hold of it,' said the second Patriarch. 'Now your mind is pacified,' said Bodhidharma."



Hirata comments that the story about 安心 as presented in the JINGDECHUANDENGLU is meant to show a connenction between the first to the fourth Chinese patriarchs. It symbolizes the question concerning the ultimate meaning in a compressed form.

***** TANAKA 1985
 - [[cite:TANAKA-1985][Tanaka 田中(1985), 初期禪宗における守心-觀心の系譜 Shoki Zenshū ni okeru shuusin kanshin no keifu 佛教の歷史と思想 Bukkyō no rekishi to shisō]]
***** WUMENGUAN
 - [[cite:WUMENGUAN][(), 無門關 Wúmén guān The Gateless Barrier Taishō]], p.292c13


T48n2005_p0292b27(04)　　　　佛祖機緣四十八則

T48n2005_p0292b28(00)　　目錄

T48n2005_p0292b29(00)　趙州狗子　百丈野狐　俱胝豎指

T48n2005_p0292c01(00)　胡子無鬚　香嚴上樹　世尊拈花

T48n2005_p0292c02(00)　趙州洗缽　奚仲造車　大通智勝

T48n2005_p0292c03(00)　清稅孤貧　州勘庵主　巖喚主人

T48n2005_p0292c04(00)　德山托缽　南泉斬貓　洞山三頓

T48n2005_p0292c05(00)　鐘聲七條　國師三喚　洞山三斤

T48n2005_p0292c06(00)　平常是道　大力量人　雲門屎橛

T48n2005_p0292c07(00)　迦葉剎竿　不思善惡　離卻語言

T48n2005_p0292c08(00)　三座說法　二僧卷簾　不是心佛

T48n2005_p0292c09(00)　久響龍潭　非風非幡　即心即佛

T48n2005_p0292c10(00)　趙州勘婆　外道問佛　非心非佛

T48n2005_p0292c11(00)　智不是道　倩女離魂　路逢達道

T48n2005_p0292c12(00)　庭前柏樹　牛過窗櫺　雲門話墮

T48n2005_p0292c13(00)　趯倒淨瓶　達磨安心　女子出定

T48n2005_p0292c14(00)　首山竹篦　芭蕉拄杖　他是阿誰

T48n2005_p0292c15(00)　竿頭進步　兜率三關　乾峰一路

T48n2005_p0292c16(00)目錄(終)

***** WUMENGUAN
 - [[cite:WUMENGUAN][(), 無門關 Wúmén guān The Gateless Barrier Taishō]], p.case 41


T48n2005_p0298a15(00)　　達磨安心

T48n2005_p0298a16(00)達磨面壁。二祖立雪斷臂云。弟子心未安。

T48n2005_p0298a17(01)乞師安心。磨云。將心來。與汝安。祖云。

T48n2005_p0298a18(03)覓心了不可得。磨云。為汝安心竟

T48n2005_p0298a19(00)　無門曰。缺齒老胡。十萬里航海特特而來。

T48n2005_p0298a20(00)　可謂是無風起浪。末後接得一箇門人。

T48n2005_p0298a21(01)　又卻六根不具。咦謝三郎。不識四字

T48n2005_p0298a22(00)　　頌曰

T48n2005_p0298a23(00)　西來直指　　事因囑起　　撓聒叢林

T48n2005_p0298a24(00)　元來是爾

***** YANAGIDA 1967
 - [[cite:YANAGIDA-1967][Yanagida 柳田(1967), 初期禪宗史書の研究 Shoki zenshū shisho no kenkyū Studies on the Historical Works of the Early Period of Zen Buddhism]], p.72-73

***** ZONGJINGLU
 - [[cite:ZONGJINGLU][(), 宗鏡錄 Zōngjīng lù Records of the Mirror of Truth Taishō]], p.953a


T48n2016_p0953a13(03)跋陀三藏云。理心者。

T48n2016_p0953a14(03)心非理外。理非心外。心即是理。理即是心。心理平等。

T48n2016_p0953a15(00)名之為理。理照能明。名之為心。覺。心理平等。

T48n2016_p0953a16(00)名之為佛。心。會實性者。不見生死涅槃有別。

T48n2016_p0953a17(00)凡聖無異。境智一如。理事俱融。真俗齊觀。

T48n2016_p0953a18(01)圓通無礙。名修大道。

**** N [[tls:syn-func::#uuid-db0698e7-db2f-4ee3-9a20-0c2b2e0cebf0][NPab]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: pacification of the mind
:PROPERTIES:
:CUSTOM_ID: uuid-6458aabc-b729-4998-94de-a036686244e7
:END:
****** DEFINITION

BUDDH: pacification of the mind

****** NOTES

**** V [[tls:syn-func::#uuid-091af450-64e0-4b82-98a2-84d0444b6d19][VPi]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: pacify the mind, set the mind at ease (this is specific term and meditation method, frequent...
:PROPERTIES:
:CUSTOM_ID: uuid-62bc8b66-e672-499e-a0ff-1dad93aa21af
:END:
****** DEFINITION

BUDDH: pacify the mind, set the mind at ease (this is specific term and meditation method, frequently mentioned in early Chan/Zen Buddhist texts, with a variety of interpretations; see SOURCES)

****** NOTES

*** 無念 wúniàn (OC:ma mɢlɯɯms MC:mi̯o nem )
:PROPERTIES:
:CUSTOM_ID: uuid-e72bf0b1-8117-4098-9077-8dcd25b41d6f
:Char+: 無(86,8/12) 念(61,4/8) 
:GY_IDS+: uuid-5de002ac-c1a1-4519-a177-4a3afcc155bb uuid-b7be0ebb-3f71-4942-850c-3361b128a506
:PY+: wú niàn    
:OC+: ma mɢlɯɯms    
:MC+: mi̯o nem    
:END: 
**** N [[tls:syn-func::#uuid-db0698e7-db2f-4ee3-9a20-0c2b2e0cebf0][NPab]] {[[tls:sem-feat::#uuid-2e7204ae-4771-435b-82ff-310068296b6d][buddhist]]} / BUDDH: non-thinking
:PROPERTIES:
:CUSTOM_ID: uuid-eda9e3b7-a1f6-46cf-8879-1b61ada8be8c
:END:
****** DEFINITION

BUDDH: non-thinking

****** NOTES

*** 野狐情 yěhúqíng (OC:laʔ ɡʷaa dzeŋ MC:jɣɛ ɦuo̝ dziɛŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-5404dfe4-fafe-4b9d-928e-d99388927d3e
:Char+: 野(166,4/11) 狐(94,5/8) 情(61,8/11) 
:GY_IDS+: uuid-35aad878-a61d-4368-8e00-10c916814ff8 uuid-dc497047-48d1-4dde-90ff-bc936f2ef309 uuid-fe0dbc1f-2ca0-4174-9787-b9511e7f67fb
:PY+: yě hú qíng   
:OC+: laʔ ɡʷaa dzeŋ   
:MC+: jɣɛ ɦuo̝ dziɛŋ   
:END: 
**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2d131ece-0e8e-4fd3-8839-9395b7aa4b14][colloquial]]} / BUDDH: wild fox spirit (derogatory and colloquial expression for somebody who has gone astray and i...
:PROPERTIES:
:CUSTOM_ID: uuid-2b306f54-c924-449d-be5f-bbc61057c7b8
:END:
****** DEFINITION

BUDDH: wild fox spirit (derogatory and colloquial expression for somebody who has gone astray and ignorant; more common is 野狐精)

****** NOTES

*** 野狐精 yěhújīng (OC:laʔ ɡʷaa tseŋ MC:jɣɛ ɦuo̝ tsiɛŋ )
:PROPERTIES:
:CUSTOM_ID: uuid-4a60efaa-b5dd-4358-bfb5-5410d5868482
:Char+: 野(166,4/11) 狐(94,5/8) 精(119,8/14) 
:GY_IDS+: uuid-35aad878-a61d-4368-8e00-10c916814ff8 uuid-dc497047-48d1-4dde-90ff-bc936f2ef309 uuid-c6636819-42f0-4291-9caf-40f23edd4c57
:PY+: yě hú jīng   
:OC+: laʔ ɡʷaa tseŋ   
:MC+: jɣɛ ɦuo̝ tsiɛŋ   
:END: 
**** N [[tls:syn-func::#uuid-a8e89bab-49e1-4426-b230-0ec7887fd8b4][NP]] {[[tls:sem-feat::#uuid-2d131ece-0e8e-4fd3-8839-9395b7aa4b14][colloquial]]} / BUDDH: wild fox spirit (derogatory and colloquial expression for somebody who has gone astray and i...
:PROPERTIES:
:CUSTOM_ID: uuid-633c62d2-dd19-49a3-8e95-65adf2b4bb38
:END:
****** DEFINITION

BUDDH: wild fox spirit (derogatory and colloquial expression for somebody who has gone astray and ignorant)

****** NOTES

*** 不立文字 bùlìwénzì (OC:pɯʔ ɡ-rub mɯn sɡlɯs MC:pi̯ut lip mi̯un dzɨ )
:PROPERTIES:
:CUSTOM_ID: uuid-e7c84beb-5341-489a-8f0b-74475901e8d8
:Char+: 不(1,3/4) 立(117,0/5) 文(67,0/4) 字(39,3/6) 
:GY_IDS+: uuid-12896cda-5086-41f3-8aeb-21cd406eec3f uuid-b598e84b-bbd1-403a-973b-cb95c13b5b7e uuid-9bad1e6b-8012-44fa-9361-adf5aa491542 uuid-462c4590-ed5f-4361-ab03-e6d19e9a434e
:PY+: bù lì wén zì  
:OC+: pɯʔ ɡ-rub mɯn sɡlɯs  
:MC+: pi̯ut lip mi̯un dzɨ  
:END: 
**** V [[tls:syn-func::#uuid-155b3f78-76bb-4fc8-9f02-6d3f28b5d00d][{VP...}]] / BUDDH: important phrase frequently appearing in Chan/Zen works: not to base oneself/postulate writt...
:PROPERTIES:
:CUSTOM_ID: uuid-94aeb58b-22c0-4e1c-b1e7-4041b34b67b6
:END:
****** DEFINITION

BUDDH: important phrase frequently appearing in Chan/Zen works: not to base oneself/postulate written words (meaning that insight must be based on direct experience and not on the texts of established traditions)

****** NOTES

*** 以心傳心 yǐxīnchuánxīn (OC:k-lɯʔ slɯm don slɯm MC:jɨ sim ɖiɛn sim )
:PROPERTIES:
:CUSTOM_ID: uuid-16d58fe8-19f2-4919-8ad3-9595967e8143
:Char+: 以(9,3/5) 心(61,0/4) 傳(9,11/13) 心(61,0/4) 
:GY_IDS+: uuid-4a877402-3023-41b9-8e4b-e2d63ebfa81c uuid-8a9907df-7760-4d14-859c-159d12628480 uuid-50da5830-5134-4b24-8b52-bf44679f9f44 uuid-8a9907df-7760-4d14-859c-159d12628480
:PY+: yǐ xīn chuán xīn  
:OC+: k-lɯʔ slɯm don slɯm  
:MC+: jɨ sim ɖiɛn sim  
:END: 
**** V [[tls:syn-func::#uuid-155b3f78-76bb-4fc8-9f02-6d3f28b5d00d][{VP...}]] / BUDDH: important phrase frequently appearing in Zen/Chan works: transmit the Mind through the Mind
:PROPERTIES:
:CUSTOM_ID: uuid-59f87cb2-11e6-4600-974b-cfad9b084439
:END:
****** DEFINITION

BUDDH: important phrase frequently appearing in Zen/Chan works: transmit the Mind through the Mind

****** NOTES

*** 即心即佛 jíxīnjífó (OC:tsɯɡ slɯm tsɯɡ bɯd MC:tsɨk sim tsɨk bi̯ut )
:PROPERTIES:
:CUSTOM_ID: uuid-2d3c9eca-c61e-4419-80a0-621eed71c87c
:Char+: 即(26,5/7) 心(61,0/4) 即(26,5/7) 佛(9,5/7) 
:GY_IDS+: uuid-9c207839-c526-42a5-bbd1-48637a0927c8 uuid-8a9907df-7760-4d14-859c-159d12628480 uuid-9c207839-c526-42a5-bbd1-48637a0927c8 uuid-d47e7bd5-88a4-4216-b6ee-b266d66dd08c
:PY+: jí xīn jí fó  
:OC+: tsɯɡ slɯm tsɯɡ bɯd  
:MC+: tsɨk sim tsɨk bi̯ut  
:END: 
**** V [[tls:syn-func::#uuid-155b3f78-76bb-4fc8-9f02-6d3f28b5d00d][{VP...}]] / BUDDH: "this very mind is the Buddha" (famous phrase by Chán Master Mǎzǔ 馬祖)
:PROPERTIES:
:CUSTOM_ID: uuid-08168d2e-1bb5-45f2-b20b-3b2c84350038
:END:
****** DEFINITION

BUDDH: "this very mind is the Buddha" (famous phrase by Chán Master Mǎzǔ 馬祖)

****** NOTES

*** 寸絲不掛 cùnsībùguà (OC:tshuuns sɯ pɯʔ kʷrees MC:tshuo̝n sɨ pi̯ut kɣɛ )
:PROPERTIES:
:CUSTOM_ID: uuid-35b8127a-e19d-4906-a9ab-5121112923a7
:Char+: 寸(41,0/3) 絲(120,6/12) 不(1,3/4) 掛(64,8/11) 
:GY_IDS+: uuid-681b4d4c-fcd8-42f0-a022-51fc6f585bdb uuid-f6978c43-e2b9-44d4-bc08-e3d780fd37ca uuid-12896cda-5086-41f3-8aeb-21cd406eec3f uuid-72a18d94-f1dc-4828-a105-fdd8b9ef81b6
:PY+: cùn sī bù guà  
:OC+: tshuuns sɯ pɯʔ kʷrees  
:MC+: tshuo̝n sɨ pi̯ut kɣɛ  
:END: 
**** SOURCE REFERENCES
***** HYDCD(RED)
, p.1267a


With reference to a parallel passage in JINGDECHUANDENGLU

***** JINGDECHUANDENGLU
 - [[cite:JINGDECHUANDENGLU][(), 景德傳燈錄 Jǐngdé chuándēng lù The Record of the Transmission of the Lamp Published in the Jǐngdé Era Taishō]], p.258b
 (陸異日又謂師曰。弟子亦薄會佛法。師便問大夫十二時中作麼生。陸云。寸絲不掛。師云。猶是階下漢。)
***** JINGDECHUANDENGLU
 - [[cite:JINGDECHUANDENGLU][(), 景德傳燈錄 Jǐngdé chuándēng lù The Record of the Transmission of the Lamp Published in the Jǐngdé Era Taishō]], p.304c
 (僧問。如何是和尚不欺人眼。師曰。看看冬到來。僧曰。究竟如何。師曰。即便春風至。問遠聞和尚6寸絲7不掛。及至到來為什麼有山可守。師曰。道什麼。僧喝。師亦喝。僧禮拜。)
**** S [[tls:syn-func::#uuid-0527dea4-756f-489b-8843-0ebc52441e20][V{S}]] / BUDDH: not to hang from a tiny thread of silk > Zen phrase which expresses that the mind fundamenta...
:PROPERTIES:
:CUSTOM_ID: uuid-9e828891-2bd0-464e-8d59-12e27a4cfff4
:END:
****** DEFINITION

BUDDH: not to hang from a tiny thread of silk > Zen phrase which expresses that the mind fundamentally is without any obstruction and dependance

****** NOTES

*** 無情說法 wúqíngshuōfǎ (OC:ma dzeŋ lʰod pab MC:mi̯o dziɛŋ ɕiɛt pi̯ɐp )
:PROPERTIES:
:CUSTOM_ID: uuid-e9b83d01-45d9-4e47-825d-c5c74ac0e2b9
:Char+: 無(86,8/12) 情(61,8/11) 說(149,7/14) 法(85,5/8) 
:GY_IDS+: uuid-5de002ac-c1a1-4519-a177-4a3afcc155bb uuid-fe0dbc1f-2ca0-4174-9787-b9511e7f67fb uuid-08ee826a-8ac2-45df-9f16-72515d87430c uuid-bcc31133-8ffb-45d4-aeeb-442e8943f17e
:PY+: wú qíng shuō fǎ  
:OC+: ma dzeŋ lʰod pab  
:MC+: mi̯o dziɛŋ ɕiɛt pi̯ɐp  
:END: 
**** SOURCE REFERENCES
***** SHARF 2002
 - [[cite:SHARF-2002][Sharf(2002), Coming to Terms with Chinese Buddhism]], p.247, 335


As Robert Sharf has pointed out the question whether inanimated objects possessed Buddha-nature was a source of controversy in the medieval period and especially in the debates between the northern and southern factions of Cha2n. The theory that also inanimated objects possess Buddha-nature is possibly based on the writings of Ji4ngyi3ng Hui4yua3n 淨影慧遠 (523-592) who "[...] distinguished between the buddha-nature that abides at all times in all places and the buddha-nature that is actualized in enlightened sentient beings. But Hui4yua3n stopped short of explicitely claiming that inanimate objects possess budha-nature. The first person to do so appears to have been the Sa1nlu2n 三輪 exegete Ji2za1ng 吉藏 (549-623), who argued that the very distinction between sentient and insentient is illegitimate, and thus, if budda-nature can be said to exist at all, then it must be possessed  by both the sentient and the insentient." (Sharf 2002: 247) The doctrine was also taken up by members of the Tia1nta2i school, escpecially Zha4nra2n 湛然 (711-782). Many adherents of the early Cha2n school seem to have supported the doctrine, e.g. the Fourth Patriarch Da4oxi4n 道信 (580-651), the Fifth Patriarch Ho2ngre3n 弘忍 (601-674), possibly also She2nxiu4 神秀 (605?-706); see ibid.: 247-248. References on secondary works on this doctrine see in ibid.: 335, fn. 55.

**** S [[tls:syn-func::#uuid-0527dea4-756f-489b-8843-0ebc52441e20][V{S}]] / BUDDH: non-sentients expound the dharma (this phrase became very popular in Zen texts from the 10th...
:PROPERTIES:
:CUSTOM_ID: uuid-62983690-74db-400b-8af4-172716fbdf20
:END:
****** DEFINITION

BUDDH: non-sentients expound the dharma (this phrase became very popular in Zen texts from the 10th century onwards and became the subject of many discussions; for the first time it was elaborated on in ZTJ (952 A.D.); the phrase is usually connected to the teaching of Huìzhōng 慧忠, but also became an important topic in the teachings of Dòngshān 洞山)

****** NOTES

** BIBLIOGRAPHY
bibliography:../core/tlsbib.bib
